### ISSUE TITLE
Add embed image function

### ISSUE THREAD

**Issue by daojia** [a-ono/redmine_ckeditor#1]
Bonjour Hubert,

Génial ton Plugin, bravo pour ton travail, c'est exactement ce qu'il manque le plus à Redmine.
Je me demande si il serait possible d'ajouter la possibilité d'uploader une image sur le serveur ?
Je t'ai trouvé un script tout fait aux petits oignons pour CKEDITOR, dis nous c'est tu peux le faire.

http://www.mixedwaves.com/2010/02/integrating-fckeditor-filemanager-in-ckeditor/

La demo : 

http://www.mixedwaves.com/filemanager_in_ckeditor/demo.html

Merci !

Penses à l'ajouter à la page des plugins de Redmine : http://www.redmine.org/wiki/1/Plugin_List
Sinon personne ne va le trouver, et est-ce que tu sais s'il va être ajouté au projet par défaut ?

**Comment by elkharrazisoufyan-netizen** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Henrywash - Premium Car Wash</title>
<style>
  /* ===== Global Styles ===== */
  body { font-family: 'Poppins', sans-serif; margin:0; padding:0; background:#f5f5f5; color:#333;}
  a { text-decoration:none; color:inherit;}
  button { cursor:pointer; }

  /* ===== Hero ===== */
  .hero { 
    background: url('https://images.unsplash.com/photo-1563729784479-89d1de9f2a5c?auto=format&fit=crop&w=1470&q=80') center/cover no-repeat;
    height: 100vh;
    display:flex;
    flex-direction:column;
    justify-content:center;
    align-items:center;
    text-align:center;
    color:#fff;
    position:relative;
  }
  .hero::after{
    content:"";
    position:absolute; top:0; left:0; width:100%; height:100%;
    background:rgba(0,200,83,0.5);
  }
  .hero-content{position:relative; z-index:1;}
  .hero h1{font-size:3rem; margin-bottom:20px;}
  .hero p{font-size:1.2rem; margin-bottom:30px;}
  .hero button{background:#00C853; border:none; padding:15px 30px; font-size:1rem; color:#fff; border-radius:5px; transition:0.3s;}
  .hero button:hover{background:#009624;}

  /* ===== Services ===== */
  .services { padding:60px 20px; text-align:center;}
  .services h2{font-size:2.5rem; margin-bottom:40px; color:#00C853;}
  .service-cards{display:flex; flex-wrap:wrap; justify-content:center; gap:20px;}
  .card { background:#fff; padding:20px; border-radius:10px; width:250px; box-shadow:0 5px 15px rgba(0,0,0,0.1); transition:0.3s;}
  .card:hover{transform:translateY(-10px); box-shadow:0 10px 25px rgba(0,0,0,0.2);}
  .card h3{margin-bottom:15px; color:#00C853;}
  .card p{font-size:0.95rem;}

  /* ===== Gallery ===== */
  .gallery{padding:60px 20px;text-align:center;}
  .gallery h2{font-size:2.5rem; margin-bottom:40px; color:#00C853;}
  .gallery-grid{display:grid; grid-template-columns:repeat(auto-fit,minmax(250px,1fr)); gap:20px;}
  .gallery-grid img{width:100%; border-radius:10px; transition:0.3s;}
  .gallery-grid img:hover{transform:scale(1.05);}

  /* ===== Testimonials ===== */
  .testimonials{padding:60px 20px; background:#e0f2f1; text-align:center;}
  .testimonials h2{font-size:2.5rem; margin-bottom:40px; color:#00C853;}
  .testimonial{margin-bottom:20px; font-style:italic;}

  /* ===== Contact ===== */
  .contact{padding:60px 20px; text-align:center;}
  .contact h2{font-size:2.5rem; margin-bottom:40px; color:#00C853;}
  .contact a.button{background:#00C853; color:#fff; padding:15px 30px; border-radius:5px; display:inline-block; transition:0.3s;}
  .contact a.button:hover{background:#009624;}

  /* ===== Responsive ===== */
  @media(max-width:768px){
    .hero h1{font-size:2rem;}
    .hero p{font-size:1rem;}
    .service-cards{flex-direction:column; align-items:center;}
  }
</style>
</head>
<body>


<section class="hero">
  <div class="hero-content">
    <h1>Henrywash - Premium Car Wash</h1>
    <p>Professional Car Wash at your doorstep – Casablanca, Morocco</p>
    <button onclick="window.location.href='https://wa.me/0669602138'">Book Now via WhatsApp</button>
  </div>
</section>


<section class="services">
  <h2>Our Services</h2>
  <div class="service-cards">
    <div class="card"><h3>Lavage Simple</h3><p>Exterior cleaning only – 99 DH</p></div>
    <div class="card"><h3>Lavage Complet</h3><p>Interior & exterior cleaning – 299 DH</p></div>
    <div class="card"><h3>Polissage & Wax</h3><p>Remove light scratches & shine</p></div>
    <div class="card"><h3>Nettoyage Villas</h3><p>Full villa cleaning – floors, glass & furniture</p></div>
  </div>
</section>


<section class="gallery">
  <h2>Gallery</h2>
  <div class="gallery-grid">
    <img src="https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80" alt="Car 1">
    <img src="https://images.unsplash.com/photo-1583267749221-19918f8e1c6c?auto=format&fit=crop&w=800&q=80" alt="Car 2">
    <img src="https://images.unsplash.com/photo-1563729784479-89d1de9f2a5c?auto=format&fit=crop&w=800&q=80" alt="Car 3">
  </div>
</section>


<section class="testimonials">
  <h2>What Our Clients Say</h2>
  <p class="testimonial">“Service exceptionnel, ma voiture est comme neuve.” ⭐⭐⭐⭐⭐</p>
  <p class="testimonial">“Henrywash أفضل lavage à domicile في كازا.” ⭐⭐⭐⭐⭐</p>
</section>


<section class="contact">
  <h2>Contact Us</h2>
  <a class="button" href="https://wa.me/0669602138">Book Now via WhatsApp</a>
</section>

</body>
</html>

**Comment by elkharrazisoufyan-netizen** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Henrywash - Premium Car Wash</title>
<style>
  /* ===== Global Styles ===== */
  body { font-family: 'Poppins', sans-serif; margin:0; padding:0; background:#f5f5f5; color:#333;}
  a { text-decoration:none; color:inherit;}
  button { cursor:pointer; }

  /* ===== Hero ===== */
  .hero { 
    background: url('https://images.unsplash.com/photo-1563729784479-89d1de9f2a5c?auto=format&fit=crop&w=1470&q=80') center/cover no-repeat;
    height: 100vh;
    display:flex;
    flex-direction:column;
    justify-content:center;
    align-items:center;
    text-align:center;
    color:#fff;
    position:relative;
  }
  .hero::after{
    content:"";
    position:absolute; top:0; left:0; width:100%; height:100%;
    background:rgba(0,200,83,0.5);
  }
  .hero-content{position:relative; z-index:1;}
  .hero h1{font-size:3rem; margin-bottom:20px;}
  .hero p{font-size:1.2rem; margin-bottom:30px;}
  .hero button{background:#00C853; border:none; padding:15px 30px; font-size:1rem; color:#fff; border-radius:5px; transition:0.3s;}
  .hero button:hover{background:#009624;}

  /* ===== Services ===== */
  .services { padding:60px 20px; text-align:center;}
  .services h2{font-size:2.5rem; margin-bottom:40px; color:#00C853;}
  .service-cards{display:flex; flex-wrap:wrap; justify-content:center; gap:20px;}
  .card { background:#fff; padding:20px; border-radius:10px; width:250px; box-shadow:0 5px 15px rgba(0,0,0,0.1); transition:0.3s;}
  .card:hover{transform:translateY(-10px); box-shadow:0 10px 25px rgba(0,0,0,0.2);}
  .card h3{margin-bottom:15px; color:#00C853;}
  .card p{font-size:0.95rem;}

  /* ===== Gallery ===== */
  .gallery{padding:60px 20px;text-align:center;}
  .gallery h2{font-size:2.5rem; margin-bottom:40px; color:#00C853;}
  .gallery-grid{display:grid; grid-template-columns:repeat(auto-fit,minmax(250px,1fr)); gap:20px;}
  .gallery-grid img{width:100%; border-radius:10px; transition:0.3s;}
  .gallery-grid img:hover{transform:scale(1.05);}

  /* ===== Testimonials ===== */
  .testimonials{padding:60px 20px; background:#e0f2f1; text-align:center;}
  .testimonials h2{font-size:2.5rem; margin-bottom:40px; color:#00C853;}
  .testimonial{margin-bottom:20px; font-style:italic;}

  /* ===== Contact ===== */
  .contact{padding:60px 20px; text-align:center;}
  .contact h2{font-size:2.5rem; margin-bottom:40px; color:#00C853;}
  .contact a.button{background:#00C853; color:#fff; padding:15px 30px; border-radius:5px; display:inline-block; transition:0.3s;}
  .contact a.button:hover{background:#009624;}

  /* ===== Responsive ===== */
  @media(max-width:768px){
    .hero h1{font-size:2rem;}
    .hero p{font-size:1rem;}
    .service-cards{flex-direction:column; align-items:center;}
  }
</style>
</head>
<body>


<section class="hero">
  <div class="hero-content">
    <h1>Henrywash - Premium Car Wash</h1>
    <p>Professional Car Wash at your doorstep – Casablanca, Morocco</p>
    <button onclick="window.location.href='https://wa.me/0669602138'">Book Now via WhatsApp</button>
  </div>
</section>


<section class="services">
  <h2>Our Services</h2>
  <div class="service-cards">
    <div class="card"><h3>Lavage Simple</h3><p>Exterior cleaning only – 99 DH</p></div>
    <div class="card"><h3>Lavage Complet</h3><p>Interior & exterior cleaning – 299 DH</p></div>
    <div class="card"><h3>Polissage & Wax</h3><p>Remove light scratches & shine</p></div>
    <div class="card"><h3>Nettoyage Villas</h3><p>Full villa cleaning – floors, glass & furniture</p></div>
  </div>
</section>


<section class="gallery">
  <h2>Gallery</h2>
  <div class="gallery-grid">
    <img src="https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80" alt="Car 1">
    <img src="https://images.unsplash.com/photo-1583267749221-19918f8e1c6c?auto=format&fit=crop&w=800&q=80" alt="Car 2">
    <img src="https://images.unsplash.com/photo-1563729784479-89d1de9f2a5c?auto=format&fit=crop&w=800&q=80" alt="Car 3">
  </div>
</section>


<section class="testimonials">
  <h2>What Our Clients Say</h2>
  <p class="testimonial">“Service exceptionnel, ma voiture est comme neuve.” ⭐⭐⭐⭐⭐</p>
  <p class="testimonial">“Henrywash أفضل lavage à domicile في كازا.” ⭐⭐⭐⭐⭐</p>
</section>


<section class="contact">
  <h2>Contact Us</h2>
  <a class="button" href="https://wa.me/0669602138">Book Now via WhatsApp</a>
</section>

</body>
</html>

**Comment by elkharrazisoufyan-netizen** [comment]
<img width="800" height="800" alt="Image" src="https://github.com/user-attachments/assets/9a7e2c2a-d429-4362-9476-5729e80aeb23" />
