### ISSUE TITLE
Bundler could not find compatible versions for gem "railties"

### ISSUE THREAD

**Issue by Polve** [a-ono/redmine_ckeditor#103]
I get this error while running:
rake redmine:plugins:migrate RAILS_ENV=production

Bundler could not find compatible versions for gem "railties":
  In Gemfile:
    rich (= 1.4.6) ruby depends on
      railties (< 5.0, >= 4.0.0) ruby

    jquery-rails (~> 2.0.2) ruby depends on
      railties (3.2.17)

I'm using redmine 2.4.4 with a couple of other plugins

**Comment by a-ono** [comment]
You should execute bundle within the Redmine root directory.
