### ISSUE TITLE
Incompatible with plugin 'simpleuploads'

### ISSUE THREAD

**Issue by optio** [a-ono/redmine_ckeditor#109]
Hi,

I've installed the simpleupload plugin (http://alfonsoml.blogspot.be/p/simpleuploads-plugin-for-ckeditor.html) by copying the files to /ckeditor-contrib/plugins/simpleuploads  , though it doesn't work.
It seems the plugin isn't even loaded.

The install should only require to add : config.extraPlugins='simpleuploads'; though I assume this is done automatically by redmine_ckeditor ?

**Comment by ChetWang** [comment]
Hi @optio & @a-ono 
simpleuploads can work with redmine_ckeditor. It's true that let redmine_ckeditor completely support image paste and upload needs a lot of work. But, just leave the upload to another process, ex, I use php + ckfinder, enven a simple script in https://github.com/AlfonsoML/CKEditorUploader
