### ISSUE TITLE
I get "Could not upload your file" error when I try to upload an image

### ISSUE THREAD

**Issue by Allanon29** [a-ono/redmine_ckeditor#116]
I get the following error when I try to upload an image:

"Could not upload your file:
- rich_file Paperclip::Errors::NotIdentifiedByImageMagickError"

The error occurs on Centos 6.5. 
ImageMagick 6.8.9-3 (Also tried with an older version - ImageMagick-6.5.4.7-7.el6_5.x86_64 - but same error)
jRuby 1.7.12
Redmine 2.5 stable

Any idea what causes this?

UPDATE:
It seems that this happens only if I use Torquebox.

**Comment by a-ono** [comment]
JRuby is not supported.
