### ISSUE TITLE
Bundler could not find compatible versions for gem "sprockets" (tag 1.0.16)

### ISSUE THREAD

**Issue by tzieleniewski** [a-ono/redmine_ckeditor#120]
Hi,

I encountered the following problem during plugin a installation in the version 1.0.16:

bundle install --without development test --local --verbose
The source :rubygems is deprecated because HTTP requests are insecure.
Please change your source to 'https://rubygems.org' if possible, or 'http://rubygems.org' if not.
Resolving dependencies...
Bundler could not find compatible versions for gem "sprockets":
  In Gemfile:
    rich (= 1.4.6) ruby depends on
      sprockets (<= 2.11.0, ~> 2.8) ruby

    rails (= 3.2.18) ruby depends on
      sprockets (2.2.2)
Bundler::VersionConflict: Bundler could not find compatible versions for gem "sprockets":
  In Gemfile:
    rich (= 1.4.6) ruby depends on
      sprockets (<= 2.11.0, ~> 2.8) ruby

    rails (= 3.2.18) ruby depends on
      sprockets (2.2.2)

Redmine Environment:
  Redmine version                2.4.5.stable.13207
  Ruby version                   1.9.3-p194 (2012-04-20) [x86_64-linux]
  Rails version                  3.2.18
  Environment                    production
  Database adapter               Mysql2

RubyGems Environment:
  - RUBYGEMS VERSION: 1.8.23
  - RUBY VERSION: 1.9.3 (2012-04-20 patchlevel 194) [x86_64-linux]
  - INSTALLATION DIRECTORY: /var/lib/gems/1.9.1
  - RUBY EXECUTABLE: /usr/bin/ruby1.9.1
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux

Kind regards,
- Tomasz

**Comment by a-ono** [comment]
You should execute bundle within the Redmine root directory.
rich doesn't depend on sprockets.
