### ISSUE TITLE
error: There's no setting named plugin_redmine_ckeditor

### ISSUE THREAD

**Issue by palytoxin** [a-ono/redmine_ckeditor#121]
this plugin is so fantastic!
but I found a problem in using redmine 2.3

I have done the following steps
1. copy this plugin to redmine/plugins/(folder name is redmine_ckeditor)
2. bundle install 
3. rake redmine:plugins:migrate
4. rails server; and starting redmine
5. Change text formatting
6. Configure the plugin

now, the plugin is work fine.

but, i'm press ctrl-c to  stop rails server, and restart 
visit 'http://127.0.0.1:3000/settings/plugin/redmine_ckeditor'
I got a error ` no setting named plugin_redmine_ckeditor`

however, plugin_redmine_ckeditor is  in my mysql by sql query
`SELECT * FROM `settings` WHERE NAME = 'plugin_redmine_ckeditor';`

When I run ` rake redmine:plugins:migrate` again , the server does not even being given erros.

Redmine 2.3, Redmine CKEditor plugin is HEAD of github

**Comment by a-ono** [comment]
It seems not to be a bug in this plugin.
