### ISSUE TITLE
LoadError: No such file to load -- rich/files_helper

### ISSUE THREAD

**Issue by mwaeckerlin** [a-ono/redmine_ckeditor#131]
Unfortunately, installartion of the plugin does not work (Ubuntu 14.04, redmine 2.4.2-1):

redmine_ckeditor-1.0.16 extracted into /usr/share/redmine/plugins (I also tried latest master, same result): LoadError: No such file to load -- rich/files_helper

What's the problem and how can I resolve it?

Then:

<pre>
marc@dev0101:/usr/share/redmine$ sudo bundle install --without development test        
Resolving dependencies...
Using rake (10.3.2) 
Using i18n (0.6.11) 
Using json (1.8.1) 
Using minitest (5.4.1) 
Using thread_safe (0.3.4) 
Using tzinfo (1.2.2) 
Using activesupport (4.1.6) 
Using builder (3.2.2) 
Using erubis (2.7.0) 
Using actionview (4.1.6) 
Using rack (1.5.2) 
Using rack-test (0.6.2) 
Using actionpack (4.1.6) 
Using mime-types (2.3) 
Using mail (2.6.1) 
Using actionmailer (4.1.6) 
Using activemodel (4.1.6) 
Using arel (5.0.1.20140414130214) 
Using activerecord (4.1.6) 
Using bundler (1.3.5) 
Using climate_control (0.0.3) 
Using cocaine (0.5.4) 
Using hike (1.2.3) 
Using htmlentities (4.3.2) 
Using thor (0.19.1) 
Using railties (4.1.6) 
Using jquery-rails (3.1.2) 
Using kaminari (0.16.1) 
Using multi_json (1.10.1) 
Using paperclip (3.5.4) 
Using rack-raw-upload (1.1.1) 
Using tilt (1.4.1) 
Using sprockets (2.11.0) 
Using sprockets-rails (2.1.4) 
Using rails (4.1.6) 
Using sass (3.2.19) 
Using sass-rails (4.0.3) 
Using rich (1.4.6) 
Your bundle is complete!
Gems in the groups development and test were not installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
marc@dev0101:/usr/share/redmine$ sudo rake redmine:plugins:migrate RAILS_ENV=production
rake aborted!
LoadError: No such file to load -- rich/files_helper

Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
marc@dev0101:/usr/share/redmine$ sudo rake redmine:plugins:migrate RAILS_ENV=production --trace
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
LoadError: No such file to load -- rich/files_helper
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:317:in `rescue in depend_on'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:312:in `depend_on'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:225:in `require_dependency'
/usr/share/redmine/plugins/redmine_ckeditor-1.0.16/lib/redmine_ckeditor/rich_files_helper_patch.rb:1:in `<top (required)>'
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:251:in `block in require'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:236:in `load_dependency'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:251:in `require'
/usr/share/redmine/plugins/redmine_ckeditor-1.0.16/lib/redmine_ckeditor.rb:115:in `apply_patch'
/usr/share/redmine/plugins/redmine_ckeditor-1.0.16/init.rb:5:in `block in <top (required)>'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:429:in `_run__811873108__prepare__601859396__callbacks'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:405:in `__run_callback'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:385:in `_run_prepare_callbacks'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:81:in `run_callbacks'
/usr/lib/ruby/vendor_ruby/action_dispatch/middleware/reloader.rb:74:in `prepare!'
/usr/lib/ruby/vendor_ruby/action_dispatch/middleware/reloader.rb:48:in `prepare!'
/usr/lib/ruby/vendor_ruby/rails/application/finisher.rb:47:in `block in <module:Finisher>'
/usr/lib/ruby/vendor_ruby/rails/initializable.rb:30:in `instance_exec'
/usr/lib/ruby/vendor_ruby/rails/initializable.rb:30:in `run'
/usr/lib/ruby/vendor_ruby/rails/initializable.rb:55:in `block in run_initializers'
/usr/lib/ruby/vendor_ruby/rails/initializable.rb:54:in `each'
/usr/lib/ruby/vendor_ruby/rails/initializable.rb:54:in `run_initializers'
/usr/lib/ruby/vendor_ruby/rails/application.rb:136:in `initialize!'
/usr/lib/ruby/vendor_ruby/rails/railtie/configurable.rb:30:in `method_missing'
/usr/share/redmine/config/environment.rb:14:in `<top (required)>'
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:251:in `block in require'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:236:in `load_dependency'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:251:in `require'
/usr/lib/ruby/vendor_ruby/rails/application.rb:103:in `require_environment!'
/usr/lib/ruby/vendor_ruby/rails/application.rb:305:in `block (2 levels) in initialize_tasks'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:240:in `call'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:240:in `block in execute'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:235:in `each'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:235:in `execute'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:199:in `each'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:199:in `invoke_prerequisites'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:165:in `invoke'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:150:in `invoke_task'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:106:in `each'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:106:in `block in top_level'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:115:in `run_with_threads'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:100:in `top_level'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:78:in `block in run'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
/var/lib/gems/1.9.1/gems/rake-10.3.2/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
</pre>

**Comment by a-ono** [comment]
It seems something wrong with Redmine installation.
Redmine 2.x doesn't depend on rails (4.1.6).

**Comment by mtyu** [comment]
Hi,

I used the defult redmine package from Ubuntu 14.04.3 LTS and met the same problem as the following.

Redmine 2.4.2.stable

Default administrator account changed	True
Attachments directory writable	True
Plugin assets directory writable	True
RMagick available (optional)	True
ImageMagick convert available (optional)	True

Environment:
  Redmine version                2.4.2.stable
  Ruby version                   1.9.3-p484 (2013-11-22) [x86_64-linux]
  Rails version                  3.2.16
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            1.9.1
  Filesystem                     
Redmine plugins:
  no plugin installed

:/usr/share/redmine$ sudo bundle install --without development test
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users on this machine.
Rubygems 1.8.23 is not threadsafe, so your gems will be installed one at a time. Upgrade to Rubygems 2.1.0 or higher to enable parallel gem installation.
Resolving dependencies...
Using rake 10.5.0
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.8.4
Using thread_safe 0.3.5
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile2 2.0.0
Using rack 1.6.4
Using mime-types 2.99
Using arel 6.0.3
Using bundler 1.11.2
Using concurrent-ruby 1.0.0
Using htmlentities 4.3.4
Using thor 0.19.1
Using multi_json 1.11.2
Using mysql2 0.4.2
Using pandoc-ruby 1.0.0
Using sass 3.4.21
Using tilt 2.0.2
Using tzinfo 1.2.2
Using nokogiri 1.6.7.2
Using rack-test 0.6.3
Using mail 2.6.3
Using sprockets 3.5.2
Using rack-raw-upload 1.1.1
Using activesupport 4.2.5.1
Using loofah 2.0.3
Using rails-deprecated_sanitizer 1.0.3
Using globalid 0.3.6
Using activemodel 4.2.5.1
Using climate_control 0.0.3
Using rails-html-sanitizer 1.0.3
Using rails-dom-testing 1.0.7
Using activejob 4.2.5.1
Using activerecord 4.2.5.1
Using cocaine 0.5.8
Using actionview 4.2.5.1
Using paperclip 3.5.4
Using actionpack 4.2.5.1
Using actionmailer 4.2.5.1
Using railties 4.2.5.1
Using kaminari 0.16.3
Using sprockets-rails 3.0.1
Using jquery-rails 4.1.0
Using rails 4.2.5.1
Using sass-rails 5.0.4
Using rich 1.4.6
Bundle complete! 6 Gemfile dependencies, 48 gems now installed.
Gems in the groups development and test were not installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.

:/usr/share/redmine$ sudo rake redmine:plugins:migrate RAILS_ENV=production
rake aborted!
LoadError: No such file to load -- rich/files_helper
/usr/share/redmine/plugins/redmine_ckeditor/lib/redmine_ckeditor/rich_files_helper_patch.rb:1:in `<top (required)>'
/usr/share/redmine/plugins/redmine_ckeditor/lib/redmine_ckeditor.rb:128:in `apply_patch'
/usr/share/redmine/plugins/redmine_ckeditor/init.rb:5:in `block in <top (required)>'
/usr/share/redmine/config/environment.rb:14:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

Do you know why the above happened? I Googleed for more than a week but still can not resolved this issue. Looks similar to the issue reported here (https://www.redmine.org/boards/3/topics/46292), but I have no luck to resolve it in the same way. Seems that rich is not installed well. Could you help me and see where I did wrong?

Thanks a lot!
