### ISSUE TITLE
Encoding problem regarding links in the Wiki

### ISSUE THREAD

**Issue by jecoffey** [a-ono/redmine_ckeditor#132]
After installing CKEditor, I have a few broken links in my wiki, specifically those containing accentuated letters (é; è; à; ...). Plain text shows those correctly, but links show the html encoding. 

Any clues, hints?

Thanks in advance...

**Comment by rompic** [comment]
any updates on this?

**Comment by a-ono** [comment]
I just updated the plugin. Please check it out.

**Comment by rompic** [comment]
thank you. if you,by any chance, can update the ckeditor version used as well, i will test it tomorrow. (see https://github.com/zinw/redmine_ckeditor)

**Comment by rompic** [comment]
works for me!

**Comment by jecoffey** [comment]
Works for me too! 

Thanks for the update!
