### ISSUE TITLE
Error that it can't install climate_control

### ISSUE THREAD

**Issue by govmeeting** [a-ono/redmine_ckeditor#136]
Please tell me where I should be asking this, if I am in the wrong place.

I am trying to install on redmine 2.5.2 with ruby 1.9.3. I moved the latest redmine_ckeditor to the plugins directory and ran "bundle install --without development test". I get an error that it can't install climate_control. Here is the output of the bundle command:

Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
Using rake 10.1.1
Using i18n 0.6.11
Using multi_json 1.10.1
Using activesupport 3.2.19
Using builder 3.0.0
Using activemodel 3.2.19
Using erubis 2.7.0
Using journey 1.0.4
Using rack 1.4.5
Using rack-cache 1.2
Using rack-test 0.6.2
Using hike 1.2.3
Using tilt 1.4.1
Using sprockets 2.2.2
Using actionpack 3.2.19
Using mime-types 1.25.1
Using polyglot 0.3.5
Using treetop 1.4.15
Using mail 2.5.4
Using actionmailer 3.2.19
Using arel 3.0.3
Using tzinfo 0.3.41
Using activerecord 3.2.19
Using activeresource 3.2.19
Using awesome_nested_set 2.1.6
Using bundler 1.7.4

Gem::RemoteFetcher::FetchError: SSL_connect returned=1 errno=0 state=SSLv3 read
server certificate B: certificate verify failed (https://rubygems.global.ssl.fas
tly.net/gems/climate_control-0.0.3.gem)
An error occurred while installing climate_control (0.0.3), and Bundler cannot
continue.
Make sure that `gem install climate_control -v '0.0.3'` succeeds before
bundling.

**Comment by a-ono** [comment]
It's an SSL connection error.
http://stackoverflow.com/questions/10246023/bundle-install-fails-with-ssl-certificate-verification-error
