### ISSUE TITLE
Syntax highlighting not available for Redmine 2.6.0

### ISSUE THREAD

**Issue by reds-heig** [a-ono/redmine_ckeditor#137]
Hi,

I've spent the past 2 hours trying to make syntax highlighting work for Redmine, with absolutely no result. If I put codesnippet in assets/ckeditor-contrib/plugins, then the plugin crashes miserably and it does not show up. In particular, the error is the following one:
```
Started GET "/plugin_assets/redmine_ckeditor/ckeditor/plugins/widget/plugin.js?t=E0LB" for 127.0.0.1 at 2014-12-15 10:41:17 +0100

ActionController::RoutingError (No route matches [GET] "/plugin_assets/redmine_ckeditor/ckeditor/plugins/widget/plugin.js"):
  actionpack (3.2.20) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (3.2.20) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.20) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.20) lib/rails/rack/logger.rb:16:in `block in call'
  activesupport (3.2.20) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.20) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.20) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.20) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.5) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.20) lib/action_dispatch/middleware/static.rb:82:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in `lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.20) lib/rails/engine.rb:484:in `call'
  railties (3.2.20) lib/rails/application.rb:231:in `call'
  railties (3.2.20) lib/rails/railtie/configurable.rb:30:in `method_missing'
  puma (2.9.2) lib/puma/configuration.rb:71:in `call'
  puma (2.9.2) lib/puma/server.rb:490:in `handle_request'
  puma (2.9.2) lib/puma/server.rb:361:in `process_client'
  puma (2.9.2) lib/puma/server.rb:254:in `block in run'
  puma (2.9.2) lib/puma/thread_pool.rb:92:in `call'
  puma (2.9.2) lib/puma/thread_pool.rb:92:in `block in spawn_thread'
```
I have tried creating a custom zip from ckeditor website and replacing the ckeditor directory with the one in the zip, and it worked for other plugins but still no syntax higlighting. I have tested other highlighting plugins, but with the same result. I can have youtube import, smileys, ... but no syntax highlighting (what I mean is that there is no entry in the menu selection that refers to syntax highlighting).
Could you please help me solve this one?
Thanks a lot!
Rob

**Comment by rompic** [comment]
hi there,
the codesnippet add-on dependencies are(according to http://ckeditor.com/addon/codesnippet ->download):
    **Widget**
    Dialog

have you installed those as well?

I was also looking into the syntax highlighting issue as well and thought about writing an even simpler ck-editor plugin that only inserts the <code> tags and language attributes. what do you think?

**Comment by reds-heig** [comment]
Hi,

Thanks a lot, now I have no errors in the logfile!
On the other hand, still no syntax highlighting... :S
The problem is that, when I go in the configuration page of the ckeditor plugin in redmine, I don't see the corresponding button to add to the toolbar.... :(

**Comment by rompic** [comment]
according to the readme:
Plugins
You can download plugins from Add-ons Repository. To activate the plugin you have to copy the plugin directory into assets/ckeditor-contrib/plugins and **restart** Redmine, then configure toolbar settings.

did you try that as well?

**Comment by reds-heig** [comment]
Yes, I have also tried modifying the configuration files by hand, and many more things.
I have found a workaround right now: I have copied the whole ckeditor directory from an old redmine installation where the highlighting plugin was working, and I've installed in the new redmine I am configuring. I won't have the latest ckeditor, but at least it works...
Thanks anyway for your help!!

**Comment by rompic** [comment]
any hints on what could be different in these two folders (except the version). I want to setup code-highlighting as wel.

**Comment by reds-heig** [comment]
No clue.... I've spent several hours trying to figure them out -- to fix my problem -- but without any luck.
From what I see (it was another person that set up the old redmine, and he has left the company some time ago) the plugin is not in ckeditor-contrib/plugins but directly in the ckeditor/plugins directory -- I believe this is what you can get if you select the plugin manually in the download page of ckeditor -- but I wasn't able to discover other significant differences...

**Comment by rompic** [comment]
which version is your "old" ckeditor? the code snippet plugin is only supported since 4.4
http://ckeditor.com/addon/codesnippet
ckeditor in this repo is still on 4.3.2

see https://github.com/zinw/redmine_ckeditor/commit/445fd7064e6ff2bcf3a54db149a56a653d00bbda for an update.

**Comment by reds-heig** [comment]
It is the 4.4.2 version, therefore not so old indeed...
Maybe it is the fact that the new one is the 4.4.6 and even the zinw version supports the 4.4.5.... :S

**Comment by rompic** [comment]
ah I see ;). I'll try to test with the 4.4.5 version in the zinw branch in the next few weeks and report back

**Comment by reds-heig** [comment]
:) Thanks a lot! (I haven't noticed the version number before -- my fault, sorry!)

**Comment by rompic** [comment]
hello again. 
ckeditor version has just been updated:
https://github.com/a-ono/redmine_ckeditor/issues/134#event-215352651

do you have the time to try your initial setup again?

**Comment by reds-heig** [comment]
Hello,

I've tried but still it doesn't work (the codesnippet entry does not appear in the menu)...
Thanks anyway! :)

**Comment by a-ono** [comment]
I have confirmed it.
You should put three add-ons below into the assets/ckeditor-contrib/plugins directory.
http://ckeditor.com/addon/codesnippet
http://ckeditor.com/addon/widget
http://ckeditor.com/addon/lineutils

Unfortunately, codesnippet generates the "language-" prefixed class name, and it's not compatible with Redmine's syntax highlighter.

**Comment by reds-heig** [comment]
Thanks for your reply, now it works correctly! :)

**Comment by yozart** [comment]
In order to get it working I added following lines at the end of <head> tag in file app\views\layouts\base.html.erb


<link href="/redmine/plugin_assets/redmine_ckeditor/ckeditor-contrib/plugins/codesnippet//lib/highlight/styles/default.css" rel="stylesheet" />
<script src="/redmine/plugin_assets/redmine_ckeditor/ckeditor-contrib/plugins/codesnippet//lib/highlight/highlight.pack.js"></script>
<script>hljs.initHighlightingOnLoad();</script>	


I know this isn't very optimized but I'm not a ruby devs so this is the best I can do without spending few days on it. I'll be glad to get a proper version if any of you is able to provide.

**Comment by rompic** [comment]
I would love to see a proper version of it.

**Comment by rompic** [comment]
unfortunately using code tags is broken using the newest release

**Comment by ChetWang** [comment]
it works in redmine 3.0 as yozart  said.

**Comment by Luckyvb** [comment]
I think not best regex in formatter gsub. i use:
```ruby
    def to_html(&block)
      auto_link!(@text)
      ActionView::Base.white_list_sanitizer.sanitize(@text,
        :tags => RedmineCkeditor.allowed_tags,
        :attributes => RedmineCkeditor.allowed_attributes
      ).gsub(/<pre>([\r\n\s]*(?!<\w+.*[\/]*>).*[\r\n\s]*|\s*[\r\n\s]*)<code\s+(?:class="(\w+|\w+\s*.+)")>(((?!<\/code>)[\s\S])*)<\/code>[\r\n\s]*((?!<\w+.*[\/]*>).*|\s*)[\r\n\s]*<\/pre>/) {
        prefix, lang, code, suffix = $~.captures
        %Q[<pre>#{prefix.html_safe}\n<code class="#{lang} syntaxhl">#{
          Redmine::SyntaxHighlighting.highlight_by_language(code, lang.split(' ')[0])
        }</code>\n#{suffix.html_safe}</pre>]
      }.gsub(/\{\{(.*?)\}\}/) {
        "{{" + CGI.unescapeHTML($1) + "}}"
      }
    end
```

**Comment by vvklymchuk** [comment]
I use codesnippet  + redmine highlightjs plugin [https://github.com/dominch/redmine_highlightjs](url)
Works very well

**Comment by archonwang** [comment]
@vvklymchuk 
could you tell me how to config codesnippet? Thanks so much.

**Comment by vvklymchuk** [comment]
archonwang said:
> could you tell me how to config codesnippet? Thanks so much.

For codesnippet I changed only theme in file plugin.js of this plugin
You must Install plugins as specified above [link](https://github.com/a-ono/redmine_ckeditor/issues/137#issuecomment-69185282)
If codesnippet doesn't work when ckeditor is loaded, check redmine log for errors. Maybe some other plugins are missed from your ckeditor install.

**Comment by archonwang** [comment]
Thanks @vvklymchuk 
I have made it worked.

**Comment by DeaconF** [comment]
@vvklymchuk 
after installing redmine_highlightjs the source code view in CK_Editor doesn't work :(

**Comment by vvklymchuk** [comment]
@DeaconF 
I replaced CodeMirror (current source code plugin) with [Source Dialog](http://ckeditor.com/addon/sourcedialog) in ..\redmine_ckeditor\assets\ckeditor-contrib\plugins\
