### ISSUE TITLE
Bundler could not find compatible versions of gem railties

### ISSUE THREAD

**Issue by nixmomo** [a-ono/redmine_ckeditor#142]
Issue:

 rake redmine:plugins:migrate RAILS_ENV=production
Bundler could not find compatible versions for gem "railties":
  In Gemfile:
    rich (= 1.4.6) ruby depends on
      sass-rails (>= 0) ruby depends on
        railties (< 5.0, >= 4.0.0) ruby

    rails (= 3.2.21) ruby depends on
      railties (3.2.21)

by try install editor

**Comment by a-ono** [comment]
Please try below:
```
cd redmine/root/path
bundle install --without development test
bundle exec rake redmine:plugins:migrate RAILS_ENV=production
```

**Comment by nixmomo** [comment]
Ahh i found Issue by myself....it was a File Permission Error....
