### ISSUE TITLE
Error for small image (<111kb) upload

### ISSUE THREAD

**Issue by alexander-st** [a-ono/redmine_ckeditor#143]
I can upload big images above 111kb without any problem, but small images below 111kb cannot be uploaded via the "browse and upload image" function. I receive the following error:

>Could not upload your file:
>
>rich_file
>
>Paperclip:Errors::NotIdentifiedbyImageMagickError

I tested around 80 different images: all screenshots, all manipulated in the same software. I also tried a big image and then resized it to a small size. The big image was no problem, but again the small image gets the error.

I am using CKEditor in Redmine (Bitnami stack installation 2.6.0-3) and CKEditor 1.0.17.
The following is a small test image which fails to get uploaded.

![test image ](https://cloud.githubusercontent.com/assets/10597540/5822719/f6e4e574-a0de-11e4-8dc1-aa90289a0845.jpg)

Let me know what information you need.

I am trying to solve the issue for a few weeks now and I have no working solution for it.

The following is a part of the production log. The first part is the error of a small image upload, the second part is a working big image.

Started POST "/redmine/rich/files?authenticity_token=7TDEurqpb%2FUH%2FxtNfg0U9XHr5Bd09VpPo3T4YGXbEWA%3D&simplified_type=image&scoped=false&scope_type=undefined&scope_id=undefined&qqfile=404+error.jpg" for 127.0.0.1 at 2015-01-20 19:52:02 +0200
Processing by Rich::FilesController#create as */*
  Parameters: {"file"=>#<ActionDispatch::Http::UploadedFile:0x4e8f7f0 @original_filename="404%20error.jpg", @content_type="application/octet-stream", @headers=nil, @tempfile=#<Tempfile:C:/Windows/Temp/raw-upload.20150120-7744-pckvby>>, "authenticity_token"=>"7TDEurqpb/UH/xtNfg0U9XHr5Bd09VpPo3T4YGXbEWA=", "simplified_type"=>"image", "scoped"=>"false", "scope_type"=>"undefined", "scope_id"=>"undefined", "qqfile"=>"404 error.jpg"}
  Current user: alex (id=1)
Command :: identify -format '%wx%h,%[exif:orientation]' "C:/Windows/Temp/f6b779ebc630a37fa5ff8eb8fca99dce20150120-7744-1r9u1ba.jpg[0]" 2>NUL
[paperclip] An error was received while processing: #<Paperclip::Errors::NotIdentifiedByImageMagickError: Paperclip::Errors::NotIdentifiedByImageMagickError>
Command :: identify -format '%wx%h,%[exif:orientation]' "C:/Windows/Temp/f6b779ebc630a37fa5ff8eb8fca99dce20150120-7744-1r9u1ba.jpg[0]" 2>NUL
[paperclip] An error was received while processing: #<Paperclip::Errors::NotIdentifiedByImageMagickError: Paperclip::Errors::NotIdentifiedByImageMagickError>
Completed 200 OK in 727.5ms (Views: 4.0ms | ActiveRecord: 8.0ms)
Started GET "/redmine/rich/files/?CKEditor=settings_welcome_text&CKEditorFuncNum=2&default_style=original&allowed_styles=thumb%2Crich_thumb%2Coriginal&insert_many=false&type=image&scoped=false&viewMode=grid" for 127.0.0.1 at 2015-01-20 19:58:19 +0200
Processing by Rich::FilesController#index as HTML
  Parameters: {"CKEditor"=>"settings_welcome_text", "CKEditorFuncNum"=>"2", "default_style"=>"original", "allowed_styles"=>"thumb,rich_thumb,original", "insert_many"=>"false", "type"=>"image", "scoped"=>"false", "viewMode"=>"grid"}
  Current user: alex (id=1)
  Rendered plugins/redmine_ckeditor/app/views/rich/files/_file.html.erb (0.0ms)
  Rendered C:/Bitnami/redmine-2.6.0-3/ruby/lib/ruby/gems/2.0.0/gems/rich-1.4.6/app/views/rich/files/index.html.erb within layouts/rich/application (4.0ms)
Completed 200 OK in 16.0ms (Views: 12.0ms | ActiveRecord: 0.0ms)
Started POST "/redmine/rich/files?authenticity_token=7TDEurqpb%2FUH%2FxtNfg0U9XHr5Bd09VpPo3T4YGXbEWA%3D&simplified_type=image&scoped=false&scope_type=undefined&scope_id=undefined&qqfile=add+map+layer.jpg" for 127.0.0.1 at 2015-01-20 19:58:25 +0200
Processing by Rich::FilesController#create as */*
  Parameters: {"file"=>#<ActionDispatch::Http::UploadedFile:0x4284cd8 @original_filename="add%20map%20layer.jpg", @content_type="application/octet-stream", @headers=nil, @tempfile=#<Tempfile:C:/Windows/Temp/thin-body20150120-7744-193hezs>>, "authenticity_token"=>"7TDEurqpb/UH/xtNfg0U9XHr5Bd09VpPo3T4YGXbEWA=", "simplified_type"=>"image", "scoped"=>"false", "scope_type"=>"undefined", "scope_id"=>"undefined", "qqfile"=>"add map layer.jpg"}
  Current user: alex (id=1)
Command :: identify -format '%wx%h,%[exif:orientation]' "C:/Windows/Temp/76641da0baa496f98245929426f2258f20150120-7744-9z7s6i.jpg[0]" 2>NUL
Command :: identify -format %m "C:/Windows/Temp/76641da0baa496f98245929426f2258f20150120-7744-9z7s6i.jpg[0]"
Command :: identify -format %m "C:/Windows/Temp/76641da0baa496f98245929426f2258f20150120-7744-9z7s6i.jpg[0]"
Command :: identify -format %m "C:/Windows/Temp/76641da0baa496f98245929426f2258f20150120-7744-9z7s6i.jpg[0]"
Command :: convert "C:/Windows/Temp/76641da0baa496f98245929426f2258f20150120-7744-9z7s6i.jpg[0]" -auto-orient -resize "x100" -crop "100x100+38+0" +repage "C:/Windows/Temp/76641da0baa496f98245929426f2258f20150120-7744-9z7s6i20150120-7744-1jvxgea"
Command :: file -b --mime "C:/Windows/Temp/76641da0baa496f98245929426f2258f20150120-7744-9z7s6i20150120-7744-1jvxgea"
[paperclip] Error while determining content type: No such file or directory - file -b --mime "C:/Windows/Temp/76641da0baa496f98245929426f2258f20150120-7744-9z7s6i20150120-7744-1jvxgea"
Command :: identify -format '%wx%h,%[exif:orientation]' "C:/Windows/Temp/76641da0baa496f98245929426f2258f20150120-7744-9z7s6i.jpg[0]" 2>NUL
Command :: identify -format %m "C:/Windows/Temp/76641da0baa496f98245929426f2258f20150120-7744-9z7s6i.jpg[0]"
Command :: identify -format %m "C:/Windows/Temp/76641da0baa496f98245929426f2258f20150120-7744-9z7s6i.jpg[0]"
Command :: identify -format %m "C:/Windows/Temp/76641da0baa496f98245929426f2258f20150120-7744-9z7s6i.jpg[0]"
Command :: convert "C:/Windows/Temp/76641da0baa496f98245929426f2258f20150120-7744-9z7s6i.jpg[0]" -auto-orient -resize "x100" -crop "100x100+38+0" +repage "C:/Windows/Temp/76641da0baa496f98245929426f2258f20150120-7744-9z7s6i20150120-7744-19bf8oz"
Command :: file -b --mime "C:/Windows/Temp/76641da0baa496f98245929426f2258f20150120-7744-9z7s6i20150120-7744-19bf8oz"
[paperclip] Error while determining content type: No such file or directory - file -b --mime "C:/Windows/Temp/76641da0baa496f98245929426f2258f20150120-7744-9z7s6i20150120-7744-19bf8oz"
Completed 200 OK in 1704.5ms (Views: 0.0ms | ActiveRecord: 38.1ms)
Started GET "/redmine/rich/files/1" for 127.0.0.1 at 2015-01-20 19:58:27 +0200
Processing by Rich::FilesController#show as */*
  Parameters: {"id"=>"1"}
Settings cache cleared.
  Current user: alex (id=1)
  Rendered plugins/redmine_ckeditor/app/views/rich/files/_file.html.erb (4.0ms)
  Rendered C:/Bitnami/redmine-2.6.0-3/ruby/lib/ruby/gems/2.0.0/gems/rich-1.4.6/app/views/rich/files/show.html.erb (8.0ms)
Completed 200 OK in 136.0ms (Views: 84.0ms | ActiveRecord: 12.0ms)

**Comment by a-ono** [comment]
Maybe #54 and #112 are the same issues.
I believe I have fixed the bug, please check it out.

**Comment by alexander-st** [comment]
Your solution:
redmine_ckeditor\assets\javascripts\browser.js
line 318
from 
handlerClass = 'UploadHandlerXhr';

to 
handlerClass = 'UploadHandlerForm';

is working. Thank you!!!

The error was still very strange, because big images where no problem only small images produced the error.

**Comment by a-ono** [comment]
This is an issue of [rack-raw-upload](/New-Bamboo/rack-raw-upload#warning-there-seem-to-be-problems-running-this-on-windows), I have pushed the commit a7203d9 (another workaround) to master branch.
Please update the plugin.

**Comment by alexander-st** [comment]
Thank you a-ono!!!!
This fixes the problem. I just changed the lib/redmine_ckeditor.rb and added the lib/redmine_ckeditor/tempfile_patch.rb file and now everything works.
