### ISSUE TITLE
Redmine error occurs while exporting to PDF

### ISSUE THREAD

**Issue by adi-david** [a-ono/redmine_ckeditor#146]
Hi,
When I try to export issue to PDF, in certain situations, I get "Redmine 500 error: internal error" page.
For example, i noticed that it happen every time I'm trying to export issue that have the following table:
<table border="1" cellpadding="0" cellspacing="0">
	<tbody>
		<tr>
			<td style="width: 295px">
			<table border="1" cellpadding="0" cellspacing="0" style="width: 845px">
				<colgroup>
					<col />
					<col />
					<col />
					<col />
					<col />
				</colgroup>
				<tbody>
					<tr height="20">
						<td height="20" style="width: 181px; height: 20px">Name</td>
						<td style="width: 56px">Priority</td>
						<td style="width: 225px">Designation</td>
						<td style="width: 220px">Purpose</td>
						<td style="width: 163px">Comment</td>
					</tr>
					<tr height="20">
						<td height="20" style="height: 20px">123</td>
						<td>High</td>
						<td>123123</td>
						<td>123</td>
						<td> </td>
					</tr>
				</tbody>
			</table>
			</td>
		</tr>
	</tbody>
</table>

You can use this HTML code to regenerate the issue:
```
<table border="1" cellpadding="0" cellspacing="0">
	<tbody>
		<tr>
			<td style="width: 295px">
			<table border="1" cellpadding="0" cellspacing="0" style="width: 845px">
				<colgroup>
					<col />
					<col />
					<col />
					<col />
					<col />
				</colgroup>
				<tbody>
					<tr height="20">
						<td height="20" style="width: 181px; height: 20px">Name</td>
						<td style="width: 56px">Priority</td>
						<td style="width: 225px">Designation</td>
						<td style="width: 220px">Purpose</td>
						<td style="width: 163px">Comment</td>
					</tr>
					<tr height="20">
						<td height="20" style="height: 20px">123</td>
						<td>High</td>
						<td>123123</td>
						<td>123</td>
						<td> </td>
					</tr>
				</tbody>
			</table>
			</td>
		</tr>
	</tbody>
</table>
```

At redmine's production.log file, I see:
```
Started GET "/issues/71.pdf" for 127.0.0.1 at 2015-02-01 17:31:11 +0200
Processing by IssuesController#show as PDF
  Parameters: {"id"=>"71"}
  Current user: adavid (id=96)
Completed 500 Internal Server Error in 141ms

NoMethodError (undefined method `<' for nil:NilClass):
  lib/plugins/rfpdf/lib/tcpdf.rb:3793:in `closedHTMLTagCalc'
  lib/plugins/rfpdf/lib/tcpdf.rb:3482:in `block in writeHTML'
  lib/plugins/rfpdf/lib/tcpdf.rb:3478:in `each'
  lib/plugins/rfpdf/lib/tcpdf.rb:3478:in `writeHTML'
  lib/plugins/rfpdf/lib/tcpdf.rb:3612:in `writeHTMLCell'
  lib/redmine/export/pdf.rb:141:in `RDMwriteHTMLCell'
  lib/redmine/export/pdf.rb:693:in `block in issue_to_pdf'
  lib/redmine/export/pdf.rb:680:in `each'
  lib/redmine/export/pdf.rb:680:in `issue_to_pdf'
  app/controllers/issues_controller.rb:124:in `block (2 levels) in show'
  app/controllers/issues_controller.rb:116:in `show'

```

This is very important for me since that this server is used in production by many users.
Will appreciate any help!

Thanks in advance,
Adi.

**Comment by a-ono** [comment]
I can't reproduce it with Redmine 2.6.

**Comment by adi-david** [comment]
Thank you for the quick answer.
It happens in Redmine 2.3.3 and CKEditor 1.0.18.
When i checked it in Redmine 2.6 it indeed worked.
Is there any chance that this can be fixed without upgrading Redmine?

**Comment by a-ono** [comment]
I've confirmed it, but I wouldn't support old versions.
