### ISSUE TITLE
Redmine 2.5.1 & Rails 3.2.17 & undefined method `perform_caching' for #<Hash:0x000000069a1fb8>

### ISSUE THREAD

**Issue by Nicholasny** [a-ono/redmine_ckeditor#150]
Environment:
  Redmine version                2.5.1.stable
  Ruby version                   2.0.0-p384 (2014-01-12) [x86_64-linux-gnu]
  Rails version                  3.2.17
  Environment                    production
  Database adapter               MySQL
SCM:
  Git                            1.9.1
  Filesystem                     
Redmine plugins:
  redmine_ckeditor               0.0.6-ebrahim
  redmine_code_review            0.6.3

Error:
Started GET "/redmine/settings/plugin/redmine_ckeditor" for 172.30.21.200 at 201
5-02-24 14:33:44 +0800
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"redmine_ckeditor"}
  Current user: admin (id=1)
  Rendered plugins/redmine_ckeditor/app/views/settings/_ckeditor.html.erb (5.7ms)
  Rendered settings/plugin.html.erb within layouts/admin (6.9ms)
Completed 500 Internal Server Error in 11.5ms

ActionView::Template::Error (undefined method `perform_caching' for #<Hash:0x000000069a1fb8>):
    1: <p>
    2:   <%= content_tag :label, l(:ckeditor_toolbar_setting) %>
    3: </p>
    4: <%= RedmineCkeditor.toolbar_selector %>
  app/views/settings/plugin.html.erb:6:in `block in _app_views_settings_plugin_html_erb___3296255275073687014_37077740'
  app/views/settings/plugin.html.erb:4:in `_app_views_settings_plugin_html_erb___3296255275073687014_37077740'

Thank you for any help...

**Comment by a-ono** [comment]
Please see [Requirements](https://github.com/a-ono/redmine_ckeditor#requirements).
