### ISSUE TITLE
Error Redmine 3.0 "ArgumentError: The scope body needs to be callable"

### ISSUE THREAD

**Issue by iamhawk** [a-ono/redmine_ckeditor#151]
rake aborted!
ArgumentError: The scope body needs to be callable.
/var/www/dev.ctech.su/redmine/plugins/redmine_ckeditor/lib/redmine_ckeditor/rich_file_patch.rb:1:in `<top (required)>'
/var/www/dev.ctech.su/redmine/plugins/redmine_ckeditor/lib/redmine_ckeditor.rb:129:in `apply_patch'
/var/www/dev.ctech.su/redmine/plugins/redmine_ckeditor/init.rb:5:in `block in <top (required)>'
/var/www/dev.ctech.su/redmine/config/environment.rb:14:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment

**Comment by a-ono** [comment]
Redmine 3.0 is not supported yet.

**Comment by a-ono** [comment]
Version 1.1.0 has been released.
