### ISSUE TITLE
引用がうまく動きません。

### ISSUE THREAD

**Issue by nakayoshisandayo** [a-ono/redmine_ckeditor#152]
Redmineの引用を押して、ckeditorで編集する場合、ckeditorの引用ボタンを押せない（blockquoteを解除できない）。

lib/redmine_ckeditor/journals_controller_patch.rb
の
@content << "<blockquote>#{ActionView::Base.full_sanitizer.sanitize(text)}</blockquote><p/>"
を
@content << "<blockquote><p>#{ActionView::Base.full_sanitizer.sanitize(text)}</p></blockquote>"
としたらどうでしょうか？

また、引用された内容がサニタイズされてしまっていて残念なことになっているので、
@content << "<blockquote><p>#{text}</p></blockquote>"
のようにサニタイズを外すのはどうでしょうか？
問題でしょうか？

**Comment by a-ono** [comment]
HTML出力時にサニタイズしているので、引用時にサニタイズしなくても特に問題はないですね。
img等も引用されてしまうのでどうかとは思いましたが、そうした方が使い勝手が良さそうだったので外しました。
pタグで囲うと入れ子になることがあるのでそちらはやめます。
改行モードをpではなくてbrにしていると、blockquoteを解除できない状態になることはまだあるのですが。
