### ISSUE TITLE
Problem instaling CKEditor 1.0.20  in Bitnami Redmine 3.0.0

### ISSUE THREAD

**Issue by morzius** [a-ono/redmine_ckeditor#153]
Hello!

I`m facing problems with installing, can you recommend me something?

Here is a log:

d:\Redmine-3.0.0\apps\redmine\htdocs>bundle install --without development test
DL is deprecated, please use Fiddle
You are trying to install in deployment mode after changing
your Gemfile. Run `bundle install` elsewhere and add the
updated Gemfile.lock to version control.

If this is a development machine, remove the Gemfile freeze
by running `bundle install --no-deployment`.

You have added to the Gemfile:
* rich (= 1.4.6)
* kaminari
* htmlentities
* paperclip (~> 3.5.4)
* pandoc-ruby

d:\Redmine-3.0.0\apps\redmine\htdocs>bundle install --no-deployment
DL is deprecated, please use Fiddle
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
Installing rake 10.4.2
Installing i18n 0.7.0
Installing json 1.8.2
Installing minitest 5.5.1
Installing thread_safe 0.3.4
Installing tzinfo 1.2.2
Installing activesupport 4.2.0
Installing builder 3.2.2
Installing erubis 2.7.0
Installing mini_portile 0.6.2
Installing nokogiri 1.6.6.2
Installing rails-deprecated_sanitizer 1.0.3
Installing rails-dom-testing 1.0.5
Installing loofah 2.0.1
Installing rails-html-sanitizer 1.0.1
Installing actionview 4.2.0
Installing rack 1.6.0
Installing rack-test 0.6.3
Installing actionpack 4.2.0
Installing globalid 0.3.0
Installing activejob 4.2.0
Installing mime-types 2.4.3
Installing mail 2.6.3
Installing actionmailer 4.2.0
Installing actionpack-action_caching 1.1.1
Installing actionpack-xml_parser 1.0.1
Installing activemodel 4.2.0
Installing arel 6.0.0
Installing activerecord 4.2.0
Using bundler 1.7.0
Installing climate_control 0.0.3
Installing cocaine 0.5.7
Installing coderay 1.1.0
Installing daemons 1.1.9
Installing eventmachine 1.0.3
Installing hike 1.2.3
Installing htmlentities 4.3.3
Installing thor 0.19.1
Installing railties 4.2.0
Installing jquery-rails 3.1.2
Installing kaminari 0.16.3
Installing multi_json 1.10.1
Installing mysql2 0.3.18
Installing net-ldap 0.3.1
Installing pandoc-ruby 1.0.0
Installing paperclip 3.5.4
Installing protected_attributes 1.0.5
Installing ruby-openid 2.3.0
Installing rack-openid 1.4.2
Installing rack-raw-upload 1.1.1
Installing tilt 1.4.1
Installing sprockets 2.12.3
Installing sprockets-rails 2.2.4
Installing rails 4.2.0
Installing rbpdf 1.18.5
Installing redcarpet 3.1.2
Installing request_store 1.0.5
Installing sass 3.4.13
Installing sass-rails 5.0.1
Installing rich 1.4.6
Installing rmagick 2.13.4
Installing thin 1.6.1
Installing tzinfo-data 1.2015.1
Updating files in vendor/cache
  * climate_control-0.0.3.gem
  * cocaine-0.5.7.gem
  * htmlentities-4.3.3.gem
  * kaminari-0.16.3.gem
  * pandoc-ruby-1.0.0.gem
  * paperclip-3.5.4.gem
  * rack-raw-upload-1.1.1.gem
  * sass-3.4.13.gem
  * sass-rails-5.0.1.gem
  * rich-1.4.6.gem
Your bundle is complete!
Gems in the groups development and test were not installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
Post-install message from nokogiri:
Nokogiri is built with the packaged libraries: libxml2-2.9.2, libxslt-1.1.28, zl
ib-1.2.8, libiconv-1.14.
Post-install message from mysql2:

================================================================================
======================

  You've installed the binary version of mysql2.
  It was built using MySQL Connector/C version 6.1.5.
  It's recommended to use the exact same version to avoid potential issues.

  At the time of building this gem, the necessary DLL files were retrieved from:

  http://cdn.mysql.com/Downloads/Connector-C/mysql-connector-c-6.1.5-win32.zip

  This gem *includes* vendor/libmysql.dll with redistribution notice in vendor/R
EADME.

================================================================================
======================

Post-install message from rmagick:
Please report any bugs. See https://github.com/gemhome/rmagick/compare/RMagick_2
-13-2...master and https://github.com/rmagick/rmagick/issues/18

d:\Redmine-3.0.0\apps\redmine\htdocs>rake redmine:plugins:migrate RAILS_ENV=prod
uction
DL is deprecated, please use Fiddle
rake aborted!
ArgumentError: The scope body needs to be callable.
d:/Redmine-3.0.0/apps/redmine/htdocs/plugins/redmine_ckeditor/lib/redmine_ckedit
or/rich_file_patch.rb:1:in `<top (required)>'
d:/Redmine-3.0.0/apps/redmine/htdocs/plugins/redmine_ckeditor/lib/redmine_ckedit
or.rb:129:in `apply_patch'
d:/Redmine-3.0.0/apps/redmine/htdocs/plugins/redmine_ckeditor/init.rb:5:in `bloc
k in <top (required)>'
d:/Redmine-3.0.0/apps/redmine/htdocs/config/environment.rb:14:in `<top (required
)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

**Comment by a-ono** [comment]
Redmine 3.0 is not supported yet.

**Comment by morzius** [comment]
Understand, thank you!

**Comment by a-ono** [comment]
Version 1.1.0 has been released.
