### ISSUE TITLE
Problem with installing on Bitnami Redmine 3.0.1

### ISSUE THREAD

**Issue by morzius** [a-ono/redmine_ckeditor#155]
Hello!

Try to install editor on Bitmani Redmine, error on the last step, here is all log:

Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

d:\Redmine-3.0.1>cd apps\redmine\htdocs

d:\Redmine-3.0.1\apps\redmine\htdocs>bundle install --without development test
DL is deprecated, please use Fiddle
You are trying to install in deployment mode after changing
your Gemfile. Run `bundle install` elsewhere and add the
updated Gemfile.lock to version control.

If this is a development machine, remove the Gemfile freeze
by running `bundle install --no-deployment`.

You have added to the Gemfile:
* rich (= 1.4.6)
* kaminari
* htmlentities
* paperclip (~> 3.5.4)
* pandoc-ruby

d:\Redmine-3.0.1\apps\redmine\htdocs>bundle install --no-deployment
DL is deprecated, please use Fiddle
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
Installing rake 10.4.2
Installing i18n 0.7.0
Installing json 1.8.2
Installing minitest 5.5.1
Installing thread_safe 0.3.4
Installing tzinfo 1.2.2
Installing activesupport 4.2.0
Installing builder 3.2.2
Installing erubis 2.7.0
Installing mini_portile 0.6.2
Installing nokogiri 1.6.6.2
Installing rails-deprecated_sanitizer 1.0.3
Installing rails-dom-testing 1.0.5
Installing loofah 2.0.1
Installing rails-html-sanitizer 1.0.1
Installing actionview 4.2.0
Installing rack 1.6.0
Installing rack-test 0.6.3
Installing actionpack 4.2.0
Installing globalid 0.3.0
Installing activejob 4.2.0
Installing mime-types 2.4.3
Installing mail 2.6.3
Installing actionmailer 4.2.0
Installing actionpack-action_caching 1.1.1
Installing actionpack-xml_parser 1.0.1
Installing activemodel 4.2.0
Installing arel 6.0.0
Installing activerecord 4.2.0
Using bundler 1.7.0
Installing climate_control 0.0.3
Installing cocaine 0.5.7
Installing coderay 1.1.0
Installing daemons 1.1.9
Installing eventmachine 1.0.3
Installing hike 1.2.3
Installing htmlentities 4.3.3
Installing thor 0.19.1
Installing railties 4.2.0
Installing jquery-rails 3.1.2
Installing kaminari 0.16.3
Installing multi_json 1.10.1
Installing mysql2 0.3.18
Installing net-ldap 0.3.1
Installing pandoc-ruby 1.0.0
Installing paperclip 3.5.4
Installing protected_attributes 1.0.5
Installing ruby-openid 2.3.0
Installing rack-openid 1.4.2
Installing rack-raw-upload 1.1.1
Installing tilt 1.4.1
Installing sprockets 2.12.3
Installing sprockets-rails 2.2.4
Installing rails 4.2.0
Installing rbpdf 1.18.5
Installing redcarpet 3.1.2
Installing request_store 1.0.5
Installing sass 3.4.13
Installing sass-rails 5.0.1
Installing rich 1.4.6
Installing rmagick 2.13.4
Installing thin 1.6.1
Installing tzinfo-data 1.2015.1
Updating files in vendor/cache
  * climate_control-0.0.3.gem
  * cocaine-0.5.7.gem
  * htmlentities-4.3.3.gem
  * kaminari-0.16.3.gem
  * pandoc-ruby-1.0.0.gem
  * paperclip-3.5.4.gem
  * rack-raw-upload-1.1.1.gem
  * sass-3.4.13.gem
  * sass-rails-5.0.1.gem
  * rich-1.4.6.gem
Your bundle is complete!
Gems in the groups development and test were not installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
Post-install message from nokogiri:
Nokogiri is built with the packaged libraries: libxml2-2.9.2, libxslt-1.1.28, zl
ib-1.2.8, libiconv-1.14.
Post-install message from mysql2:

================================================================================
======================

  You've installed the binary version of mysql2.
  It was built using MySQL Connector/C version 6.1.5.
  It's recommended to use the exact same version to avoid potential issues.

  At the time of building this gem, the necessary DLL files were retrieved from:

  http://cdn.mysql.com/Downloads/Connector-C/mysql-connector-c-6.1.5-win32.zip

  This gem *includes* vendor/libmysql.dll with redistribution notice in vendor/R
EADME.

================================================================================
======================

Post-install message from rmagick:
Please report any bugs. See https://github.com/gemhome/rmagick/compare/RMagick_2
-13-2...master and https://github.com/rmagick/rmagick/issues/18

d:\Redmine-3.0.1\apps\redmine\htdocs>rake redmine:plugins:migrate RAILS_ENV=prod
uction
DL is deprecated, please use Fiddle
rake aborted!
ArgumentError: The scope body needs to be callable.
d:/Redmine-3.0.1/apps/redmine/htdocs/plugins/redmine_ckeditor/lib/redmine_ckedit
or/rich_file_patch.rb:1:in `<top (required)>'
d:/Redmine-3.0.1/apps/redmine/htdocs/plugins/redmine_ckeditor/lib/redmine_ckedit
or.rb:129:in `apply_patch'
d:/Redmine-3.0.1/apps/redmine/htdocs/plugins/redmine_ckeditor/init.rb:5:in `bloc
k in <top (required)>'
d:/Redmine-3.0.1/apps/redmine/htdocs/config/environment.rb:14:in `<top (required
)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

d:\Redmine-3.0.1\apps\redmine\htdocs>

**Comment by a-ono** [comment]
What version are you using?
redmine_ckeditor 1.1.0 does not contain rich_file_patch.rb anymore.

**Comment by morzius** [comment]
Sorry, my fault, used old version, try new one:

First, installed git, because without it it don`t want to setup. Here is installation log:

Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

d:\Redmine-3.0.1>cd apps\redmine\htdocs

d:\Redmine-3.0.1\apps\redmine\htdocs>bundle install --without development test
DL is deprecated, please use Fiddle
You are trying to install in deployment mode after changing
your Gemfile. Run `bundle install` elsewhere and add the
updated Gemfile.lock to version control.

If this is a development machine, remove the Gemfile freeze
by running `bundle install --no-deployment`.

You have added to the Gemfile:
* source: https://github.com/a-ono/rich.git (at master)
* rich
* kaminari
* htmlentities
* paperclip (~> 4.2.1)
* pandoc-ruby

You have changed in the Gemfile:
* rich from `https://github.com/a-ono/rich.git (at master)` to `no specified
source`

d:\Redmine-3.0.1\apps\redmine\htdocs>bundle install --no-deployment
DL is deprecated, please use Fiddle
Fetching https://github.com/a-ono/rich.git
Checking out files: 100% (773/773), done.
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Installing rake 10.4.2
Installing i18n 0.7.0
Installing json 1.8.2
Installing minitest 5.5.1
Installing thread_safe 0.3.4
Installing tzinfo 1.2.2
Installing activesupport 4.2.0
Installing builder 3.2.2
Installing erubis 2.7.0
Installing mini_portile 0.6.2
Installing nokogiri 1.6.6.2
Installing rails-deprecated_sanitizer 1.0.3
Installing rails-dom-testing 1.0.5
Installing loofah 2.0.1
Installing rails-html-sanitizer 1.0.1
Installing actionview 4.2.0
Installing rack 1.6.0
Installing rack-test 0.6.3
Installing actionpack 4.2.0
Installing globalid 0.3.0
Installing activejob 4.2.0
Installing mime-types 2.4.3
Installing mail 2.6.3
Installing actionmailer 4.2.0
Installing actionpack-action_caching 1.1.1
Installing actionpack-xml_parser 1.0.1
Installing activemodel 4.2.0
Installing arel 6.0.0
Installing activerecord 4.2.0
Using bundler 1.7.0
Installing climate_control 0.0.3
Installing cocaine 0.5.7
Installing coderay 1.1.0
Installing daemons 1.1.9
Installing eventmachine 1.0.3
Installing hike 1.2.3
Installing htmlentities 4.3.3
Installing thor 0.19.1
Installing railties 4.2.0
Installing jquery-rails 3.1.2
Installing kaminari 0.16.3
Installing multi_json 1.10.1
Installing mysql2 0.3.18
Installing net-ldap 0.3.1
Installing pandoc-ruby 1.0.0
Installing paperclip 4.2.1
Installing protected_attributes 1.0.5
Installing ruby-openid 2.3.0
Installing rack-openid 1.4.2
Installing rack-raw-upload 1.1.1
Installing tilt 1.4.1
Installing sprockets 2.12.3
Installing sprockets-rails 2.2.4
Installing rails 4.2.0
Installing rbpdf 1.18.5
Installing redcarpet 3.1.2
Installing request_store 1.0.5
Installing sass 3.4.13
Installing sass-rails 5.0.1
Using rich 1.4.8 from https://github.com/a-ono/rich.git (at master)
Installing rmagick 2.13.4
Installing thin 1.6.1
Installing tzinfo-data 1.2015.1
Updating files in vendor/cache
  * climate_control-0.0.3.gem
  * cocaine-0.5.7.gem
  * htmlentities-4.3.3.gem
  * kaminari-0.16.3.gem
  * pandoc-ruby-1.0.0.gem
  * paperclip-4.2.1.gem
  * rack-raw-upload-1.1.1.gem
  * sass-3.4.13.gem
  * sass-rails-5.0.1.gem
Your bundle is complete!
Gems in the groups development and test were not installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
Post-install message from nokogiri:
Nokogiri is built with the packaged libraries: libxml2-2.9.2, libxslt-1.1.28, zl
ib-1.2.8, libiconv-1.14.
Post-install message from mysql2:

================================================================================
======================

  You've installed the binary version of mysql2.
  It was built using MySQL Connector/C version 6.1.5.
  It's recommended to use the exact same version to avoid potential issues.

  At the time of building this gem, the necessary DLL files were retrieved from:

  http://cdn.mysql.com/Downloads/Connector-C/mysql-connector-c-6.1.5-win32.zip

  This gem *includes* vendor/libmysql.dll with redistribution notice in vendor/R
EADME.

================================================================================
======================

Post-install message from rmagick:
Please report any bugs. See https://github.com/gemhome/rmagick/compare/RMagick_2
-13-2...master and https://github.com/rmagick/rmagick/issues/18

d:\Redmine-3.0.1\apps\redmine\htdocs>rake redmine:plugins:migrate RAILS_ENV=prod
uction
DL is deprecated, please use Fiddle
Migrating redmine_ckeditor (Redmine CKEditor plugin)...
== 20130418001207 CreateRichRichImages: migrating =============================
-- create_table(:rich_rich_images)
   -> 0.0090s
== 20130418001207 CreateRichRichImages: migrated (0.0100s) ====================

== 20130418001208 AddUriCacheToRichImage: migrating ===========================
-- add_column(:rich_rich_images, :uri_cache, :text)
   -> 0.0080s
== 20130418001208 AddUriCacheToRichImage: migrated (0.0100s) ==================

== 20130418001209 RefactorImageToFile: migrating ==============================
-- rename_table(:rich_rich_images, :rich_rich_files)
   -> 0.0020s
-- rename_column(:rich_rich_files, :image_file_name, :rich_file_file_name)
   -> 0.0260s
-- rename_column(:rich_rich_files, :image_content_type, :rich_file_content_type)

   -> 0.0210s
-- rename_column(:rich_rich_files, :image_file_size, :rich_file_file_size)
   -> 0.0220s
-- rename_column(:rich_rich_files, :image_updated_at, :rich_file_updated_at)
   -> 0.0220s
-- add_column(:rich_rich_files, :simplified_type, :string, {:default=>"file"})
   -> 0.0080s
== 20130418001209 RefactorImageToFile: migrated (0.1130s) =====================

But i can`t see CKEditor in options https://yadi.sk/i/ZP9oM_yWfSzBd

**Comment by morzius** [comment]
After restarting all services CKEditor appeared and working. Thank you!
