### ISSUE TITLE
Image upload error rich_file has an extension that does not match its contents

### ISSUE THREAD

**Issue by alexander-st** [a-ono/redmine_ckeditor#159]
Dear all,

I just installed the new version of Redmine 3.0.1 and I only added the fresh downloaded ckeditor plugin. The installation runs without any problems and the activation also. But I cannot upload any images with the function "browse and upload images". I can choose an image in the pop-up from my drive but the I receive the following error:

![image error](https://cloud.githubusercontent.com/assets/10597540/6938458/329f3974-d86c-11e4-917f-6116462601e9.jpg)

Please advice! Thank you for your time!

**Comment by BRUTEF0RCE** [comment]
I do experiment the same problem on my side with Redmine 3.0.1 as well.  If you require me to give you some more info on my setup to help in this matter, please do ask me!

Regards.

**Comment by alexander-st** [comment]
Dear BRUTEF0RCE,

please walk me through the solution!

Thank you.

**Comment by BRUTEF0RCE** [comment]
Actually, I guess I was not clear in my comment, I have the same problem as you do... My help offering was aimed toward M. Ono, if he needed info on the specific of my redmine setup.

Regards

**Comment by a-ono** [comment]
I confirmed and fixed this problem.
Please update the rich gem and restart Redmine.
```
bundle update rich
```

**Comment by BRUTEF0RCE** [comment]
Thank you very much M. a-ono!  I confirm the fix on my side as well! Thank you for this very useful plugin! :)
