### ISSUE TITLE
Csv export fails

### ISSUE THREAD

**Issue by Rawukal** [a-ono/redmine_ckeditor#163]
Hi,
my environment:
Redmine version                3.0.3.stable.14294
Ruby version                   2.2.1-p85 (2015-02-26) [x86_64-linux]
Rails version                  4.2.1
Environment                    production
Database adapter               Mysql2

When I install the ckeditor plugin the csv export gives me an error:

I, [2015-06-02T16:22:03.481959 #13107]  INFO -- : Processing by IssuesController#index as CSV
I, [2015-06-02T16:22:03.482135 #13107]  INFO -- :   Parameters: {"utf8"=>"â", "columns"=>"all", "description"=>"1", "project_id"=>"etasoftware"}
I, [2015-06-02T16:22:03.489260 #13107]  INFO -- :   Current user: mauer(id=49)
I, [2015-06-02T16:22:03.739341 #13107]  INFO -- : Completed 500 Internal Server Error in 257ms (ActiveRecord: 9.5ms)
F, [2015-06-02T16:22:03.742677 #13107] FATAL -- :
NameError (uninitialized constant QueriesHelper::HTML):
  app/helpers/queries_helper.rb:141:in `csv_content'
  app/helpers/queries_helper.rb:178:in `block (3 levels) in query_to_csv'
  app/helpers/queries_helper.rb:178:in `collect'
  app/helpers/queries_helper.rb:178:in `block (2 levels) in query_to_csv'
  app/helpers/queries_helper.rb:177:in `each'
  app/helpers/queries_helper.rb:177:in `block in query_to_csv'
  app/helpers/queries_helper.rb:173:in `query_to_csv'
  app/controllers/issues_controller.rb:82:in `block (2 levels) in index'
  app/controllers/issues_controller.rb:76:in `index'

Regards Markus

**Comment by ericLemanissier** [comment]
I'm having the same problem using the Dockerized redmine app by sameersbn. Is there any solution available ?

**Comment by ericLemanissier** [comment]
it looks like redmine also had the issue : http://www.redmine.org/issues/19537

**Comment by a-ono** [comment]
Fixed in version 1.1.1
