### ISSUE TITLE
MathJax plugin not installable

### ISSUE THREAD

**Issue by aguarino77** [a-ono/redmine_ckeditor#168]
I tried to install the mathjax plugin for ckeditor. 
* I copied the mathjax folder + its dependencies (widget, lineutils) into redmine_ckeditor\assets\ckeditor-contrib\plugins
* plugins/redmine_ckeditor/config/ckeditor.yml was modified as follows:

allowedContent: true
bodyClass: "wiki"
basicEntities: false
entities: false
removePlugins: "div,flash,forms,iframe"
forcePasteAsPlainText: false
extraPlugins: "widget,lineutils,mathjax"
mathJaxClass: "my-math"
mathJaxLib: "//cdn.mathjax.org/mathjax/2.2-latest/MathJax.js?config=TeX-AMS_HTML"

still it does not work. the "math" button can be added to the toolbar, but latex is not rendered on OK.
Production.log shows:

Processing by SettingsController#plugin as */*
  Parameters: {"id"=>"undefined"}
  Current user: guarino_a (id=3)
  Rendered common/error.html.erb within layouts/base (0.0ms)
Completed 404 Not Found in 62ms (Views: 46.9ms | ActiveRecord: 0.0ms)

**Comment by a-ono** [comment]
Please copy file to REDMINE_ROOT/config/ckeditor.yml

**Comment by bviktor** [comment]
I did all these, now mathjax renders correctly in "edit" mode, but the final, rendered page only displays the raw formulae. If I add manually the 

~~~
<script type="text/javascript" async
  src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML">
</script>
~~~

code to head, it renders correctly. How can I fix this the proper way?

**Comment by bdonnahue** [comment]
@bviktor I am having the same problem as you. The plugin works in edit mode but the rendered page does not work. Have you figured out a work around?

@a-ono I have tried your suggestion without success:
I move the ckeditor.yml.example to ckeditor.yml
I then add or modify the lines @aguarino77  mentioned
I then run a bundle install, rake, restart httpd... but this breaks edit mode and does not render

I have a working docker container to spin up clean environments. Willing to share if it will help. Would love to get this plugin working.
