### ISSUE TITLE
Existing Text Issue

### ISSUE THREAD

**Issue by jsh562** [a-ono/redmine_ckeditor#169]
Great plugin. However, it changes literally all text boxes within Redmine from RedCloth to CKEditor.
All existing text and formatted text (including calls to pictures, links, etc.) becomes essentially invalid and broken with implementation of this. In my particular case with over 1000 projects with associated issues, fixing this is a very huge burden.

I would really like a way to choose which groups of text boxes are changed.
e.g. Convert "Issues", "News", "Wiki" only

It probably would take changes on the redmine side as well.... i am guessing.

Or, another solution would be to have all existing text boxes evaluate the text with Redcloth unless saved with CKEdtior, but this would be an even more complicated solution.

**Comment by a-ono** [comment]
Please see below:
https://github.com/a-ono/redmine_ckeditor#migration-notes

[redmine_per_project_formatting](https://github.com/a-ono/redmine_per_project_formatting) plugin may help you.
