### ISSUE TITLE
CKEditor and redmine 3.1.x

### ISSUE THREAD

**Issue by KueWW** [a-ono/redmine_ckeditor#172]
Hello everybody,

I tried to install the plugin 1.1.2 using bitnami redmine 3.1.0.
It is written that the plugin works with redmine 3.0.x. Is that right?
The installation did not work.
I've got the following messages:
![2015-08-20 10_53_01-bitnami-redmine-310-ckeditor-112](https://cloud.githubusercontent.com/assets/7642828/9379969/47f2329c-472d-11e5-92de-ad98815afaba.png)

It looks like problem with ruby.

Here's the output from bundle:
![2015-08-20 11_16_44-c__temp_bundle txt - notepad](https://cloud.githubusercontent.com/assets/7642828/9379929/056c4d86-472d-11e5-9d9d-1d48a1b9347d.png)

I'm using an opensuse 13.1 with that ruby version:
![2015-08-20 10_53_01-bitnami-redmine-310-ruby-version](https://cloud.githubusercontent.com/assets/7642828/9379977/54a699b0-472d-11e5-82ad-63789300c8e6.png)

Can you give any help?

Thanks in advance....

**Comment by a-ono** [comment]
It's not a this plugin's problem.
Please refer to the information below.
https://www.redmine.org/projects/redmine/search?utf8=%E2%9C%93&issues=1&q=ActionView%3A%3AHelpers%3A%3AActiveModelHelper
