### ISSUE TITLE
Image export pdf

### ISSUE THREAD

**Issue by r0perice** [a-ono/redmine_ckeditor#173]
Hello,

I'm working on a redmine platform and I want to upload image in my wiki and export it in pdf. The upload work fine but when I export the wiki in pdf their is no image. If I insert an image hosted on internet in my wiki, the pdf export works (thanks to https://github.com/ogerman/redmine_pdf_export) but if I use Rich module from CKeditor to upload the image the export pdf doesn't work.

###### My wiki
--
![pdf_issue_1](https://cloud.githubusercontent.com/assets/7713432/9471100/7224814a-4b57-11e5-91d3-0a46d187bf2c.png)

###### My pdf
--
![pdf_issue_2](https://cloud.githubusercontent.com/assets/7713432/9471099/72245a30-4b57-11e5-80f8-194a85430f81.png)

#### Error
>Processing by WikiController#show as PDF
  Parameters: {"project_id"=>"default_project", "id"=>"Welcome_to_default_project"}
  Current user: admin (id=1)
bad component(expected host component): localhost:3000
**pdf: Image: error: RBPDF error: Image filename is empty.**
  Rendered wiki/show.pdf.erb (395.4ms)
Completed 200 OK in 414ms (Views: 397.0ms | ActiveRecord: 3.0ms)

#### My configuration
OS : centOS 6.5
Redmine : 3.1.0-0 (https://bitnami.com/stack/redmine/installer)
CKeditor : 1.1.2 (https://github.com/a-ono/redmine_ckeditor)

Any help will be greatly appreciated !

Robin

**Comment by a-ono** [comment]
It's supported in version 1.1.3.
