### ISSUE TITLE
CKEDITOR broken on 'New Issue' page

### ISSUE THREAD

**Issue by chrisp1001** [a-ono/redmine_ckeditor#175]
I am using redmine 3.1.0 and have installed the lastest redmine_ckeditor plugin. CKEDITOR works on all pages except on the new issue page. It looks broken like this:

![auswahl_019](https://cloud.githubusercontent.com/assets/14017864/9550012/3041baaa-4da9-11e5-9094-6393aab0871d.png)

Can anybody help?

**Comment by rompic** [comment]
sounds like #135 where http://www.redmine.org/plugins/redmine-mentions was causing the problems.

**Comment by chrisp1001** [comment]
Thank you rompic. Uninstalling redmine_mentions fixed the problem!
