### ISSUE TITLE
< not converted into HTML entity

### ISSUE THREAD

**Issue by chrisp1001** [a-ono/redmine_ckeditor#176]
I am using redmine 3.1.0 and the lastest redmine_ckeditor plugin and wanted to use a < char in the text of a wiki page. When I save the page it is not visible on the Wiki Page as it does not seem to be converted into an HTML entity.
I have already played around with the config options of CKEDITOR regarding entities however had no luck.

**Comment by rompic** [comment]
Sounds like #158 to me

**Comment by chrisp1001** [comment]
Yes, seems to be the same problem. I cannot understand why CKEDITOR doesn't convert special chars into html entities directly when typing them into the WYSIWYG box. When I switch to the source view all chars are still plain and not converted directly.
It seems that the conversions happens in the backend after sending the form to redmine_ckeditor.

**Comment by rompic** [comment]
yes this is also noted in the other issue. would love to see this fixed.

**Comment by a-ono** [comment]
Fixed in master branch.
