### ISSUE TITLE
config/ckeditor.yml is not functioning normally.

### ISSUE THREAD

**Issue by bluenyx** [a-ono/redmine_ckeditor#177]
I have been using redmine 3.1.0.
Paste table of excel in ckeditor has not been well. So add the following option "ckeditor.yml"

config.pasteFromWordRemoveFontStyles: false
config.pasteFromWordRemoveStyles: false

However, this does not apply.
Where should I modify?

Thank you, Great plugin.

**Comment by a-ono** [comment]
REDMINE_ROOT/config/ckeditor.yml
```
pasteFromWordRemoveFontStyles: false
pasteFromWordRemoveStyles: false
```
