### ISSUE TITLE
Workaround for <

### ISSUE THREAD

**Issue by alterspirt** [a-ono/redmine_ckeditor#178]
Hello!

I`m facing same problem as others about wrong HTML convertation, in editor i put like this

https://yadi.sk/i/XWYvk1MmjNoRG

But after saving i get it like this:

https://yadi.sk/i/iV6s74hPjNoUy

If someone can have any workaround or fix for this, can you plz share?

Thank you.

**Comment by a-ono** [comment]
Fixed in master branch.
