### ISSUE TITLE
ckeditor + plantuml plugin

### ISSUE THREAD

**Issue by hjansen** [a-ono/redmine_ckeditor#179]
Hi,

i really like the ckeditor plugin but i like the plantuml plugin as well. Is there a way to make them work together ? Currently when i enable ckeditor the planuml part of the page doesn't get converted anymore. Is there a special syntax on how to use them together or does it simply not work because there needs some coding to be done ?

Thx and greetings

Holger

**Comment by a-ono** [comment]
Unfortunately there's a problem with multi-line macro. #114

**Comment by a-ono** [comment]
Fixed in master branch.
