### ISSUE TITLE
use of &thinsp; in HTML code causes 500 error on save

### ISSUE THREAD

**Issue by leobg** [a-ono/redmine_ckeditor#181]
I noticed using "&thinsp;" (this is "& t h i n s p ;" - remove the spaces) which is the code for thin space HTML char) causes 500 error when attempting to save the content. I understand it could be related to CKeditor itself, not the plugin. Found this issue on CKeditor dev: https://dev.ckeditor.com/ticket/983 which seems related. 
The use of this character isn't really an issue, but it becomes a problem when copy/paste from another source and trying to save the page in Redmine.

**Comment by leobg** [comment]
after converting wiki_contents table to utf8 500 error is gone. CKeditor's issue of converting HTML entities when switching back and forth between HTML and WYSIWYG mode remains though. But I guess this is CKeditor issue and we could close this one I guess.

**Comment by a-ono** [comment]
Closing because I can't reproduce it.
