### ISSUE TITLE
Bundle install is failing on rich

### ISSUE THREAD

**Issue by davidmckay** [a-ono/redmine_ckeditor#182]
Hi, I'm upgrading my redmine to use your latest plugin, and have run into an issue on the bundle install step as follows:

Updating https://github.com/a-ono/rich.git
Fetching gem metadata from https://rubygems.org/............
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies.....................................................................
Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    rich (>= 0) ruby depends on
      rails (>= 3.2.0) ruby

    acts-as-taggable-on (~> 2.3.1) ruby depends on
      rails (~> 3.0) ruby

    rails (= 4.2.3) ruby

Redmine 3.0.5
ruby 2.2.3p173
ubuntu 14.04

Clearly rails is > 3.2.0 , so I'm not sure how to solve the issue.

**Comment by a-ono** [comment]
Both Redmine and ckeditor plugin don't depend acts-as-taggable-on.
It seems another plugin's issue.
