### ISSUE TITLE
bundle exec rake db:migrate

### ISSUE THREAD

**Issue by ankusharma788** [a-ono/redmine_ckeditor#184]
Hi,

I am trying to configure redmine with backlog service but getting below mentioned error message while running "bundle exec rake db:migrate".

Please configure your config/database.yml first
rake aborted!
ArgumentError: The scope body needs to be callable.
/var/lib/gems/1.9.1/gems/activerecord-4.2.4/lib/active_record/scoping/named.rb:143:in `scope'
/opt/redmine/plugins/redmine_backlogs/app/models/rb_release.rb:174:in `<class:RbRelease>'
/opt/redmine/plugins/redmine_backlogs/app/models/rb_release.rb:156:in `<top (required)>'
/var/lib/gems/1.9.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/1.9.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
/var/lib/gems/1.9.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/1.9.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/1.9.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:360:in `require_or_load'
/var/lib/gems/1.9.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:494:in `load_missing_constant'
/var/lib/gems/1.9.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:184:in `const_missing'
/var/lib/gems/1.9.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:526:in `load_missing_constant'
/var/lib/gems/1.9.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:184:in `const_missing'
/var/lib/gems/1.9.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:526:in `load_missing_constant'
/var/lib/gems/1.9.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:184:in `const_missing'
/opt/redmine/plugins/redmine_backlogs/lib/backlogs_issue_query_patch.rb:31:in `block in included'
/opt/redmine/plugins/redmine_backlogs/lib/backlogs_issue_query_patch.rb:25:in `class_eval'
/opt/redmine/plugins/redmine_backlogs/lib/backlogs_issue_query_patch.rb:25:in `included'
/opt/redmine/plugins/redmine_backlogs/lib/backlogs_issue_query_patch.rb:145:in `include'
/opt/redmine/plugins/redmine_backlogs/lib/backlogs_issue_query_patch.rb:145:in `<top (required)>'
/var/lib/gems/1.9.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/1.9.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
/var/lib/gems/1.9.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/1.9.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/1.9.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:360:in `require_or_load'
/var/lib/gems/1.9.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:317:in `depend_on'
/var/lib/gems/1.9.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:233:in `require_dependency'
/opt/redmine/plugins/redmine_backlogs/init.rb:27:in `block in <top (required)>'
/var/lib/gems/1.9.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:446:in `instance_exec'
/var/lib/gems/1.9.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:446:in `block in make_lambda'
/var/lib/gems/1.9.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:192:in `call'
/var/lib/gems/1.9.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:192:in `block in simple'
/var/lib/gems/1.9.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:504:in `call'
/var/lib/gems/1.9.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:504:in `block in call'
/var/lib/gems/1.9.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:504:in `each'
/var/lib/gems/1.9.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:504:in `call'
/var/lib/gems/1.9.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/var/lib/gems/1.9.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_prepare_callbacks'
/var/lib/gems/1.9.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:81:in `run_callbacks'
/var/lib/gems/1.9.1/gems/actionpack-4.2.4/lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
/var/lib/gems/1.9.1/gems/actionpack-4.2.4/lib/action_dispatch/middleware/reloader.rb:55:in `prepare!'
/var/lib/gems/1.9.1/gems/railties-4.2.4/lib/rails/application/finisher.rb:50:in `block in <module:Finisher>'
/var/lib/gems/1.9.1/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `instance_exec'
/var/lib/gems/1.9.1/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `run'
/var/lib/gems/1.9.1/gems/railties-4.2.4/lib/rails/initializable.rb:55:in `block in run_initializers'
/var/lib/gems/1.9.1/gems/railties-4.2.4/lib/rails/initializable.rb:54:in `run_initializers'
/var/lib/gems/1.9.1/gems/railties-4.2.4/lib/rails/application.rb:352:in `initialize!'
/opt/redmine/config/environment.rb:14:in `<top (required)>'
/var/lib/gems/1.9.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/1.9.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
/var/lib/gems/1.9.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/1.9.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/1.9.1/gems/railties-4.2.4/lib/rails/application.rb:328:in `require_environment!'
/var/lib/gems/1.9.1/gems/railties-4.2.4/lib/rails/application.rb:457:in `block in run_tasks_blocks'
Tasks: TOP => redmine:backlogs:install => environment
(See full trace by running task with --trace)
imfinity@Redmine-anku:/opt/redmine$ ^C
imfinity@Redmine-anku:/opt/redmine$ bundle exec rake redmine:backlogs:install parameter=value parameter=value ...

Can you please help me out here?

Please refer below link which i follow to setup

https://www.redmine.org/projects/redmine/wiki/RedmineInstall
http://www.redminebacklogs.net/en/installation.html

Regards,
Anku

**Comment by a-ono** [comment]
It's not a this plugin's issue...
