### ISSUE TITLE
CKE Editor in custom fields

### ISSUE THREAD

**Issue by hriekehof** [a-ono/redmine_ckeditor#185]
Hi,

i currently have the problem that the CKEditor is just active for the description field in the issue context. It would be great if the editor would also work for custom fields with _long text_.

Is this already included in the new version ? I currently have 1.0.20

Best regards,
hr

**Comment by a-ono** [comment]
It's not currently available.

**Comment by hriekehof** [comment]
Would it be possible without too much effort to activate textile again in custom fields ? 

Right now if i am using ckeditor in tickets html is also enabled in custom fields. It would be nice if the custom fields would than be rendered in textile again

**Comment by ftab** [comment]
This would be good to have, if possible. I have custom fields in my application for "steps to follow", "expected result", "actual result"

**Comment by hriekehof** [comment]
I close this now to get rid of it in my issue list :) sorry
