### ISSUE TITLE
Configuration inner workings

### ISSUE THREAD

**Issue by CivicRacer** [a-ono/redmine_ckeditor#186]
I'd like to get a quick description on how the configuration files work.  I'm having an issue with HTML generation, and based on behavior I've observed, I can't be sure my configuration changes are really taking effect.  I guess I'll start with the question: what configuration method has priority; the ckeditor.yml or the in-Redmine plugin settings?

If I add in the following line to the ckeditor.yml file, it appears to override the settings in Redmine.
extraPlugins: "scayt"

However, if I try this line, it has no effect (appears not to override the color setting in Redmine):
uiColor: "#AADC6E"

I ask because I am trying to get "allowedContent: true" to have effect, but I can't be sure this is happening.

Also, what does the config.js file do in this environment?  It seems to never change or have any effect despite the documentation on the CKEditor website.

**Comment by a-ono** [comment]
The order of priority is below.
1. plugin settings in Redmine
2. ckeditor.yml

config.js file is not currently available.
