### ISSUE TITLE
Not support redmine 2.6?

### ISSUE THREAD

**Issue by eefylin** [a-ono/redmine_ckeditor#188]
Hello,

I'm using Bitnami Redmine 2.6. I tried to install ckeditor(b667a68), but I got some problem while "rake redmine".

bash-4.1# rake redmine:plugins:migrate RAILS_ENV=production
(in /var/redmine-2.6.0-1/apps/redmine/htdocs)
rake aborted!
Redmine::PluginRequirementError: redmine_ckeditor plugin requires Redmine 3.0.0 or higher but current is 2.6.0.stable

Can anyone help me with it?

**Comment by a-ono** [comment]
Please see README file.
You should install version [1.0.20](https://github.com/a-ono/redmine_ckeditor/releases/tag/1.0.20)

**Comment by eefylin** [comment]
I encounter the same problem as #158 , but this fix didn't put it into version 1.0.20.
So that's the reason I tried master branch.

Can you help me to handle this problem?

**Comment by a-ono** [comment]
It seems OK.
I will no longer support Redmine 2.x.
