### ISSUE TITLE
codehighlight

### ISSUE THREAD

**Issue by rompic** [a-ono/redmine_ckeditor#190]
what is the best way to enable codehighlight?
adding code tags in the source code does not work since 1.1.3

**Comment by a-ono** [comment]
It should work. I have no problem with it.

**Comment by rompic** [comment]
how do you use it? I tried the example in http://www.redmine.org/projects/redmine/wiki/RedmineTextFormattingTextile

**Comment by a-ono** [comment]
What doesn't work?
It seems OK to add `pre` and `code` tags in the source mode as you wrote.

**Comment by rompic** [comment]
the code is not highlighted

**Comment by a-ono** [comment]
I can't reproduce it.
Please add screenshots of HTML source and rendered result.

**Comment by rompic** [comment]
I reloaded my browser and it works now. sorry for any inconvenience.
