### ISSUE TITLE
undefined method `get_image_filename' for class `Redmine::Export::PDF::ITCPDF'

### ISSUE THREAD

**Issue by arturol76** [a-ono/redmine_ckeditor#193]
Hello.
I've followed your instructions to install the plugin.
The "bundle install --without development test" is OK.
But when i execute "rake redmine:plugins:migrate RAILS_ENV=production", I get this error:

rake aborted!
NameError: undefined method `get_image_filename' for class `Redmine::Export::PDF::ITCPDF'
/usr/share/redmine/plugins/redmine_ckeditor/lib/redmine_ckeditor/pdf_patch.rb:8:in `block in included'
/usr/share/redmine/plugins/redmine_ckeditor/lib/redmine_ckeditor/pdf_patch.rb:6:in `class_eval'
/usr/share/redmine/plugins/redmine_ckeditor/lib/redmine_ckeditor/pdf_patch.rb:6:in `included'
/usr/share/redmine/plugins/redmine_ckeditor/lib/redmine_ckeditor/pdf_patch.rb:60:in `include'
/usr/share/redmine/plugins/redmine_ckeditor/lib/redmine_ckeditor/pdf_patch.rb:60:in `<module:RedmineCkeditor>'
/usr/share/redmine/plugins/redmine_ckeditor/lib/redmine_ckeditor/pdf_patch.rb:3:in `<top (required)>'
/usr/share/redmine/plugins/redmine_ckeditor/lib/redmine_ckeditor.rb:135:in `<top (required)>'
/usr/share/redmine/plugins/redmine_ckeditor/init.rb:2:in `<top (required)>'
/usr/share/redmine/lib/redmine/plugin.rb:133:in `block in load'
/usr/share/redmine/lib/redmine/plugin.rb:124:in `each'
/usr/share/redmine/lib/redmine/plugin.rb:124:in `load'
/usr/share/redmine/config/initializers/30-redmine.rb:19:in `<top (required)>'
/usr/share/redmine/config/environment.rb:14:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

ubuntu: Ubuntu 14.04.3 LTS
redmine: 
  Redmine version                2.4.2.stable
  Ruby version                   1.9.3-p484 (2013-11-22) [x86_64-linux]
  Rails version                  3.2.16
  Environment                    production
  Database adapter               MySQL
SCM:
  Git                            1.9.1
  Filesystem                     
Redmine plugins:
  redmine_email_fetcher          0.3.1

Can you help me?
Thanks!

**Comment by a-ono** [comment]
> Redmine version 2.4.2.stable

redmine_ckeditor 1.1.3 requires Redmine 3.0.x or higher.
 Please use version 1.0.20.
