### ISSUE TITLE
support ckeditor image clipboard copy&paste

### ISSUE THREAD

**Issue by mknj** [a-ono/redmine_ckeditor#194]
ckeditor supports image clipboard copy&paste via base64 encoded html img tags.

For bigger images this fails as the underlying database tables have size limitations.

Would it be possible to extract the base64 image when hitting save, and store it as "hash(data).png"  attachment?

**Comment by adrianobr** [comment]
Do you need add the plugins: 'pastebase64' and 'base64image'
In config.js add:
config.extraPlugins = 'pastebase64';
config.extraPlugins = 'base64image';

And init.rb add:
(Loofah::VERSION >= "2.3.0" ? Loofah::HTML5::SafeList : Loofah::HTML5::WhiteList)::ALLOWED_PROTOCOLS.add('data')

Working perfect!

**Comment by mknj** [comment]
Thanks
