### ISSUE TITLE
Cannot show base64 inline image in the journal notes

### ISSUE THREAD

**Issue by huyttq** [a-ono/redmine_ckeditor#196]
Let say there is a base64 inline image in the notes of journal:

`<p><img alt="cannot show image" src="data:image/png;base64,wxxxxxxxx" /></p>`

In edit mode, it shows fine but after the image cannot be showed.
Look at the rendered html, look like the src property of img tag has been removed by the plugin.

My suspect is that **Redmine::WikiFormatting::LinksHelper.to_html** clears it.

Redmine 3.2.0
Redmine CKEditor plugin 1.1.3 with addon https://github.com/nmmf/base64image

Please have a check, thanks

**Comment by huyttq** [comment]
FYI:

I managed to fix the issue by allowing `data` protocols in Rails initializers:

`Loofah::HTML5::WhiteList::ALLOWED_PROTOCOLS.add('data')`

**Comment by blackhase** [comment]
which file must i this insert, 
sry, for my english.

**Comment by ski4404** [comment]
I have no Rails experience so this might not be the correct place to insert this code but I added it to the end of the block of code in `plugins/redmine_ckeditor/init.rb`  right above the last line "end" and it works.

**Comment by blackhase** [comment]
I have reinstall redmine.
Install ckeditor plugin as first. 
Edit plugins/redmine_ckeditor/init.rb 
end of the block Loofah::HTML5::WhiteList::ALLOWED_PROTOCOLS.add('data') 

It's works! thks

**Comment by a-ono** [comment]
Data URI should not be allowed by default because it is not safe and is used with addon.
It is configurable in REDMINE_ROOT/config/ckeditor.yml since version 1.1.4.
```
allowedProtocols:
  - data
```

**Comment by rompic** [comment]
@a-ono couldn't get this to work with creating a config file and adding data. can you please check?

**Comment by LaurentBarbareau** [comment]
Adding ckeditor.yml did not work for me either.

But the init.rb modification did work, adding the line ALLOWED_PROTOCOLS.add('data') as already mentioned, like this:
```
Loofah::HTML5::WhiteList::ALLOWED_PROTOCOLS.replace RedmineCkeditor.allowed_protocols
Loofah::HTML5::WhiteList::ALLOWED_PROTOCOLS.add('data')
```
(the order is important)

I'm using CKEditor plugin 1.1.5 and Bitnami Redmine 3.3.1
No need to add base64image plugin.

**Comment by acosonic** [comment]
The second line is still not present in init.rb, I have added it manually and data protocol worked...

Please reopen this issue...
