### ISSUE TITLE
LoadError: No such file to load -- rich/files_helper

### ISSUE THREAD

**Issue by mtyu** [a-ono/redmine_ckeditor#197]
Hi,

I used the default redmine package from Ubuntu 14.04.3 LTS and met the same problem as #131. The following is what I see.

Redmine 2.4.2.stable

Default administrator account changed True
Attachments directory writable True
Plugin assets directory writable True
RMagick available (optional) True
ImageMagick convert available (optional) True

Environment:
Redmine version 2.4.2.stable
Ruby version 1.9.3-p484 (2013-11-22) [x86_64-linux]
Rails version 3.2.16
Environment production
Database adapter Mysql2
SCM:
Git 1.9.1
Filesystem

Redmine plugins:
no plugin installed

:/usr/share/redmine$ sudo bundle install --without development test
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users on this machine.
Rubygems 1.8.23 is not threadsafe, so your gems will be installed one at a time. Upgrade to Rubygems 2.1.0 or higher to enable parallel gem installation.
Resolving dependencies...
Using rake 10.5.0
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.8.4
Using thread_safe 0.3.5
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile2 2.0.0
Using rack 1.6.4
Using mime-types 2.99
Using arel 6.0.3
Using bundler 1.11.2
Using concurrent-ruby 1.0.0
Using htmlentities 4.3.4
Using thor 0.19.1
Using multi_json 1.11.2
Using mysql2 0.4.2
Using pandoc-ruby 1.0.0
Using sass 3.4.21
Using tilt 2.0.2
Using tzinfo 1.2.2
Using nokogiri 1.6.7.2
Using rack-test 0.6.3
Using mail 2.6.3
Using sprockets 3.5.2
Using rack-raw-upload 1.1.1
Using activesupport 4.2.5.1
Using loofah 2.0.3
Using rails-deprecated_sanitizer 1.0.3
Using globalid 0.3.6
Using activemodel 4.2.5.1
Using climate_control 0.0.3
Using rails-html-sanitizer 1.0.3
Using rails-dom-testing 1.0.7
Using activejob 4.2.5.1
Using activerecord 4.2.5.1
Using cocaine 0.5.8
Using actionview 4.2.5.1
Using paperclip 3.5.4
Using actionpack 4.2.5.1
Using actionmailer 4.2.5.1
Using railties 4.2.5.1
Using kaminari 0.16.3
Using sprockets-rails 3.0.1
Using jquery-rails 4.1.0
Using rails 4.2.5.1
Using sass-rails 5.0.4
Using rich 1.4.6
Bundle complete! 6 Gemfile dependencies, 48 gems now installed.
Gems in the groups development and test were not installed.
Use bundle show [gemname] to see where a bundled gem is installed.

:/usr/share/redmine$ sudo rake redmine:plugins:migrate RAILS_ENV=production
rake aborted!
LoadError: No such file to load -- rich/files_helper
/usr/share/redmine/plugins/redmine_ckeditor/lib/redmine_ckeditor/rich_files_helper_patch.rb:1:in <top (required)>' /usr/share/redmine/plugins/redmine_ckeditor/lib/redmine_ckeditor.rb:128:inapply_patch'
/usr/share/redmine/plugins/redmine_ckeditor/init.rb:5:in block in <top (required)>' /usr/share/redmine/config/environment.rb:14:in'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

Do you know why the above happened? I Googled for more than a week but still can not resolved this issue. Looks similar to the issue reported here (https://www.redmine.org/boards/3/topics/46292), but I have no luck to resolve it in the same way. Seems that rich is not installed well. Could you help me and see where I did wrong?

Thanks a lot!

**Comment by a-ono** [comment]
> Redmine version 2.4.2.stable
> Rails version 3.2.16
> Using rails 4.2.5.1

It's wired.
It doesn't seem to be Redmine 2.4.2.

**Comment by mtyu** [comment]
Before "sudo bundle install --without development test", I can see Rails 3.2.16 from "rails -v" issued at any working directory. However, after this, if I change to like /var/lib/gems, I will see Rails 4.2.5.1.

**Comment by a-ono** [comment]
> Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users on this machine.

You should not use sudo command.

**Comment by JoshCoCML** [comment]
Hi - I'm recieving this same error.

LoadError: No such file to load -- rich/files_helper

How is this resolved?

Thanks

Josh

**Comment by bartroff** [comment]
Hi, I have the same issue. Any tips on how to fix this? 

Btw, why is this topic closed when there is no solution yet? 

Regards - Allan
