### ISSUE TITLE
Cannot upload images

### ISSUE THREAD

**Issue by vvklymchuk** [a-ono/redmine_ckeditor#198]
I've installed CKEditor on bitnami redmine stack 3.2.0. All work perfect except uploading images. When I choose some image (doesn't matter size of image), I get this error.

![alt tag](http://i65.tinypic.com/2qn8gud.jpg)

In file production.log there are lines:

Processing by Rich::FilesController#create as HTML
  Parameters: {"file"=>#<ActionDispatch::Http::UploadedFile:0xadff010 @tempfile=#<Tempfile:C:/Windows/Temp/thin-body20160222-3152-k6eogc>, @original_filename="IMG_1542.JPG", @content_type="application/octet-stream", @headers=nil>, "authenticity_token"=>"4xtGrdUJuMFB2e7s9nzwMGhmpnUL1/F0oMoX0ER+goXGo6k04cWaxYPhF61p6cx7/0jrxaDNtBq/b4kfO6oQ5g==", "simplified_type"=>"image", "scoped"=>"true", "scope_type"=>"Project", "scope_id"=>"1", "qqfile"=>"IMG_1542.JPG"}
  Current user: admin (id=1)
Command :: identify -format '%wx%h,%[exif:orientation]' "C:/Windows/Temp/78f9cb676f3ac9b1b05b99341239be1320160222-3152-wwwqih.JPG[0]" 2>NUL
Command :: identify -format %m "C:/Windows/Temp/78f9cb676f3ac9b1b05b99341239be1320160222-3152-wwwqih.JPG[0]"
Command :: convert "C:/Windows/Temp/78f9cb676f3ac9b1b05b99341239be1320160222-3152-wwwqih.JPG[0]" -auto-orient -resize "100x" -crop "100x100+0+16" +repage "C:/Windows/Temp/78f9cb676f3ac9b1b05b99341239be1320160222-3152-wwwqih20160222-3152-1ukvrzj"
**[paperclip] An error was received while processing: #\<Paperclip::Error: There was an error processing the thumbnail for 78f9cb676f3ac9b1b05b99341239be1320160222-3152-wwwqih\>**

Executing "convert" command with these files in cmd ends without errors.
Some info:
C:\Bitnami\redmine-3.2.0-2\apps\redmine\htdocs>which convert
C:\Bitnami\redmine-3.2.0-2\imagemagick\convert.EXE

C:\Bitnami\redmine-3.2.0-2\apps\redmine\htdocs>convert --version
Version: ImageMagick 6.9.2-0 Q8 x86 2015-08-15 http://www.imagemagick.org

**Comment by yamoe** [comment]
1. add windows environment variable
Path : C:\Bitnamiredmine-3.2.0-2\imagemagick
MAGICK_CODER_MODULE_PATH : C:\Bitnamiredmine-3.2.0-2\imagemagick**

2. change "Log On". windows service property : readmineThin1, readmineThin2
This account : Local Service
Password : ""
Confirm password : ""

3. restart readmineThin1, readmineThin2 windows service

good luck.... =0=;;;;

**Comment by vvklymchuk** [comment]
Thank you, but didn't help. The same error.

**Comment by iosx** [comment]
I get the same error, too.

**Comment by jakingfox** [comment]
I get the same error, too.

**Comment by rolek** [comment]
Same issue. Set permissions to Everyone to test, still no go.
Set service user as Local System. No go. Same error

**Comment by archonwang** [comment]
+1

**Comment by mmartinezespichan** [comment]
Me too, the the same error:
Specs: OS: Win7
Environment:
  Redmine version                3.2.3.stable
  Ruby version                   2.1.8-p440 (2015-12-16) [i386-mingw32]
  Rails version                  4.2.5.2
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.16
  Git                            2.7.4
  Filesystem                     
Redmine plugins:
  redmine_ckeditor               1.1.4
  redmine_landing_page           0.1.0
  redmine_wiki_extensions        0.7.0
  redmine_workflow_enhancements  0.5.0

**Comment by jackygu88** [comment]
I have the same problems.   in windows.  this is a bug or other?

**Comment by swbrhel** [comment]
I have the same problems. in windows ?
Some solution ?

**Comment by swbrhel** [comment]
That mean .... C:**/Windows**/Temp/bf215181b5140522 ....

**Comment by a-ono** [comment]
https://github.com/a-ono/redmine_ckeditor/issues/224#issuecomment-256273776

This issue is caused by  c:\windows\system32\convert.exe.

* Add imagemagick directory to the PATH environment variable **before c:\windows\system32**
* Restart **Windows** (https://support.microsoft.com/en-us/kb/821761)

**Comment by archonwang** [comment]
@a-ono , and some question about unix, I installed on centOS 6, how to config to use ckeditor to upload images?

**Comment by undigo** [comment]
Good instruction of @a-ono 
I put ImageMagick Path at the FIRST position on PATH system environnement System Variable
then restart Windows and download file on CKeditor is done, cool !

Windows 7 Entreprise 64 bits SP1 (on Virtual machine)
My redmine config :
Environment:
  Redmine version                3.3.3.stable
  Ruby version                   2.1.9-p490 (2016-03-30) [i386-mingw32]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            2.7.4
  Filesystem                     
Redmine plugins:
  a_common_libs                  2.3.0
  clipboard_image_paste          1.12
  issue_charts                   1.3.0
  periodictask                   3.2.1
  redhopper                      1.0.7
  redmine_agile                  1.4.3
  redmine_card                   0.0.1
  redmine_checklists             3.1.5
  redmine_ckeditor               1.1.4
  redmine_custom_reports         0.1.5
  redmine_drawio                 0.6.0
  redmine_issue_tabs             1.2.2
  redmine_issue_templates        0.1.5
  redmine_issues_tree            0.0.9
  redmine_knowledgebase          3.2.1
  redmine_tweaks                 1.0.1

**Comment by marasong** [comment]
> 
> 
>     1. add windows environment variable
>        Path : C:\Bitnami\redmine-3.2.0-2\imagemagick
>        MAGICK_CODER_MODULE_PATH : C:\Bitnami\redmine-3.2.0-2\imagemagick
> 
>     2. change "Log On". windows service property : readmineThin1, readmineThin2
>        This account : Local Service
>        Password : ""
>        Confirm password : ""
> 
>     3. restart readmineThin1, readmineThin2 windows service
> 
> 
> good luck.... =0=;;;;

No 1 -> Restart Windows -> Working ~ 
Thanks a lot ~
