### ISSUE TITLE
HTML entities in code blocks

### ISSUE THREAD

**Issue by wilsoc5** [a-ono/redmine_ckeditor#199]
We have a user who insists on putting in the python interpreter ">>>" in his python code blocks in a wiki.
These get converted to the HTML entities &amp;gt;&amp;gt;&amp;gt; when saved to the wiki database. When viewed, these are not converted back to the ">>>" as it is inside a &lt;pre&gt; block.

I found that changing lib/redmine_ckeditor/wiki_formatting/formatter.rb line 17:
````
        %Q[<pre>\n<code class="#{lang} syntaxhl">#{
          Redmine::SyntaxHighlighting.highlight_by_language(code, lang)
        }</code>\n</pre>]
`````
to 
````
        %Q[<pre>\n<code class="#{lang} syntaxhl">#{
          Redmine::SyntaxHighlighting.highlight_by_language(CGI.unescapeHTML(code), lang)
        }</code>\n</pre>]
`````

solved our problem with HTML entities in code.

**Comment by a-ono** [comment]
Thank you for your feedback.
