### ISSUE TITLE
video tag stripped from html

### ISSUE THREAD

**Issue by aguarino77** [a-ono/redmine_ckeditor#204]
Hello, 

despite setting allowedContent: true in creditor.yml, the <video> tag seems to be removed when html is generated. Any hint?
I found a similar issue  #186 , but I cannot understand how it was fixed.

Thanks

**Comment by aguarino77** [comment]
In the three following screenshots you see what I mean.

Screenshot 1: editing in CKeditor in source mode shows the <video> tag
Screenshot 2: switching to WSIWYG mode displays some black box as video placeholder
Screenshot 3: as soon as I save the page the video tag disappears. Inspecting the page source reveals that the <video> tag is stripped away!

Any hints?

**Screenshot 1**
![screen shot 2016-04-14 at 08 30 24](https://cloud.githubusercontent.com/assets/7809076/14518866/4167d7a2-021b-11e6-97a4-ac7b3d0899fe.png)

**Screenshot 2**
![screen shot 2016-04-14 at 08 31 41](https://cloud.githubusercontent.com/assets/7809076/14518875/56cae422-021b-11e6-8a8a-b70761a493a0.png)

**Screenshot 3**
![screen shot 2016-04-14 at 08 32 00](https://cloud.githubusercontent.com/assets/7809076/14518880/6045ce0e-021b-11e6-8c63-1a90e33f63ab.png)

**Comment by aguarino77** [comment]
Slight improvement:
if I add the video tag to the lib/redmine_ckeditor.rb file

```ruby
    def allowed_tags
      @allowed_tags ||= %w[
        a abbr acronym address blockquote b big br caption cite code dd del dfn
        div dt em h1 h2 h3 h4 h5 h6 hr i img ins kbd li ol p pre samp small span
        strike s strong sub sup table tbody td tfoot th thead tr tt u ul var video iframe
      ]
    end
```

then the <video> tag is not stripped by the sanitizer any more. Still the browser refuses to display the video. Only an empty div appears.

So that the source 
```html
<video controls="controls" height="300" id="video20163149112" width="400"><source src="http://simulationsupport.casalelug.ch/attachments/download/337/big_buck_bunny_720p_1mb-3.mp4" type="video/mp4" /> Your browser doesn't support video.</video>
```

becomes after saving
```html
<video height="300" width="400"> Your browser doesn't support video.</video>
```

**Comment by a-ono** [comment]
It's now configurable in REDMINE_ROOT/config/ckeditor.yml.
