### ISSUE TITLE
{{toc}} not working?

### ISSUE THREAD

**Issue by aguarino77** [a-ono/redmine_ckeditor#206]
Despite many users confirm it is working, I cannot get the {{toc}} macro working. It is simply ignored and stays as such. All other macros work.

When I do {{macro_list}}, {{toc}} is not appearing.
If I switch to textile and try it on a textile page, it works.

Any idea?

**Comment by aguarino77** [comment]
I might add my configuration: 

Environment:
  Redmine version                3.2.1.stable
  Ruby version                   2.1.7-p400 (2015-08-18) [i386-mingw32]
  Rails version                  4.2.5.2
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.11
  Git                            2.5.1
  Filesystem                     
Redmine plugins:
  clipboard_image_paste          1.10
  redmine_ckeditor               1.1.3
  redmine_stats                  0.0.3
  redmine_wiki_extensions        0.7.0

**Comment by JL2014** [comment]
Hi,
Are you sure to use styles title 1, title 2...? the toc is activated only if you use it.
If you show the html source code of your page in ckeditor (with the button source), is there a html code near of the toc, for example : `{{toc}}&nbsp;` ?

**Comment by aguarino77** [comment]
Yep...

this is the beginning of my page ...

```html
{{toc}} 
<h1>Casale Bed</h1>

<h2 id="description">Description</h2>

<p> Casale Bed is a UNISIM extension. It is a very generic reactor unit operation which simulates an adiabatic/pseudo-isothermal Bed Reactor for the following reaction types:</p>

<ul>
	<li>NH3 synthesis</li>
	<li>MeOH Synthesis</li>
	<li>Water Gas Shift</li>
</ul>
```

which produces only 
![screen shot 2016-04-18 at 09 15 03](https://cloud.githubusercontent.com/assets/7809076/14596337/10ab9e18-0546-11e6-8e44-366992bdf570.png)

**Comment by aguarino77** [comment]
Ok, it seems that writing in the source code as 
```
<p>{{>toc}}</p>
```
works!
