### ISSUE TITLE
Multi-line macros not working in editor

### ISSUE THREAD

**Issue by ftab** [a-ono/redmine_ckeditor#208]
e.g. wiki graphviz plugin

```
{{graphviz_link()
digraph G {
  subgraph cluster_se {
    graph [label="Search Engine"]
    y [label="Yahoo!", URL="http://www.yahoo.com/"]
    g [label="Google", URL="http://www.google.com/"]
  }
  p [label="Page"]
  g -> p
}
}}
```

Trying to insert this into a wiki page while the CKEditor is active results in the following being inserted as the source code:

```
{{graphviz_link()<br />
digraph G {<br />
&nbsp; subgraph cluster_se {<br />
&nbsp;&nbsp;&nbsp; graph [label=&quot;Search Engine&quot;]<br />
&nbsp;&nbsp;&nbsp; y [label=&quot;Yahoo!&quot;, URL=&quot;http://www.yahoo.com/&quot;]<br />
&nbsp;&nbsp;&nbsp; g [label=&quot;Google&quot;, URL=&quot;http://www.google.com/&quot;]<br />
&nbsp; }<br />
&nbsp; p [label=&quot;Page&quot;]<br />
&nbsp; g -&gt; p<br />
}<br />
}}
```

This then does not get processed.

If I change the source so that it is like so:

```
<p>{{graphviz_link()
digraph G {
  subgraph cluster_se {
    graph [label="Search Engine"]
    y [label="Yahoo!", URL="http://www.yahoo.com/"]
    g [label="Google", URL="http://www.google.com/"]
  }
  p [label="Page"]
  g -> p
}
}}</p>
```

it will then work, but only until I hit the edit button the next time, at which point it's reverted again to the broken form with encoded quotes and `<br />`'s on every line.

**Comment by ftab** [comment]
Hi! Thanks for your attention to this issue. I have pulled the code, updated gems, and restarted Redmine, and it appears to no longer be inserting the noted br's and nbsp's into the source, but it is still not handled correctly in the WYSIWYG editor :( If I paste the text of the sample graphviz macro noted in the OP directly into the WYSIWYG editor, the text is collapsed onto one line and does not work

> ![image](https://cloud.githubusercontent.com/assets/1690894/18145184/18b5739c-6f98-11e6-8d98-0929f34073c9.png)

Resulting source:
> ![image](https://cloud.githubusercontent.com/assets/1690894/18145218/37b6c7c8-6f98-11e6-84a0-fd51cd354b63.png)


If I paste the contents directly into source view, it does work:

> ![image](https://cloud.githubusercontent.com/assets/1690894/18145233/50b58ab6-6f98-11e6-8c66-4565f5b88cd3.png)


But only while I'm in the source view. Once I exit, it's collapsed back onto one line again (including on subsequent edits of the page):

> ![image](https://cloud.githubusercontent.com/assets/1690894/18145256/6d5e4158-6f98-11e6-8af7-80c30b65ea7d.png)


Incidentally, I noticed while copying and pasting directly from this Github issue comment that the text was pasted as `<pre><code>`, with HTML entities escaped out. O_o

> ![image](https://cloud.githubusercontent.com/assets/1690894/18145341/cd04413e-6f98-11e6-9e2c-63bfd5397ec5.png)
> ![image](https://cloud.githubusercontent.com/assets/1690894/18145354/ddda823e-6f98-11e6-814b-15ceba7acf2a.png)

I wonder what that's about. In any case, typing the macro manually into the WYSIWYG editor also does not work. I did this, then clicked the preview link, and noted that the preview consists of nbsps and brs and the macro does not get processed.

I have tried using newline mode p, div, and br, neither of them changed the behavior.

Anything I can do to help track it down?

Thanks :)

**Comment by stellaf** [comment]
Is this solved? The problem described in the post above still remaining not solve seems.
