### ISSUE TITLE
migration

### ISSUE THREAD

**Issue by timmyver** [a-ono/redmine_ckeditor#209]
i'm having problems with the migrations,
when i run the migration (_rake redmine:plugins:migrate RAILS_ENV=production)_ of existing issue's  it doesn't give an error but when i look into the text of the issue's created before the layout is complete messed up. The picture's are still in there but the tabs, spaces, OEF, etc. are complete messed.

did anybody already had this kind of problems?

**Comment by lanelarochelle** [comment]
Its due to formatting issues if you are switching from a different format like textile

**Comment by a-ono** [comment]
Please see below:
https://github.com/a-ono/redmine_ckeditor#migration-notes
