### ISSUE TITLE
How to include code syntax highlighting?

### ISSUE THREAD

**Issue by wdjunaidi** [a-ono/redmine_ckeditor#21]
This might not be an issue. I have been trying to use the different editing option, but I can't seem to get the code syntax highlighting back on redmine. Is there a way to get the syntax highlighting working?

I also tried editing the "Source" from CKEditor pluging and manually input <pre><code></code></pre> tags, but it still does not work.

**Comment by halida** [comment]
I've found a way to fix this.

Install those plugin for ck_editor:

* http://ckeditor.com/addon/lineutils
* http://ckeditor.com/addon/widget
* http://ckeditor.com/addon/codesnippet

Then edit plugins/redmine_ckeditor/lib/redmine_ckeditor/wiki_formatting.rb:

```ruby
...
      ).gsub(/<pre>\s*<code\s+(?:class="(language\-)?(\w+)")>[\r\n]*([^<]*?)[\r\n]*<\/code>\s*<\/pre>/) { # support codesnippet highlight
...
```

So ck_editor SyntaxHighlighting will support  codesnippet format.

**Comment by Luckyvb** [comment]
halida +1

**Comment by aguarino77** [comment]
Thank you @halida

**Comment by joanmarcriera** [comment]
Thanks @halida

**Comment by LuisIrigoyen** [comment]
How can I install the plugin into redmine_ckeditor¿?

**Comment by LuisIrigoyen** [comment]
plugins/redmine_ckeditor/lib/redmine_ckeditor/wiki_formatting.rb: does not exist :(

**Comment by AshkanV** [comment]
As current version of Redmine (3.4.4) and CKEditor (4.9), I used this simple method successfully:
 
1. Download CodeSnippets and all of its dependencies **recursively**: button clipboard codesnippet dialog dialogui lineutils notification toolbar widget widgetselection
2. Extract all plugins
3. Some plugins are extract in a a nested subfolder (they ususally have a version number in their extracted folder name). Their content should be cut and past to the parent folder and their name must not have a version number in it.
4. Copy all the pluging to this path: plugins/redmine_ckeditor/assets/ckeditor-contrib/plugins/
5. Remove this folder: public/plugin_assets/redmine_ckeditor/
6. Restart Redmine
