### ISSUE TITLE
Upgrading CKEditor - error

### ISSUE THREAD

**Issue by adrianobo** [a-ono/redmine_ckeditor#211]
When I try Upgrading CKEditor following the README.rdoc instructions I have a problem when run 
`rails generate redmine_ckeditor:rich_assets`

This execution show the error below: 

> ckeditor-releases]# rails generate redmine_ckeditor:rich_assets
> /usr/local/rvm/gems/ruby-1.9.3-p551/gems/mysql2-0.3.20/lib/mysql2/client.rb:70:in `connect': Access denied for user 'root'@'localhost' (using password: NO) (Mysql2::Error)
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/mysql2-0.3.20/lib/mysql2/client.rb:70:in `initialize'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `new'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `mysql2_connection'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
>         from /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
>         from /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activerecord-4.2.5.2/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activerecord-4.2.5.2/lib/active_record/connection_handling.rb:87:in `connection'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activerecord-4.2.5.2/lib/active_record/model_schema.rb:230:in `table_exists?'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activerecord-4.2.5.2/lib/active_record/attribute_methods/primary_key.rb:97:in `get_primary_key'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activerecord-4.2.5.2/lib/active_record/attribute_methods/primary_key.rb:85:in `reset_primary_key'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activerecord-4.2.5.2/lib/active_record/attribute_methods/primary_key.rb:73:in `primary_key'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/protected_attributes-1.1.3/lib/active_record/mass_assignment_security/attribute_assignment.rb:15:in `attributes_protected_by_default'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/protected_attributes-1.1.3/lib/active_model/mass_assignment_security.rb:337:in `block in protected_attributes_configs'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/protected_attributes-1.1.3/lib/active_model/mass_assignment_security.rb:222:in `yield'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/protected_attributes-1.1.3/lib/active_model/mass_assignment_security.rb:222:in `default'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/protected_attributes-1.1.3/lib/active_model/mass_assignment_security.rb:222:in `protected_attributes'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/protected_attributes-1.1.3/lib/active_model/mass_assignment_security.rb:126:in `block in attr_protected'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/protected_attributes-1.1.3/lib/active_model/mass_assignment_security.rb:125:in `each'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/protected_attributes-1.1.3/lib/active_model/mass_assignment_security.rb:125:in `attr_protected'
>         from /var/www/redmine/app/models/custom_field.rb:36:in `<class:CustomField>'
>         from /var/www/redmine/app/models/custom_field.rb:18:in `<top (required)>'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:457:in `load'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:457:in `block in load_file'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:647:in `new_constants_in'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:456:in `load_file'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:354:in `require_or_load'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:494:in `load_missing_constant'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:184:in `const_missing'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:526:in `load_missing_constant'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:184:in `const_missing'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:526:in `load_missing_constant'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:184:in `const_missing'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:526:in `load_missing_constant'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:184:in `const_missing'
>         from /var/www/redmine/lib/redmine/field_format.rb:87:in `field_attributes'
>         from /var/www/redmine/lib/redmine/field_format.rb:90:in `<class:Base>'
>         from /var/www/redmine/lib/redmine/field_format.rb:48:in `<module:FieldFormat>'
>         from /var/www/redmine/lib/redmine/field_format.rb:19:in `<module:Redmine>'
>         from /var/www/redmine/lib/redmine/field_format.rb:18:in `<top (required)>'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `require'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `block in require'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:240:in `load_dependency'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `require'
>         from /var/www/redmine/lib/redmine.rb:38:in `<top (required)>'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `require'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `block in require'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:240:in `load_dependency'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `require'
>         from /var/www/redmine/config/initializers/30-redmine.rb:6:in `<top (required)>'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:268:in `load'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:268:in `block in load'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:240:in `load_dependency'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:268:in `load'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/railties-4.2.5.2/lib/rails/engine.rb:652:in `block in load_config_initializer'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.5.2/lib/active_support/notifications.rb:166:in `instrument'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/railties-4.2.5.2/lib/rails/engine.rb:651:in `load_config_initializer'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/railties-4.2.5.2/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/railties-4.2.5.2/lib/rails/engine.rb:615:in `each'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/railties-4.2.5.2/lib/rails/engine.rb:615:in `block in <class:Engine>'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/railties-4.2.5.2/lib/rails/initializable.rb:30:in `instance_exec'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/railties-4.2.5.2/lib/rails/initializable.rb:30:in `run'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/railties-4.2.5.2/lib/rails/initializable.rb:55:in `block in run_initializers'
>         from /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/tsort.rb:150:in `block in tsort_each'
>         from /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/tsort.rb:183:in `block (2 levels) in each_strongly_connected_component'
>         from /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/tsort.rb:210:in `block (2 levels) in each_strongly_connected_component_from'
>         from /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/tsort.rb:219:in `each_strongly_connected_component_from'
>         from /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/tsort.rb:209:in `block in each_strongly_connected_component_from'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/railties-4.2.5.2/lib/rails/initializable.rb:44:in `each'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/railties-4.2.5.2/lib/rails/initializable.rb:44:in `tsort_each_child'
>         from /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/tsort.rb:203:in `each_strongly_connected_component_from'
>         from /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/tsort.rb:182:in `block in each_strongly_connected_component'
>         from /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/tsort.rb:180:in `each'
>         from /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/tsort.rb:180:in `each_strongly_connected_component'
>         from /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/tsort.rb:148:in `tsort_each'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/railties-4.2.5.2/lib/rails/initializable.rb:54:in `run_initializers'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/railties-4.2.5.2/lib/rails/application.rb:352:in `initialize!'
>         from /var/www/redmine/config/environment.rb:14:in `<top (required)>'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `require'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `block in require'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:240:in `load_dependency'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `require'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/railties-4.2.5.2/lib/rails/application.rb:328:in `require_environment!'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:142:in `require_application_and_environment!'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:128:in `generate_or_destroy'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:50:in `generate'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
>         from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/railties-4.2.5.2/lib/rails/commands.rb:17:in `<top (required)>'
>         from bin/rails:4:in `require'
>         from bin/rails:4:in `<main>'
> 
You can help me?

**Comment by a-ono** [comment]
> Access denied for user 'root'@'localhost' (using password: NO) (Mysql2::Error)

You probably didn't configure database.yml for development environment.
Please try this:
`RAILS_ENV=production rails generate redmine_ckeditor:rich_assets`
