### ISSUE TITLE
Not working 1.1.3 on redmine 3.2.1

### ISSUE THREAD

**Issue by TadejPanjtar** [a-ono/redmine_ckeditor#212]
I was following instructions here to install plugin. Tried to deploy 1.1.3 to redmine version 3.2.1 (https://bitnami.com/stack/redmine/virtual-machine) but this plugin break whole redmine.

**Comment by andymnc** [comment]
at the moment, as u can see on the readme, it's compatible =< 3.0.x
so not with 3.2.x

**Comment by a-ono** [comment]
It should work.
Please add more information.
