### ISSUE TITLE
Inline(Base64) Images are not shown anyone after update to redmine 3.2.2

### ISSUE THREAD

**Issue by rompic** [a-ono/redmine_ckeditor#213]
I noticed that images inlined/pasted as Base64 (using ckeditor) are not displayed any more (empty src tag in HTML) in issues, notes, project Descriptions after updating to 3.2.2.

when editing everything seems fine.

**Comment by blackhase** [comment]
Hallo, 
have some problem. 
Please help.

**Comment by rompic** [comment]
could it be a result of this fix?
http://www.redmine.org/projects/redmine/repository/revisions/15362

**Comment by rompic** [comment]
i filed a bug in the redmine forum but it was closed http://www.redmine.org/issues/22910

**Comment by rompic** [comment]
sounds similar to https://github.com/a-ono/redmine_ckeditor/issues/196

**Comment by blackhase** [comment]
No, isnt fixed. 
Thx,

**Comment by rompic** [comment]
adding the fix proposed in https://github.com/a-ono/redmine_ckeditor/issues/196#issuecomment-184509446 solves this problem.
@a-ono would be great if this could be in the next release of the plugin.

**Comment by a-ono** [comment]
See https://github.com/a-ono/redmine_ckeditor/issues/196#issuecomment-239682908
