### ISSUE TITLE
Compatibility with Redmine 3.3.0

### ISSUE THREAD

**Issue by ehvidal** [a-ono/redmine_ckeditor#214]
Thank you very much for your fine job! I have been using your plugin for the last 5 years and I think it's awesome.

Now I'm planning to migrate my Redmine to 3.3.0, so my question is, are you planning to make your plugin compatible with Redmine 3.3.0 soon? Do you have some idea about when it will be published?

Again, thank you very much for your excellent work!

**Comment by a-ono** [comment]
It works with Redmine 3.3.0.

**Comment by ehvidal** [comment]
Thank you very much, @a-ono, again, you did a great job with this plugin! ;)
