### ISSUE TITLE
Include macro between Textile and CKEditor wiki

### ISSUE THREAD

**Issue by Champal** [a-ono/redmine_ckeditor#219]
Hi, 

CKEditor is a great improvments in Wiki Editing but we have old wiki in textile and we use "redmine_per_project_formatting".
Include macro works fine from Textile to Textile and from CKEditor to CKEditor
But including page in the mix way doesn't work

For memory the include macro of redmine : 
```
desc "Includes a wiki page. Examples:\n\n" +
         "{{include(Foo)}}\n" +
         "{{include(projectname:Foo)}} -- to include a page of a specific project wiki
macro :include do |obj, args|
    page = Wiki.find_page(args.first.to_s, :project => @project)
    raise 'Page not found' if page.nil? || !User.current.allowed_to?(:view_wiki_pages, page.wiki.project)
    @included_wiki_pages ||= []
    raise 'Circular inclusion detected' if @included_wiki_pages.include?(page.title)
    @included_wiki_pages << page.title
    out = textilizable(page.content, :text, :attachments => page.attachments, :headings => false)
    @included_wiki_pages.pop
    out
end
```

### From CKeditor to Textile 
Include macro print the html source .  `<html><head><title>...</html>`
Adding this in an iframe srcdoc produce html rendering but without css
```
o = ''
o << '<iframe srcdoc="'+ out + '" style="border: 0" width="100%" height="400pt" frameborder="0" scrolling="auto"></iframe>'
o.html_safe
```

Other solution : 
* put the whole page in an iframe but there is menu, footer, editing, ...
* put the html export of a wiki page in an iframe but this force downloading ....

### From Textile to CKeditor
Include macro print the raw textile source `*bold*  _italic_`
The question here is how to invoke textile rendering in an CKEditor wiki page 

Thanks, 
Stéphane.

**Comment by a-ono** [comment]
Unfortunately It's not possible at the moment.
Maybe it's necessary to store the format per page or extend macro syntax.
I'm closing this issue because it's a problem of redmine_per_project_formatting.

**Comment by Champal** [comment]
Hi, 

My question wasn't automatic detection but how to include wiki page from different formating.
I can use 2 differents macros for "textile to CKEditor" and "CKEditor to textile".
If that work it would be be a good improvements to make automatic detection of format what involves redmine_per_project_formatting

For the first point do you have any idea ?

Stéphane

**Comment by a-ono** [comment]
You can convert textile to html like below.
```
textile_source = "*bold* _italic_"
formatter = Redmine::WikiFormatting.formatter_for("textile")
formatter.new(textile_source).to_html
```

**Comment by Champal** [comment]
Hi,

adding this at the end of include macro 
```
#out
formatter = Redmine::WikiFormatting.formatter_for("textile")
formatter.new(out).to_html
```
Transform textile code to html (quote don't work) but display raw html source code
`Blabla textile<br /><strong>bold</strong> <ul> <li>Item 1<br />&gt; quotes</li> </ul>` 
Embeding in an iframe "display" html but without style

Stéphane

**Comment by a-ono** [comment]
It seems to be sanitized by rails.
Please try this:
```
formatter.new(out).to_html.html_safe
```

**Comment by Champal** [comment]
It's work ! Thanks !
There is a limitation with blockquotes :  bq. work but '>' and nested '>' don't work
http://www.redmine.org/projects/redmine/wiki/RedmineTextFormattingTextile#Blockquotes

For the other way CKE -> Textile : how to get the content only of a CKE page without `<html><head><title>` ?

For autodetection of source format, do you want I open an issue in redmine_per_project_formatting ?

Stéphane

**Comment by Champal** [comment]
Hi, 
Another problem with textile to CKE : if there is an issue `#xxxx`on the textile wiki page there will be the html code of the issue `<a class="issue tracker ...` on the CKE wiki page
Stéphane
