### ISSUE TITLE
Using browser spell checker

### ISSUE THREAD

**Issue by Wayn0** [a-ono/redmine_ckeditor#220]
I searched through the issues and could not seem to find this, but it's been a long day.

Is there anyway to tell ck-editor to use the browsers spell checker?

Thanks

**Comment by nixmomo** [comment]
Nop there isn't but your Browser should use it as in any other Textfields

**Comment by Wayn0** [comment]
yeah that's the problem, works everywhere except the in the CKeditor field.

Thanks

**Comment by a-ono** [comment]
Please see http://docs.ckeditor.com/#!/guide/dev_spellcheck
