### ISSUE TITLE
Install error ActionDispatch::XmlParamsParser

### ISSUE THREAD

**Issue by chebyrek** [a-ono/redmine_ckeditor#226]
Hello,

I have a issue with redmine_ckeditor plugin. I tried to install redmine_ckeditor on Redmine 3.2 but it always failed at final step "rake redmine:plugins:migrate RAILS_ENV=production"

Error output:
when i do `rake --trace redmine:plugins:migrate RAILS_ENV=production`

`user@srv-redmine:/usr/share/redmine/lib/plugins/redmine_ckeditor$ rake --trace redmine:plugins:migrate RAILS_ENV=production
(in /usr/share/redmine)
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
Rails Error: Unable to access log file. Please ensure that /usr/share/redmine/instances/default/log/production.log exists and is writable (ie, make it writable for user and group: chmod 0664 /usr/share/redmine/instances/default/log/production.log). The log level has been raised to WARN and the output directed to STDERR until the problem is fixed.
rake aborted!
LoadError: No such file to load -- rich/files_helper
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:274:in `require'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:274:in `block in require'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:240:in `load_dependency'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:274:in `require'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:360:in `require_or_load'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:317:in `depend_on'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:233:in `require_dependency'
/usr/share/redmine/lib/plugins/redmine_ckeditor/lib/redmine_ckeditor/rich_files_helper_patch.rb:1:in `<top (required)>'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:274:in `require'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:274:in `block in require'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:240:in `load_dependency'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:274:in `require'
/usr/share/redmine/lib/plugins/redmine_ckeditor/lib/redmine_ckeditor.rb:133:in `apply_patch'
/usr/share/redmine/lib/plugins/redmine_ckeditor/init.rb:5:in `block (2 levels) in <top (required)>'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:446:in `instance_exec'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:446:in `block in make_lambda'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:192:in `block in simple'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:504:in `block in call'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:504:in `each'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:504:in `call'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:92:in `__run_callbacks__'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:778:in `_run_prepare_callbacks'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:81:in `run_callbacks'
/usr/lib/ruby/vendor_ruby/action_dispatch/middleware/reloader.rb:83:in `prepare!'
/usr/lib/ruby/vendor_ruby/action_dispatch/middleware/reloader.rb:55:in `prepare!'
/usr/lib/ruby/vendor_ruby/rails/application/finisher.rb:50:in `block in <module:Finisher>'
/usr/lib/ruby/vendor_ruby/rails/initializable.rb:30:in `instance_exec'
/usr/lib/ruby/vendor_ruby/rails/initializable.rb:30:in `run'
/usr/lib/ruby/vendor_ruby/rails/initializable.rb:55:in `block in run_initializers'
/usr/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
/usr/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/lib/ruby/2.3.0/tsort.rb:347:in `each'
/usr/lib/ruby/2.3.0/tsort.rb:347:in `call'
/usr/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
/usr/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
/usr/lib/ruby/vendor_ruby/rails/initializable.rb:54:in `run_initializers'
/usr/lib/ruby/vendor_ruby/rails/application.rb:352:in `initialize!'
/usr/share/redmine/config/environment.rb:14:in `<top (required)>'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:274:in `require'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:274:in `block in require'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:240:in `load_dependency'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:274:in `require'
/usr/lib/ruby/vendor_ruby/rails/application.rb:328:in `require_environment!'
/usr/lib/ruby/vendor_ruby/rails/application.rb:457:in `block in run_tasks_blocks'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:199:in `each'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:199:in `invoke_prerequisites'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/var/lib/gems/2.3.0/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
`

and when i do ` bundle exec rake --trace redmine:plugins:migrate RAILS_ENV=production`

`user@srv-redmine:/usr/share/redmine/lib/plugins/redmine_ckeditor$ bundle exec rake --trace redmine:plugins:migrate RAILS_ENV=production
(in /usr/share/redmine)
rake aborted!
NameError: uninitialized constant ActionDispatch::XmlParamsParser
Did you mean?  ActionDispatch::ParamsParser
/usr/share/redmine/config/application.rb:55:in `<class:Application>'
/usr/share/redmine/config/application.rb:8:in `<module:RedmineApp>'
/usr/share/redmine/config/application.rb:7:in `<top (required)>'
/usr/share/redmine/Rakefile:4:in `require'
/usr/share/redmine/Rakefile:4:in `<top (required)>'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/rake_module.rb:28:in `load'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/rake_module.rb:28:in `load_rakefile'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:689:in `raw_load_rakefile'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:94:in `block in load_rakefile'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:93:in `load_rakefile'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:77:in `block in run'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/var/lib/gems/2.3.0/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
`
**Environment:**
Ubuntu Server 16.10
ruby 2.3.0
rails 4.2.7
redmine 3.2.3-2
MySQL

`
user@srv-redmine:/usr/share/redmine/lib/plugins/redmine_ckeditor$ gem list

*** LOCAL GEMS ***

actioncable (5.0.0.1)
actionmailer (5.0.0.1, 4.2.7.1)
actionpack (5.0.0.1, 4.2.7.1)
actionpack-action_caching (1.1.1)
actionpack-xml_parser (2.0.0, 1.0.2)
actionview (5.0.0.1, 4.2.7.1)
activejob (5.0.0.1, 4.2.7.1)
activemodel (5.0.0.1, 4.2.7.1)
activerecord (5.0.0.1, 4.2.7.1)
activesupport (5.0.0.1, 4.2.7.1)
addressable (2.4.0)
arel (7.1.4, 6.0.3)
atomic (1.1.16)
bigdecimal (1.2.8)
binding_of_caller (0.7.2)
blankslate (3.1.3)
builder (3.2.2)
bundler (1.13.6, 1.12.5)
byebug (5.0.0)
climate_control (0.0.3)
cocaine (0.5.8)
coderay (1.1.1)
coffee-rails (4.1.0)
coffee-script (2.4.1)
coffee-script-source (1.10.0)
columnize (0.9.0)
concurrent-ruby (1.0.2, 1.0.0)
css_parser (1.3.6)
debug_inspector (0.0.2)
did_you_mean (1.0.0)
erubis (2.7.0)
eventmachine (1.0.7)
execjs (2.6.0)
ffi (1.9.10)
globalid (0.3.7, 0.3.6)
hike (1.2.1)
htmlentities (4.3.4, 4.3.3)
i18n (0.7.0)
io-console (0.4.5)
jbuilder (2.3.1)
jquery-rails (4.2.1, 4.0.5)
json (2.0.1, 1.8.3)
kaminari (0.17.0)
listen (3.0.3)
loofah (2.0.3)
mail (2.6.4)
method_source (0.8.2)
mime-types (3.1, 2.6.1)
mime-types-data (3.2016.0521)
mimemagic (0.3.0)
mini_portile2 (2.1.0)
minitest (5.9.1, 5.9.0)
molinillo (0.5.0)
multi_json (1.12.1, 1.11.2)
mysql2 (0.4.3)
net-http-persistent (2.9.4)
net-ldap (0.12.1)
net-telnet (0.1.1)
nio4r (1.2.1)
nokogiri (1.6.8.1, 1.6.8)
oj (2.17.1)
pandoc-ruby (2.0.1)
paperclip (4.2.4)
pkg-config (1.1.7)
polyglot (0.3.4)
power_assert (0.2.7)
protected_attributes (1.1.3)
psych (2.0.17)
rack (2.0.1, 1.6.4)
rack-openid (1.4.2)
rack-raw-upload (1.1.1)
rack-test (0.6.3)
rails (5.0.0.1, 4.2.7.1)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (2.0.1, 1.0.6)
rails-html-sanitizer (1.0.3)
rails-observers (0.1.2)
railties (5.0.0.1, 4.2.7.1)
rake (10.5.0)
rb-inotify (0.9.7)
rbpdf (1.19.0)
rbpdf-font (1.19.0)
rdoc (4.2.1)
redcarpet (3.3.4)
request_store (1.3.0)
rmagick (2.15.4)
roadie (3.1.1)
roadie-rails (1.1.0)
ruby-hmac (0.4.0)
ruby-openid (2.7.0)
sass (3.4.22)
sass-rails (5.0.6, 5.0.4)
sdoc (0.4.1)
spring (1.3.6)
sprockets (3.7.0)
sprockets-rails (2.3.3, 2.3.2)
sqlite3 (1.3.11)
test-unit (3.1.7)
thor (0.19.1)
thread_safe (0.3.5)
tilt (2.0.5, 2.0.1)
treetop (1.6.3)
turbolinks (2.5.3)
tzinfo (1.2.2)
uglifier (2.7.2)
web-console (2.2.1)
websocket-driver (0.6.4)
websocket-extensions (0.1.2)
`

**Comment by a-ono** [comment]
You should execute `bundle exec rake` in REDMINE_ROOT(/usr/share/redmine).
