### ISSUE TITLE
Install Error No such file to load -- rich/files_helper

### ISSUE THREAD

**Issue by sherry721** [a-ono/redmine_ckeditor#237]
Hi, @a-ono ,

When I install version 1.0.20, I have an error "No such file to load -- rich/files_helper".

user@TWTPS523:/opt/redmine.org.cn/apps/redmine/htdocs$ bundle exec rake --trace redmine:plugins:migrate RAILS_ENV=production

/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/bundler-1.10.4/lib/bundler/shared_helpers.rb:78: warning: Insecure world writable dir /opt/redmine.org.cn/ruby/bin in PATH, mode 040777
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/bundler-1.10.4/lib/bundler/shared_helpers.rb:78: warning: Insecure world writable dir /opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0 in PATH, mode 040777
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
No such file to load -- rich/files_helper
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:360:in `require_or_load'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:317:in `depend_on'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:233:in `require_dependency'
/opt/redmine.org.cn/apps/redmine/htdocs/plugins/redmine_ckeditor/lib/redmine_ckeditor/rich_files_helper_patch.rb:1:in `<top (required)>'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/opt/redmine.org.cn/apps/redmine/htdocs/plugins/redmine_ckeditor/lib/redmine_ckeditor.rb:128:in `apply_patch'
/opt/redmine.org.cn/apps/redmine/htdocs/plugins/redmine_ckeditor/init.rb:5:in `block in <top (required)>'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:446:in `instance_exec'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:446:in `block in make_lambda'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:192:in `call'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:192:in `block in simple'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:504:in `call'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:504:in `block in call'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:504:in `each'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:504:in `call'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:778:in `_run_prepare_callbacks'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:81:in `run_callbacks'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/reloader.rb:55:in `prepare!'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/railties-4.2.6/lib/rails/application/finisher.rb:50:in `block in <module:Finisher>'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `instance_exec'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `run'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/railties-4.2.6/lib/rails/initializable.rb:55:in `block in run_initializers'
/opt/redmine.org.cn/ruby/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
/opt/redmine.org.cn/ruby/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
/opt/redmine.org.cn/ruby/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
/opt/redmine.org.cn/ruby/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
/opt/redmine.org.cn/ruby/lib/ruby/2.1.0/tsort.rb:345:in `each'
/opt/redmine.org.cn/ruby/lib/ruby/2.1.0/tsort.rb:345:in `call'
/opt/redmine.org.cn/ruby/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
/opt/redmine.org.cn/ruby/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
/opt/redmine.org.cn/ruby/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/railties-4.2.6/lib/rails/initializable.rb:54:in `run_initializers'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/railties-4.2.6/lib/rails/application.rb:352:in `initialize!'
/opt/redmine.org.cn/apps/redmine/htdocs/config/environment.rb:14:in `<top (required)>'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/railties-4.2.6/lib/rails/application.rb:328:in `require_environment!'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/railties-4.2.6/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/task.rb:236:in `call'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/task.rb:236:in `block in execute'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/task.rb:231:in `each'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/task.rb:231:in `execute'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/task.rb:175:in `block in invoke_with_call_chain'
/opt/redmine.org.cn/ruby/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/task.rb:168:in `invoke_with_call_chain'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/task.rb:197:in `block in invoke_prerequisites'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/task.rb:195:in `each'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/task.rb:195:in `invoke_prerequisites'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/task.rb:174:in `block in invoke_with_call_chain'
/opt/redmine.org.cn/ruby/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/task.rb:168:in `invoke_with_call_chain'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/task.rb:161:in `invoke'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/application.rb:149:in `invoke_task'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/application.rb:106:in `each'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/application.rb:106:in `block in top_level'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/application.rb:115:in `run_with_threads'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/application.rb:100:in `top_level'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/application.rb:78:in `block in run'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/application.rb:165:in `standard_exception_handling'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/application.rb:75:in `run'
/opt/redmine.org.cn/ruby/lib/ruby/gems/2.1.0/gems/rake-10.1.1/bin/rake:33:in `<top (required)>'
/opt/redmine.org.cn/ruby/bin/rake:23:in `load'
/opt/redmine.org.cn/ruby/bin/rake:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment

Environment:
 Ubuntu Server 16.04
 Ruby：2.1.9p490 (2016-03-30 revision 54437) [x86_64-linux]
 Rails：4.2.6
 Redmine：3.3.0.stable
 Database adapter：Mysql2

gem list

*** LOCAL GEMS ***

actionmailer (4.2.6, 4.2.5.1)
actionpack (4.2.6, 4.2.5.1)
actionpack-action_caching (1.1.1)
actionpack-xml_parser (1.0.2)
actionview (4.2.6, 4.2.5.1)
activejob (4.2.6, 4.2.5.1)
activemodel (4.2.6, 4.2.5.1)
activerecord (4.2.6, 4.2.5.1)
activesupport (4.2.6, 4.2.5.1)
acts-as-taggable-on (2.4.1)
addressable (2.4.0)
akami (1.2.0)
arel (6.0.3)
atomic (1.1.14)
awesome_nested_set (3.1.1)
aws-sdk (2.1.1)
aws-sdk-core (2.1.1)
aws-sdk-resources (2.1.1)
bcrypt-ruby (3.1.1)
bigdecimal (1.2.4)
binding_of_caller (0.7.2)
bluecloth (2.2.0)
builder (3.2.2)
bundler (1.10.4)
byebug (3.5.1)
charlock_holmes (0.6.9.4)
chartkick (2.1.1)
climate_control (0.0.3)
cocaine (0.5.8)
coderay (1.1.1)
coffee-rails (4.1.0)
coffee-script (2.2.0)
coffee-script-source (1.6.2)
columnize (0.9.0)
concurrent-ruby (1.0.2)
crack (0.3.1)
css_parser (1.3.7)
daemon_controller (1.2.0)
daemons (1.1.8)
dav4rack (0.3.0)
debug_inspector (0.0.2)
debugger-linecache (1.2.0)
diff-lcs (1.1.3)
erubis (2.7.0)
escape_utils (0.2.4)
eventmachine (1.0.4)
execjs (1.4.0)
faraday (0.8.4)
faraday_middleware (0.9.0)
fast_stack (0.1.0)
fast_xor (1.1.1)
fast_xs (0.8.0)
ffi (1.9.0)
gherkin (2.11.1)
github-markdown (0.5.3)
globalid (0.3.6)
groupdate (3.0.2)
gyoku (0.4.6)
hashie (1.2.0)
hike (1.2.3)
hiredis (0.4.5)
hoe (3.0.6)
hoe-bundler (1.2.0)
hoe-debugging (1.0.5)
hoe-gemspec (1.0.0)
htmlentities (4.3.1)
http_parser.rb (0.5.3)
httparty (0.8.3)
httpauth (0.2.0)
i18n (0.7.0)
iconv (1.0.3)
io-console (0.4.3)
jbuilder (2.6.0, 2.0.7)
jmespath (1.0.2)
jquery-rails (3.1.4, 3.0.4)
json (1.8.3, 1.8.1)
jwt (0.1.8)
kaminari (0.17.0)
libv8 (3.16.14.3 x86_64-linux)
loofah (2.0.3)
mail (2.6.4, 2.6.3)
memcache-client (1.8.5)
mime-types (3.0, 2.6.2)
mime-types-data (3.2016.0221)
mimemagic (0.3.1)
mini_magick (3.4)
mini_portile (0.6.0)
mini_portile2 (2.1.0)
minitest (5.9.0, 5.8.1, 4.7.5, 3.3.0)
multi_json (1.12.0, 1.5.0, 1.3.6)
multi_xml (0.5.1)
multipart-post (1.1.5)
mysql2 (0.4.2)
net-ldap (0.12.1)
nokogiri (1.6.8, 1.6.2.1, 1.5.9)
oauth (0.4.7)
oj (2.0.11)
omniauth (1.1.4)
pandoc-ruby (2.0.1)
paperclip (4.2.4, 3.5.4)
passenger (5.0.6)
pg (0.18.0.pre20141117110243, 0.15.1)
pkg-config (1.1.7)
polyglot (0.3.3)
posix-spawn (0.3.6)
protected_attributes (1.1.3)
psych (2.0.5)
racc (1.4.8)
rack (1.6.4)
rack-openid (1.4.2)
rack-raw-upload (1.1.1)
rack-test (0.6.3)
rails (4.2.6, 4.2.5.1)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (1.0.7)
rails-html-sanitizer (1.0.3, 1.0.2)
railties (4.2.6, 4.2.5.1)
rake (11.1.2, 10.4.2, 10.1.1, 10.1.0, 0.8.7)
rake-compiler (0.8.1)
rbpdf (1.19.0)
rbpdf-font (1.19.0)
rdiscount (1.6.8)
rdoc (4.1.0)
redcarpet (3.3.4, 3.0.0, 2.2.2)
RedCloth (4.2.9)
redis (3.0.4)
redmine_acts_as_taggable_on (1.0.0)
redmine_crm (0.0.22)
ref (1.0.2)
request_store (1.0.5)
rexical (1.0.5)
rich (1.4.6)
rinku (1.7.3)
rmagick (2.15.4, 2.13.1)
roadie (3.1.1)
roadie-rails (1.1.1)
rspec (2.11.0)
rspec-core (2.11.1)
rspec-expectations (2.11.2)
rspec-mocks (2.11.1)
ruby-hmac (0.4.0)
ruby-ole (1.2.12)
ruby-openid (2.3.0)
ruby-progressbar (1.8.1)
rubyzip (1.2.0)
rvm (1.11.3.5)
sass (3.4.22, 3.4.14)
sass-rails (5.0.6, 5.0.5, 5.0.3)
sdoc (0.4.0)
simple_enum (2.3.0)
simple_oauth (0.1.9)
slop (3.6.0)
spreadsheet (0.6.9)
spring (1.2.0)
sprockets (3.6.3, 3.4.0, 2.2.1)
sprockets-rails (2.3.3)
sqlite3 (1.3.10)
sqlite3-ruby (1.3.3)
subexec (0.2.2)
test-unit (2.1.9.0)
therubyracer (0.12.0)
thin (1.5.1)
thor (0.19.1, 0.18.1)
thread_safe (0.3.5)
tilt (2.0.5, 1.4.1)
treetop (1.4.14)
turbolinks (1.2.0)
twitter-stream (0.1.16)
tzinfo (1.2.2)
tzinfo-data (1.2014.2)
uglifier (2.1.1)
uuidtools (2.1.5, 2.1.3)
vcard (0.2.12)
vpim (13.11.11)
web-console (2.0.0)
will_paginate (3.1.0)
ya2yaml (0.31)
yajl-ruby (1.1.0)

user@TWTPS523:/opt/redmine.org.cn/apps/redmine/htdocs$ ls -al plugins/redmine_ckeditor/lib/redmine_ckeditor

total 56
drwxr-xr-x 4 root root 4096 Dec 12 18:08 .
drwxr-xr-x 5 root root 4096 Dec 12 18:08 ..
-rw-r--r-- 1 root root  770 Dec 12 18:08 application_helper_patch.rb
drwxr-xr-x 2 root root 4096 Dec 12 18:08 hooks
-rw-r--r-- 1 root root 1008 Dec 12 18:08 journals_controller_patch.rb
-rw-r--r-- 1 root root  799 Dec 12 18:08 mail_handler_patch.rb
-rw-r--r-- 1 root root  875 Dec 12 18:08 messages_controller_patch.rb
-rw-r--r-- 1 root root  459 Dec 12 18:08 pdf_patch.rb
-rw-r--r-- 1 root root  420 Dec 12 18:08 queries_helper_patch.rb
-rw-r--r-- 1 root root  762 Dec 12 18:08 rich_file_patch.rb
-rw-r--r-- 1 root root  980 Dec 12 18:08 rich_files_controller_patch.rb
-rw-r--r-- 1 root root  633 Dec 12 18:08 rich_files_helper_patch.rb
-rw-r--r-- 1 root root  228 Dec 12 18:08 tempfile_patch.rb
drwxr-xr-x 2 root root 4096 Dec 12 18:08 wiki_formatting

Thanks for help!

**Comment by a-ono** [comment]
Version 1.0.20 is not compatible Redmine 3.x.
You should use 1.1.4.
