### ISSUE TITLE
JS hassle on redmine 3.3.2 stable and ckeditor 1.1.4

### ISSUE THREAD

**Issue by rocksit** [a-ono/redmine_ckeditor#239]
Hello a-ono,

thank you first for your great plugin, but sadly I cant get it working.
I run a plain redmine 3.3.2 stable install from git on debian 8, everything 
wars installed like recommended by you. bundler gets all required stuff,
rake install your plugin without errors. Apache reload is done.

But when I change default editor to ckeditor, it seems like some java
script could not be loaded as it should and my editor field stays invisible.
I use Firefox 45 on linux with default user agent, it seems to me like this
is in some ways related to this issue.

I took some screen shots documenting my situation. You can see redmine
config panel and you see FF debuger error in one of your js files loading.
As you can see, editor could not be loaded. I atached my system config,
too.

Would be very glad to get a hint what is going wrong ! CKeditor is a great
peace of software ! Thanks !

regards,

Peter 

-------------------------------------------------
![ckeditor_js_error1](https://cloud.githubusercontent.com/assets/12859761/22824339/cf7089fe-ef87-11e6-8f07-632d63c9ae9a.jpg)
-------------------------------------------------
![ckeditor_js_error2](https://cloud.githubusercontent.com/assets/12859761/22824340/cf84e462-ef87-11e6-8033-4c74dbb3214d.jpg)
-------------------------------------------------
![ckeditor_js_error3](https://cloud.githubusercontent.com/assets/12859761/22824341/cf8670de-ef87-11e6-9a43-4db03b451375.jpg)
-------------------------------------------------
![ckeditor_js_error4](https://cloud.githubusercontent.com/assets/12859761/22824342/cf9a1224-ef87-11e6-89b3-667ae758291e.jpg)
-------------------------------------------------
![ckeditor_js_error5](https://cloud.githubusercontent.com/assets/12859761/22824343/cfa0e5e0-ef87-11e6-9a7f-b1faf93c1067.jpg)
-------------------------------------------------
![ckeditor_js_error6](https://cloud.githubusercontent.com/assets/12859761/22824323/bca94b26-ef87-11e6-9391-2982aecd0db9.jpg)

**Comment by a-ono** [comment]
Are there `REDMINE_ROOT/public/plugin_assets/redmine_ckeditor` directory and `editor_gecko.css`?

**Comment by rocksit** [comment]
Hello a-ono!
Thank you, with your help I was able to figure out what is going wrong. Sadly my ruby skills are so poor, I can not decide if it is an installation error in my apache + redmine config or some sort of thing your plugin should take care about. But I'm sure you can ;) 

I find that your code is loading some css stuff dynamically and find that it try to get a file at wrong location:

`https://plugin_assets/redmine_ckeditor/ckeditor/skins/moono/editor_gecko.css?t=G6DE`

Because there is a missing host part in URL this wont go fine. I suppose, problem is a additional /
before root url part so that my browser reads it as absolute path.

What I did to fix it, was to patch file 

`./plugins/redmine_ckeditor/lib/redmine_ckeditor/application_helper_patch.rb`

and replace line
`   
#root = RedmineCkeditor.assets_root

with

root = "/plugin_assets/redmine_ckeditor" 
`
This way everything is loading just fine :-)

But I'm not sure this error is due to wrong configured document root
or a problem of your plugin. So here is my config, please decide:

Here is relevant part of my apache config
`  SetEnv RAILS_RELATIVE_URL_ROOT "/"
   # apache2 serves public files
    Alias "/" /opt/redmine/redmine-live/public/
    <Location />
        PassengerBaseURI /
        PassengerAppRoot /opt/redmine/redmine-live/
    </Location>`

Here is a list of my gems with versions:

`Using rake 12.0.0
Using i18n 0.8.0
Using json 1.8.6
Using minitest 5.10.1
Using thread_safe 0.3.5
Using builder 3.2.3
Using erubis 2.7.0
Using mini_portile2 2.1.0
Using rack 1.6.5
Using mime-types-data 3.2016.0521
Using arel 6.0.4
Using public_suffix 2.0.5
Using bundler 1.14.3
Using climate_control 0.1.0
Using coderay 1.1.1
Using concurrent-ruby 1.0.4
Using uuidtools 2.1.5
Using tilt 2.0.6
Using sexp_processor 4.8.0
Using thor 0.19.4
Using htmlentities 4.3.1
Using kaminari-core 1.0.1
Using mimemagic 0.3.2
Using multi_json 1.12.1
Using mysql2 0.3.21
Using net-ldap 0.12.1
Using pandoc-ruby 2.0.1
Using ruby-openid 2.3.0
Using rbpdf-font 1.19.0
Using redcarpet 3.3.4
Using request_store 1.0.5
Using require_patch 0.1.0
Using sass 3.4.23
Using rmagick 2.16.0
Using rubyzip 1.2.1
Using xapian-full-alaveteli 1.2.21.1
Using tzinfo 1.2.2
Using nokogiri 1.7.0.1
Using rack-test 0.6.3
Using mime-types 3.1
Using addressable 2.5.0
Using cocaine 0.5.8
Using sprockets 3.7.1
Using haml 4.0.7
Using ruby_parser 3.8.4
Using rack-raw-upload 1.1.1
Using rack-openid 1.4.2
Using rbpdf 1.19.0
Using zip-zip 0.3
Using activesupport 4.2.7.1
Using loofah 2.0.3
Using dav4rack 0.3.0
Using mail 2.6.4
Using css_parser 1.4.8
Using html2haml 2.1.0
Using rails-deprecated_sanitizer 1.0.3
Using globalid 0.3.7
Using activemodel 4.2.7.1
Using simple_enum 2.3.0
Using rails-html-sanitizer 1.0.3
Using roadie 3.2.1
Using rails-dom-testing 1.0.8
Using activejob 4.2.7.1
Using activerecord 4.2.7.1
Using paperclip 4.2.4
Using protected_attributes 1.1.3
Using actionview 4.2.7.1
Using kaminari-activerecord 1.0.1
Using actionpack 4.2.7.1
Using kaminari-actionview 1.0.1
Using actionmailer 4.2.7.1
Using actionpack-action_caching 1.2.0
Using actionpack-xml_parser 1.0.2
Using railties 4.2.7.1
Using sprockets-rails 3.2.0
Using kaminari 1.0.1
Using haml-rails 0.9.0
Using jquery-rails 3.1.4
Using jquery-ui-rails 6.0.1
Using roadie-rails 1.1.1
Using rails 4.2.7.1
Using sass-rails 5.0.6
Using redmine_extensions 0.1.17
Using rich 1.4.8 from https://github.com/a-ono/rich.git (at master@93d1dd9
`

Here is html code generated by not fixed plugin for not working textarea of administration->configuration shown in figure in previous post.

`<p><label for="settings_welcome_text">Willkommenstext</label><textarea name="settings[welcome_text]" id="settings_welcome_text" cols="60" rows="5" class="wiki-edit">
</textarea></p>
<script>
//<![CDATA[
CKEDITOR_BASEPATH = '//plugin_assets/redmine_ckeditor/ckeditor/';
//]]>
</script><script src="/plugin_assets/redmine_ckeditor/javascripts/application.js"></script><script>
//<![CDATA[
CKEDITOR.plugins.addExternal('redmine', '//plugin_assets/redmine_ckeditor/ckeditor-contrib/plugins/redmine//');
CKEDITOR.plugins.addExternal('mediaembed', '//plugin_assets/redmine_ckeditor/ckeditor-contrib/plugins/mediaembed//');
CKEDITOR.plugins.addExternal('codemirror', '//plugin_assets/redmine_ckeditor/ckeditor-contrib/plugins/codemirror//');
CKEDITOR.plugins.addExternal('richfile', '//plugin_assets/redmine_ckeditor/ckeditor-contrib/plugins/richfile//');
//]]>
</script><link rel="stylesheet" media="screen" href="/plugin_assets/redmine_ckeditor/stylesheets/editor.css" /><script>
//<![CDATA[
        function showAndScrollTo(id, focus) {
          var elem = $("#" + id);
          elem.show();
          if (focus != null && CKEDITOR.instances.hasOwnProperty(focus)) { CKEDITOR.instances[focus].focus(); }
          $('html, body').animate({scrollTop: elem.offset().top}, 100);
        }

        function destroyEditor(id) {
          if (CKEDITOR.instances[id]) CKEDITOR.instances[id].destroy();
        }

//]]>
</script><script>
//<![CDATA[
      $(document).ready(function() {
              (function() {
        var id = 'settings_welcome_text';
        var textarea = document.getElementById(id);
        if (!textarea) return;

        var editor = CKEDITOR.replace(textarea, {"height":400,"extraPlugins":"redmine,mediaembed,codemirror,richfile","removePlugins":"div,flash,forms,iframe","contentsCss":["/stylesheets/application.css","//plugin_assets/redmine_ckeditor/stylesheets/editor.css"],"startupOutlineBlocks":true,"forcePasteAsPlainText":false,"toolbar":[["Source","ShowBlocks"],["Undo","Redo","-","Find","Replace"],["Bold","Italic","Underline","Strike","-","Subscript","Superscript","-","NumberedList","BulletedList","-","Outdent","Indent","Blockquote","-","JustifyLeft","JustifyCenter","JustifyRight","JustifyBlock","-","Link","Unlink","-","richImage","Table","HorizontalRule"],"/",["Styles","Format","Font","FontSize","-","TextColor","BGColor"]],"language":"de","richBrowserUrl":"//rich/files/","uiColor":"#f4f4f4","allowed_styles":["thumb","rich_thumb","original"],"default_style":"original","insert_many":false,"allow_document_uploads":true,"allow_embeds":true,"placeholder_image":"data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==","preview_size":"100px","hidden_input":false,"paginates_per":34,"scoped":false,"allowedContent":true,"bodyClass":"wiki","skin":"moono","enterMode":1,"shiftEnterMode":2,"toolbarCanCollapse":false,"toolbarStartupExpanded":true,"toolbarLocation":"top","width":null});
        editor.on("change", function() { textarea.value = editor.getSnapshot(); });
      })();

      });

//]]>
</script>`

**Comment by a-ono** [comment]
It's probably caused by this path.
```
CKEDITOR_BASEPATH = '//plugin_assets/redmine_ckeditor/ckeditor/';
```
The leading double slash (//) means protocol-relative URL.
http://plugin_assets/redmine_ckeditor/ckeditor/
or
https://plugin_assets/redmine_ckeditor/ckeditor/

Please remove below line from your apache config.
```
SetEnv RAILS_RELATIVE_URL_ROOT "/"
```
And you will get this result.
```
CKEDITOR_BASEPATH = '/plugin_assets/redmine_ckeditor/ckeditor/';
```

**Comment by rocksit** [comment]
Thank You a-ono!
This was my misconfiguration and now every thing works fine. I'm new in rails world, sorry for wasting your time.
