### ISSUE TITLE
Can't run redmine with redmine_ckeditor

### ISSUE THREAD

**Issue by zawadaa** [a-ono/redmine_ckeditor#245]
Hi,
When I try to log in to redmine I have an error:

> /usr/share/ruby/2.1/rubygems/defaults/operating_system.rb:85:in `home': couldn't find HOME environment -- expanding `~' (ArgumentError)
        from /usr/share/ruby/2.1/rubygems/defaults/operating_system.rb:85:in `default_bindir'
        from /usr/share/ruby/2.1/rubygems.rb:263:in `bindir'
        from /usr/share/ruby/vendor_ruby/bundler/rubygems_integration.rb:85:in `gem_bindir'
        from /usr/share/ruby/vendor_ruby/bundler.rb:262:in `system_bindir'
        from /usr/share/ruby/vendor_ruby/bundler.rb:279:in `requires_sudo?'
        from /usr/share/ruby/vendor_ruby/bundler/source/git.rb:199:in `cache_path'
        from /usr/share/ruby/vendor_ruby/bundler/source/git.rb:284:in `git_proxy'
        from /usr/share/ruby/vendor_ruby/bundler/source/git.rb:212:in `revision'
        from /usr/share/ruby/vendor_ruby/bundler/source/git.rb:81:in `install_path'
        from /usr/share/ruby/vendor_ruby/bundler/source/path.rb:126:in `load_spec_files'
        from /usr/share/ruby/vendor_ruby/bundler/source/git.rb:185:in `load_spec_files'
        from /usr/share/ruby/vendor_ruby/bundler/source/path.rb:92:in `local_specs'
        from /usr/share/ruby/vendor_ruby/bundler/source/git.rb:155:in `specs'
        from /usr/share/ruby/vendor_ruby/bundler/lazy_specification.rb:53:in `__materialize__'
        from /usr/share/ruby/vendor_ruby/bundler/spec_set.rb:88:in `block in materialize'
        from /usr/share/ruby/vendor_ruby/bundler/spec_set.rb:85:in `map!'
        from /usr/share/ruby/vendor_ruby/bundler/spec_set.rb:85:in `materialize'
        from /usr/share/ruby/vendor_ruby/bundler/definition.rb:132:in `specs'
        from /usr/share/ruby/vendor_ruby/bundler/definition.rb:177:in `specs_for'
        from /usr/share/ruby/vendor_ruby/bundler/definition.rb:166:in `requested_specs'
        from /usr/share/ruby/vendor_ruby/bundler/environment.rb:18:in `requested_specs'
        from /usr/share/ruby/vendor_ruby/bundler/runtime.rb:13:in `setup'
        from /usr/share/ruby/vendor_ruby/bundler.rb:122:in `setup'
        from /usr/share/ruby/vendor_ruby/bundler/setup.rb:17:in `<top (required)>'
        from /usr/share/redmine/config/boot.rb:4:in `require'
        from /usr/share/redmine/config/boot.rb:4:in `<top (required)>'
        from /usr/share/redmine/public/dispatch.fcgi:3:in `require'
        from /usr/share/redmine/public/dispatch.fcgi:3:in `<main>'

Without this plugin redmine works.
redmine = 3.3.3
redmine_ckeditor = master

Something wrong with my environment?

**Comment by a-ono** [comment]
It doesn't seem to be a this plugin's problem.
You should set HOME environment variable.
