### ISSUE TITLE
Any plan on upgrading to CKEditor 4.6?

### ISSUE THREAD

**Issue by bartroff** [a-ono/redmine_ckeditor#246]
Hi there,

Thanks for a great plugin. 

Is there any plans on upgrading to CKEditor 4.6 anytime soon?

Regards - Allan

**Comment by gabriel-cardoso** [comment]
Hi, 

Did you try to follow these instructions ? 

https://github.com/a-ono/redmine_ckeditor#upgrading-ckeditor-for-development

**Comment by bartroff** [comment]
Yes, and that works - thanks
