### ISSUE TITLE
Current Support Redmine Version

### ISSUE THREAD

**Issue by hanbroz** [a-ono/redmine_ckeditor#247]
Does it support 3.3.3-0 (64-bit) versions?

Bundle install --without development test --no-deployment 

causes an error if you add *--no-deployment*.

**Comment by cuoilennaocacban** [comment]
working fine on 32 bit version of redmin 3.3.3

**Comment by a-ono** [comment]
Yes, did you execute `bundle install --deployment` before?
http://bundler.io/man/bundle-install.1.html#DEPLOYMENT-MODE
