### ISSUE TITLE
Is redmine_ckeditor compatible with Redmine 3.4.2

### ISSUE THREAD

**Issue by markwintch** [a-ono/redmine_ckeditor#251]
I am planning to upgrade to the latest version, but do not want to lose this plugin.  I know that 3.4.0 introduced some wiki enhancements, so I am curious if this should be compatible.  I apologize if this has been answered somewhere else, I was not able to find the answer any other place.

I plan on using Ruby 2.4.1 x64 and SQL 2016

**Comment by rompic** [comment]
Would love to know that too.

**Comment by rompic** [comment]
In the meantime I saw that there have been some fixes for 3.4.x in the latest release.
https://github.com/a-ono/redmine_ckeditor/commit/8559d7ab81bb66acd7978979cdc068fec743cb2b

However, would still be great to get an update concerning compatibility.

**Comment by a-ono** [comment]
It should work.
