### ISSUE TITLE
Doesn't protect against leaving a page with unsaved text

### ISSUE THREAD

**Issue by dougg3** [a-ono/redmine_ckeditor#254]
Redmine provides protection against closing a window/tab with unsaved changes to an issue/wiki/etc. If I type something into the text editor and then try to close the tab, reload, or click a link, the browser will force me to confirm that I want to leave the page. In fact, the "My account" page in Redmine has a checkbox "Warn me when leaving a page with unsaved text" that allows me to turn this feature on and off.

Unfortunately, when this plugin is enabled, that protection goes away and I lose all of my changes immediately regardless of the checkbox setting. What would it take to re-add this protection?

**Comment by dougg3** [comment]
It's possible to hack stock Redmine's public/javascripts/application.js file to fix this issue by modifying the window.onbeforeunload function (set up in warnLeavingUnsaved()) to poll the CKEDITOR instances by calling checkDirty() and seeing if any of them return true. Here is my sample hacked version of warnLeavingUnsaved from Redmine 3.3.1:

```javascript
function warnLeavingUnsaved(message) {
  warnLeavingUnsavedMessage = message;
  $(document).on('submit', 'form', function(){
    $('textarea').removeData('changed');
  });
  $(document).on('change', 'textarea', function(){
    $(this).data('changed', 'changed');
  });
  window.onbeforeunload = function(){
    var warn = false;
    $('textarea').blur().each(function(){
      if ($(this).data('changed')) {
        warn = true;
      }
    });
    /* BEGIN HACK BY DOUG FOR REDMINE CKEDITOR */
    if (typeof CKEDITOR !== 'undefined') {
        for (editorName in CKEDITOR.instances) {
            if (CKEDITOR.instances[editorName].checkDirty()) {
                warn = true;
            }
        }
    }
    /* END HACK BY DOUG FOR REDMINE CKEDITOR */
    if (warn) {return warnLeavingUnsavedMessage;}
  };
}
```

I'm not sure how to do this hack in a clean way inside the plugin, but it does seem to restore the functionality.

**Comment by a-ono** [comment]
#281 has been merged.
