### ISSUE TITLE
"The git source https://github.com/a-ono/rich.git is not yet checked out." error

### ISSUE THREAD

**Issue by oivanenko** [a-ono/redmine_ckeditor#270]
Hi!

I have installed and successfully working Bitnami Redmine 3.4.4 on Windows Server 2008 R2 Standard

I had tried to install redmine_ckeditor following "Plugin installation and setup":
1. Copy content of downloaded "redmine_ckeditor-master.zip" file to "C:\Bitnami\redmine-3.4.4-2\apps\redmine\htdocs\plugins" directory
2. Rename "redmine_ckeditor-master" directory to "redmine_ckeditor"
3. Launch "Use BitNami Redmine Stack" command window with "Run as administrator" and execute next commands:

C:\Bitnami\redmine-3.4.4-2>cd C:\Bitnami\redmine-3.4.4-2\apps\redmine\htdocs

C:\Bitnami\redmine-3.4.4-2\apps\redmine\htdocs>bundle install --without development test
You are trying to install in deployment mode after changing
your Gemfile. Run `bundle install` elsewhere and add the
updated Gemfile.lock to version control.

If this is a development machine, remove the Gemfile freeze
by running `bundle install --no-deployment`.

You have added to the Gemfile:
* source: https://github.com/a-ono/rich.git (at master)
* rich
* kaminari
* htmlentities
* paperclip (~> 4.2.1)
* pandoc-ruby

C:\Bitnami\redmine-3.4.4-2\apps\redmine\htdocs>rake redmine:plugins:migrate RAIL
S_ENV=production
The git source https://github.com/a-ono/rich.git is not yet checked out. Please run `bundle install` before trying to start your application

C:\Bitnami\redmine-3.4.4-2\apps\redmine\htdocs>

After that Redmine can't start.

I had tried to uninstall ckeditor following Uninstall guide:

C:\Bitnami\redmine-3.4.4-2\apps\redmine\htdocs>rake redmine:plugins:migrate  NAME=redmine_ckeditor VERSION=0 RAILS_ENV=production
The git source https://github.com/a-ono/rich.git is not yet checked out. Please run `bundle install` before trying to start your application

After that Redmine still can't starting.

Can you please help me? What kind of information I can provide you to fix this issue? Please, note that I can successfully fetch git repository mentioned above with "git clone https://github.com/a-ono/rich.git" command.

**Comment by dougti** [comment]
Same issue here

**Comment by a-ono** [comment]
Please try version 1.1.7 or 1.2.0.
