### ISSUE TITLE
Can't install CKEditor 1.1.5 to REdmine 3.4.4

### ISSUE THREAD

**Issue by RomanovSergei** [a-ono/redmine_ckeditor#271]
Hello, i can't install CKEditor 1.1.5 to REdmine 3.4.4.

### System

CentOS 7

ruby -v
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]

rails -v
Rails 4.2.8

Environment:
  Redmine version                3.4.4.stable
  Ruby version                   2.4.0-p0 (2016-12-24) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.7.14
  Git                            1.8.3.1
  Filesystem                     
Redmine plugins:
  a_common_libs                  2.4.3
  global_roles                   2.2.1
  luxury_buttons                 4.0.2
  redmine_issue_tabs             1.3.0
  redmine_logs                   0.1.1
  redmine_sender                 1.4.2
  rm_user_mentions               1.0.2
  unread_issues                  2.2.1
  usability                      2.3.2

LOGS

### Download

# git clone https://github.com/a-ono/redmine_ckeditor.git
Cloning into 'redmine_ckeditor'...
remote: Counting objects: 7123, done.
remote: Total 7123 (delta 0), reused 0 (delta 0), pack-reused 7123
Receiving objects: 100% (7123/7123), 9.11 MiB | 757.00 KiB/s, done.
Resolving deltas: 100% (3511/3511), done.

### Gems
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users on this machine.
Fetching https://github.com/a-ono/rich.git
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32 x86-mswin32`.
/opt/rh/rh-ruby24/root/usr/share/gems/gems/psych-2.2.2/lib/psych.rb:228: warning: already initialized constant Psych::LIBYAML_VERSION
/opt/rh/rh-ruby24/root/usr/share/ruby/psych.rb:228: warning: previous definition of LIBYAML_VERSION was here
/opt/rh/rh-ruby24/root/usr/share/gems/gems/psych-2.2.2/lib/psych.rb:230: warning: already initialized constant Psych::FALLBACK
/opt/rh/rh-ruby24/root/usr/share/ruby/psych.rb:230: warning: previous definition of FALLBACK was here
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using rake 12.3.0
Using i18n 0.7.0
Using minitest 5.11.3
Using thread_safe 0.3.6
Using tzinfo 1.2.5
Using activesupport 4.2.8
Using builder 3.2.3
Using erubis 2.7.0
Using mini_portile2 2.3.0
Using nokogiri 1.8.2
Using rails-deprecated_sanitizer 1.0.3
Using rails-dom-testing 1.0.9
Using crass 1.0.3
Using loofah 2.2.0
Using rails-html-sanitizer 1.0.3
Using actionview 4.2.8
Using rack 1.6.9
Using rack-test 0.6.3
Using actionpack 4.2.8
Using globalid 0.4.1
Using activejob 4.2.8
Using mime-types-data 3.2016.0521
Using mime-types 3.1
Using mail 2.6.6
Using actionmailer 4.2.8
Using actionpack-xml_parser 1.0.2
Using activemodel 4.2.8
Using arel 6.0.4
Using activerecord 4.2.8
Using multi_json 1.13.1
Using thor 0.20.0
Using railties 4.2.8
Using activerecord-session_store 1.1.0
Using public_suffix 3.0.2
Using addressable 2.5.2
Using bundler 1.16.1
Fetching climate_control 0.2.0
Installing climate_control 0.2.0
Fetching cocaine 0.5.8
Installing cocaine 0.5.8
Using coderay 1.1.2
Using concurrent-ruby 1.0.5
Using css_parser 1.6.0
Fetching ffi 1.9.23
Installing ffi 1.9.23 with native extensions
Using htmlentities 4.3.4
Using jquery-rails 3.1.4
Fetching kaminari-core 1.1.1
Installing kaminari-core 1.1.1
Fetching kaminari-actionview 1.1.1
Installing kaminari-actionview 1.1.1
Fetching kaminari-activerecord 1.1.1
Installing kaminari-activerecord 1.1.1
Fetching kaminari 1.1.1
Installing kaminari 1.1.1
Using mimemagic 0.3.2
Using mysql2 0.4.10
Using net-ldap 0.12.1
Fetching pandoc-ruby 2.0.2
Installing pandoc-ruby 2.0.2
Fetching paperclip 4.2.4
Installing paperclip 4.2.4
Using protected_attributes 1.1.4
Using ruby-openid 2.3.0
Using rack-openid 1.4.2
Fetching rack-raw-upload 1.1.1
Installing rack-raw-upload 1.1.1
Using sprockets 3.7.1
Using sprockets-rails 3.2.1
Using rails 4.2.8
Fetching rb-fsevent 0.10.3
Installing rb-fsevent 0.10.3
Fetching rb-inotify 0.9.10
Installing rb-inotify 0.9.10
Using rbpdf-font 1.19.1
Using rbpdf 1.19.3
Using redcarpet 3.4.0
Using request_store 1.0.5
Fetching sass-listen 4.0.0
Installing sass-listen 4.0.0
Fetching sass 3.5.5
Installing sass 3.5.5
Fetching tilt 2.0.8
Installing tilt 2.0.8
Fetching sass-rails 5.0.7
Installing sass-rails 5.0.7
Using rich 1.4.8 from https://github.com/a-ono/rich.git (at master@93d1dd9)
Using rmagick 2.16.0
Using roadie 3.2.2
Using roadie-rails 1.1.1
Using rubyzip 1.2.1
Using xmpp4r 0.5.6
Bundle complete! 39 Gemfile dependencies, 76 gems now installed.
Gems in the groups development, test, postgresql and sqlite were not installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

### Migration

(in /var/www/redmine)
Migrating a_common_libs (A common libraries)...
Migrating global_roles (Global Roles plugin)...
Migrating luxury_buttons (Luxury Buttons plugin)...
Migrating redmine_ckeditor (Redmine CKEditor plugin)...
== 20130418001207 CreateRichRichImages: migrating =============================
-- create_table(:rich_rich_images)
   -> 0.3198s
== 20130418001207 CreateRichRichImages: migrated (0.3202s) ====================

== 20130418001208 AddUriCacheToRichImage: migrating ===========================
-- add_column(:rich_rich_images, :uri_cache, :text)
   -> 0.0662s
== 20130418001208 AddUriCacheToRichImage: migrated (0.0663s) ==================

== 20130418001209 RefactorImageToFile: migrating ==============================
-- rename_table(:rich_rich_images, :rich_rich_files)
   -> 0.0083s
-- rename_column(:rich_rich_files, :image_file_name, :rich_file_file_name)
   -> 0.0766s
-- rename_column(:rich_rich_files, :image_content_type, :rich_file_content_type)
   -> 0.0818s
-- rename_column(:rich_rich_files, :image_file_size, :rich_file_file_size)
   -> 0.0579s
-- rename_column(:rich_rich_files, :image_updated_at, :rich_file_updated_at)
   -> 0.0770s
-- add_column(:rich_rich_files, :simplified_type, :string, {:default=>"file"})
   -> 0.0728s
== 20130418001209 RefactorImageToFile: migrated (0.3752s) =====================

Migrating redmine_issue_tabs (Redmine Issue Tabs plugin)...
Migrating redmine_logs (Redmine Logs plugin)...
Migrating redmine_sender (Redmine Sender)...
Migrating rm_user_mentions (Redmine User Mentions plugin)...
Migrating unread_issues (Unread Issues plugin)...
Migrating usability (Usability plugin)...

### HTTPD log

App 4906 stdout: 
App 4906 stdout: 
[ E 2018-03-14 15:54:49.2737 4822/Th age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /var/www/redmine: An error occurred while starting up the preloader.
  Error ID: 676a6070
  Error details saved to: /tmp/passenger-error-seOtDK.html
  Message from application: <p>It looks like Bundler could not find a gem. Maybe you didn't install all the gems that this application needs. To install your gems, please run:</p>

  <pre class="commands">bundle install</pre>

<p>If that didn't work, then the problem is probably caused by your application being run under a different environment than it's supposed to. Please check the following:</p>

<ol>
  <li>Is this app supposed to be run as the <code>apache</code> user?</li>
  <li>Is this app being run on the correct Ruby interpreter? Below you will
      see which Ruby interpreter Phusion Passenger attempted to use.</li>
</ol>

<p>-------- The exception is as follows: -------</p>
https://github.com/a-ono/rich.git (at master@93d1dd9) is not yet checked out. Run `bundle install` first. (Bundler::GitError)
<pre>  /opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.16.1/lib/bundler/source/git.rb:202:in `rescue in load_spec_files&#39;
  /opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.16.1/lib/bundler/source/git.rb:199:in `load_spec_files&#39;
  /opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.16.1/lib/bundler/source/path.rb:100:in `local_specs&#39;
  /opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.16.1/lib/bundler/source/git.rb:166:in `specs&#39;
  /opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.16.1/lib/bundler/lazy_specification.rb:76:in `__materialize__&#39;
  /opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.16.1/lib/bundler/spec_set.rb:85:in `block in materialize&#39;
  /opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.16.1/lib/bundler/spec_set.rb:82:in `map!&#39;
  /opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.16.1/lib/bundler/spec_set.rb:82:in `materialize&#39;
  /opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.16.1/lib/bundler/definition.rb:170:in `specs&#39;
  /opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.16.1/lib/bundler/definition.rb:237:in `specs_for&#39;
  /opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.16.1/lib/bundler/definition.rb:226:in `requested_specs&#39;
  /opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.16.1/lib/bundler/runtime.rb:108:in `block in definition_method&#39;
  /opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.16.1/lib/bundler/runtime.rb:20:in `setup&#39;
  /opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.16.1/lib/bundler.rb:107:in `setup&#39;
  /opt/rh/rh-ruby24/root/usr/local/share/gems/gems/bundler-1.16.1/lib/bundler/setup.rb:20:in `&lt;top (required)&gt;&#39;
  /opt/rh/rh-ruby24/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require&#39;
  /opt/rh/rh-ruby24/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require&#39;
  /opt/rh/rh-ruby24/root/usr/local/share/gems/gems/passenger-5.2.1/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:456:in `activate_gem&#39;
  /opt/rh/rh-ruby24/root/usr/local/share/gems/gems/passenger-5.2.1/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:323:in `block in run_load_path_setup_code&#39;
  /opt/rh/rh-ruby24/root/usr/local/share/gems/gems/passenger-5.2.1/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:461:in `running_bundler&#39;
  /opt/rh/rh-ruby24/root/usr/local/share/gems/gems/passenger-5.2.1/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:322:in `run_load_path_setup_code&#39;
  /opt/rh/rh-ruby24/root/usr/local/share/gems/gems/passenger-5.2.1/src/helper-scripts/rack-preloader.rb:100:in `preload_app&#39;
  /opt/rh/rh-ruby24/root/usr/local/share/gems/gems/passenger-5.2.1/src/helper-scripts/rack-preloader.rb:156:in `&lt;module:App&gt;&#39;
  /opt/rh/rh-ruby24/root/usr/local/share/gems/gems/passenger-5.2.1/src/helper-scripts/rack-preloader.rb:30:in `&lt;module:PhusionPassenger&gt;&#39;
  /opt/rh/rh-ruby24/root/usr/local/share/gems/gems/passenger-5.2.1/src/helper-scripts/rack-preloader.rb:29:in `&lt;main&gt;&#39;</pre>

[ E 2018-03-14 15:54:49.2794 4822/T9 age/Cor/Con/CheckoutSession.cpp:285 ]: [Client 2-1] Cannot checkout session because a spawning error occurred. The identifier of the error is 676a6070. Please see earlier logs for details about the error.

### Production Logs 

Migrating to CreateRichRichImages (20130418001207)
DEPRECATION WARNING: `#timestamps` was called without specifying an option for `null`. In Rails 5, this behavior will change to `null: false`. You should manually specify `null: true` to prevent the behavior of your existing migrations from changing. (called from block in change at /var/www/redmine/plugins/redmine_ckeditor/db/migrate/20130418001207_create_rich_rich_images.rich.rb:6)
Migrating to AddUriCacheToRichImage (20130418001208)
Migrating to RefactorImageToFile (20130418001209)

### Redmine

We're sorry, but something went wrong.

The issue has been logged for investigation. Please try again later.
Technical details for the administrator of this website
Error:
Web application could not be started
Error ID:
90262281
Details:

Web application could not be started by the Phusion Passenger application server.

Please read the Passenger log file (search for the Error ID) to find the details of the error.

You can also get a detailed report to appear directly on this page, but for security reasons it is only provided if Phusion Passenger is run with environment set to development and/or with the friendly error pages option set to on.

For more information about configuring environment and friendly error pages, see:

**Comment by josvo** [comment]
I had the same problem. This link https://stackoverflow.com/questions/6648870/is-not-checked-out-bundle-install-does-not-fix-help worked for me.
However, that is no permanent solution, but I hope this will help others too until a fix is available.

**Comment by LuisSerrano** [comment]
Any new about this bug?

**Comment by LuisSerrano** [comment]
The same problem with the redmine version 3.4.5.

**Comment by adrianobr** [comment]
I have succeeded in installing the redmine container 3.4.5 many other plugins and also Ckeditor 1.1.5.
I use docker for redmine. Inside the docker I first update the operating system and then install some things. Follow the steps.

echo "Upgrade / Upgrade from OS"
apt-get update && sudo apt-get upgrade
echo "Installing Build-Essential"
apt-get install build-essential
echo "Installing libstdc ++ 6"
apt-get install libstdc ++ 6
echo "Updating Locales"
apt-get purge locales
apt-get install locales
dpkg-reconfigure locales
echo "Setting Date and Time"
dpkg-reconfigure tzdata
echo "Installing VI"
apt-get install vim


--bundle install--
bundle install --without development test
--executing migrations from all plugins--
bundle exec rake redmine: plugins: migrate RAILS_ENV = production
--restart--
touch tmp / restart.txt

adrianojosebaptistella@gmail.com

**Comment by a-ono** [comment]
Please try version 1.1.7 or 1.2.0.
