### ISSUE TITLE
Errno::EACCES (Permission denied @ dir_s_mkdir

### ISSUE THREAD

**Issue by ricardojohnny** [a-ono/redmine_ckeditor#279]
We need a solution regarding this error, it simply does not upload the image and generates this error in the log:

Started POST "/rich/files?authenticity_token=36jOboxkbZP2PhK9UbDJ6ZwuvbQdrFpn45vOnK%2FVjAa2bUkIXAsVY5x61Ss9f8GQXDcWVQqvJauiM2eot6B0Eg%3D%3D&simplified_type=image&scoped=true&scope_type=Project&scope_id=196&qqfile=race-to-the-cloud-1920-0d9230cd32.png" for 127.0.0.1 at 2018-07-18 13:15:04 +0000
Processing by Rich::FilesController#create as */*
  Parameters: {"file"=>#<ActionDispatch::Http::UploadedFile:0x0000000011b34cd0 @tempfile=#<Tempfile:/tmp/raw-upload.20180718-233-1w14rxs>, @original_filename="race-to-the-cloud-1920-0d9230cd32.png", @content_type="application/octet-stream", @headers=nil>, "authenticity_token"=>"36jOboxkbZP2PhK9UbDJ6ZwuvbQdrFpn45vOnK/VjAa2bUkIXAsVY5x61Ss9f8GQXDcWVQqvJauiM2eot6B0Eg==", "simplified_type"=>"image", "scoped"=>"true", "scope_type"=>"Project", "scope_id"=>"196", "qqfile"=>"race-to-the-cloud-1920-0d9230cd32.png"}
  Current user: ricardo.jesus (id=195)
Command :: identify -format '%wx%h,%[exif:orientation]' '/tmp/53ad0cbba798467e5606bc760fb64a7220180718-233-1gz39zj.png[0]' 2>/dev/null
Command :: identify -format %m '/tmp/53ad0cbba798467e5606bc760fb64a7220180718-233-1gz39zj.png[0]'
Command :: convert '/tmp/53ad0cbba798467e5606bc760fb64a7220180718-233-1gz39zj.png[0]' -auto-orient -resize "x100" -crop "100x100+38+0" +repage '/tmp/53ad0cbba798467e5606bc760fb64a7220180718-233-1gz39zj20180718-233-1c0cu9p'
Command :: file -b --mime '/tmp/53ad0cbba798467e5606bc760fb64a7220180718-233-1gz39zj20180718-233-1c0cu9p'
Command :: identify -format '%wx%h,%[exif:orientation]' '/tmp/53ad0cbba798467e5606bc760fb64a7220180718-233-1gz39zj.png[0]' 2>/dev/null
Command :: identify -format %m '/tmp/53ad0cbba798467e5606bc760fb64a7220180718-233-1gz39zj.png[0]'
Command :: convert '/tmp/53ad0cbba798467e5606bc760fb64a7220180718-233-1gz39zj.png[0]' -auto-orient -resize "x100" -crop "100x100+38+0" +repage '/tmp/53ad0cbba798467e5606bc760fb64a7220180718-233-1gz39zj20180718-233-rqxa4t'
Command :: file -b --mime '/tmp/53ad0cbba798467e5606bc760fb64a7220180718-233-1gz39zj20180718-233-rqxa4t'
Completed 500 Internal Server Error in 536ms (ActiveRecord: 7.0ms)

Errno::EACCES (Permission denied @ dir_s_mkdir - /home/redmine/redmine/public/system/rich/rich_files/rich_files/000/001/747):
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by a-ono** [comment]
You must have write permission on redmine/public/system.
https://github.com/a-ono/redmine_ckeditor/issues/70#issuecomment-24371501
