### ISSUE TITLE
Not working in futur version of Redmine 4.x

### ISSUE THREAD

**Issue by abrochet** [a-ono/redmine_ckeditor#283]
Hello,

The plugin is not compatible with the new version of Redmine 4.0 Rails 5.2 :(
The method "alias_method_chain" is missing in the new version of Rails 5.x
Obviously, it must be replaced by the method "prepend" but I do not know Ruby enough for that...

Is it possible to correct?

**Comment by a-ono** [comment]
Version 1.2.0 is compatible with Redmine 4.0.
