### ISSUE TITLE
CKEditor error in Redmine 4.x

### ISSUE THREAD

**Issue by HeeJoon-Kim** [a-ono/redmine_ckeditor#288]
I was installed ckeditor master branch at Redmine 4.0.0 stable.
How to solve this?
Thanks.

F, [2019-01-03T10:39:45.440124 #1] FATAL -- :   
F, [2019-01-03T10:39:45.440147 #1] FATAL -- : ActionView::Template::Error (undefined local variable or method `ckeditor_javascripts' for #<#<Class:0x000055e08d86baa0>:0x000055e08e664a30>):
F, [2019-01-03T10:39:45.440298 #1] FATAL -- :     1: <%= ckeditor_javascripts %>
    2: <%= stylesheet_link_tag 'editor', :plugin => 'redmine_ckeditor'%>
    3: <%= stylesheet_link_tag 'selector', :plugin => 'redmine_ckeditor'%>
    4: <p>
F, [2019-01-03T10:39:45.440327 #1] FATAL -- :   
F, [2019-01-03T10:39:45.440338 #1] FATAL -- : plugins/redmine_ckeditor/app/views/settings/_ckeditor.html.erb:1:in `_plugins_redmine_ckeditor_app_views_settings__ckeditor_html_erb___4215508978245412493_47211474934120'
app/views/settings/plugin.html.erb:6:in `block in _app_views_settings_plugin_html_erb__4010949002171704514_47211475053320'
app/views/settings/plugin.html.erb:4:in `_app_views_settings_plugin_html_erb__4010949002171704514_47211475053320'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'

Environment:
  Redmine version                4.0.0.stable
  Ruby version                   2.5.3-p105 (2018-10-18) [x86_64-linux]
  Rails version                  5.2.2
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.9.5
  Mercurial                      4.0
  Bazaar                         2.8.0
  Git                            2.11.0
  Filesystem                     
Redmine plugins:
  redmine_agile                  1.4.7
  redmine_checklists             3.1.13
  redmine_ckeditor               1.2.0b

**Comment by a-ono** [comment]
Please restart Redmine.

**Comment by aiorlov** [comment]
The same issue. Restarting Redmine does not help.

**Comment by davidgxxl** [comment]
Same issue... Is a shame this issue had been closed by the autor..!

**Comment by Cosmos-Web** [comment]
Hi, I looked at the edits [here](https://github.com/a-ono/redmine_ckeditor/commit/9ed00b9ca06a491320322717701123dd46065b06), I have them in the module, but the error remains.

```
redmine_v4 | I, [2019-01-21T12:30:03.430243 #1]  INFO -- : Completed 500 Internal Server Error in 164ms (ActiveRecord: 6.7ms)
redmine_v4 | F, [2019-01-21T12:30:03.431493 #1] FATAL -- :
redmine_v4 | F, [2019-01-21T12:30:03.431530 #1] FATAL -- : ActionView::Template::Error (undefined local variable or method `ckeditor_javascripts' for #<#<Class:0x000055626ce9f8d0>:0x00007f235d337a70>):
redmine_v4 | F, [2019-01-21T12:30:03.431697 #1] FATAL -- :     1: <%= ckeditor_javascripts %>
redmine_v4 |     2: <%= stylesheet_link_tag 'editor', :plugin => 'redmine_ckeditor'%>
redmine_v4 |     3: <%= stylesheet_link_tag 'selector', :plugin => 'redmine_ckeditor'%>
redmine_v4 |     4: <p>
redmine_v4 | F, [2019-01-21T12:30:03.431723 #1] FATAL -- :
redmine_v4 | F, [2019-01-21T12:30:03.431743 #1] FATAL -- : plugins/redmine_ckeditor/app/views/settings/_ckeditor.html.erb:1:in `_plugins_redmine_ckeditor_app_views_settings__ckeditor_html_erb__3575094037314653364_69894932142960'
redmine_v4 | app/views/settings/plugin.html.erb:6:in `block in _app_views_settings_plugin_html_erb___4026794961609383168_46940607234800'
```
