### ISSUE TITLE
 An error occurred while installing ffi (1.9.25)

### ISSUE THREAD

**Issue by Cosmos-Web** [a-ono/redmine_ckeditor#290]
Hello!
I use Redmine v4.0 in Docker.
When installing the plugin - I get the installation error ffi 1.9.25.

If you add a plugin to an already running container, then when running `bundle install --without development test`, the error is similar.

Log:

> redmine_v4_work | Fetching ffi 1.9.25
redmine_v4_work | Installing ffi 1.9.25 with native extensions
redmine_v4_work | Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
redmine_v4_work |
redmine_v4_work |     current directory: /usr/local/bundle/gems/ffi-1.9.25/ext/ffi_c
redmine_v4_work | /usr/local/bin/ruby -I /usr/local/lib/ruby/site_ruby/2.5.0 -r
redmine_v4_work | ./siteconf20190112-31-8oaae5.rb extconf.rb
redmine_v4_work | *** extconf.rb failed ***
redmine_v4_work | Could not create Makefile due to some reason, probably lack of necessary
redmine_v4_work | libraries and/or headers.  Check the mkmf.log file for more details.  You may
redmine_v4_work | need configuration options.
redmine_v4_work |
redmine_v4_work | Provided configuration options:
redmine_v4_work |       --with-opt-dir
redmine_v4_work |       --without-opt-dir
redmine_v4_work |       --with-opt-include
redmine_v4_work |       --without-opt-include=${opt-dir}/include
redmine_v4_work |       --with-opt-lib
redmine_v4_work |       --without-opt-lib=${opt-dir}/lib
redmine_v4_work |       --with-make-prog
redmine_v4_work |       --without-make-prog
redmine_v4_work |       --srcdir=.
redmine_v4_work |       --curdir
redmine_v4_work |       --ruby=/usr/local/bin/$(RUBY_BASE_NAME)
redmine_v4_work |       --with-ffi_c-dir
redmine_v4_work |       --without-ffi_c-dir
redmine_v4_work |       --with-ffi_c-include
redmine_v4_work |       --without-ffi_c-include=${ffi_c-dir}/include
redmine_v4_work |       --with-ffi_c-lib
redmine_v4_work |       --without-ffi_c-lib=${ffi_c-dir}/lib
redmine_v4_work |       --with-libffi-config
redmine_v4_work |       --without-libffi-config
redmine_v4_work |       --with-pkg-config
redmine_v4_work |       --without-pkg-config
redmine_v4_work | /usr/local/lib/ruby/2.5.0/mkmf.rb:456:in `try_do': The compiler failed to
redmine_v4_work | generate an executable file. (RuntimeError)
redmine_v4_work | You have to install development tools first.
redmine_v4_work |       from /usr/local/lib/ruby/2.5.0/mkmf.rb:541:in `try_link0'
redmine_v4_work |       from /usr/local/lib/ruby/2.5.0/mkmf.rb:559:in `try_link'
redmine_v4_work |       from /usr/local/lib/ruby/2.5.0/mkmf.rb:661:in `try_ldflags'
redmine_v4_work |       from /usr/local/lib/ruby/2.5.0/mkmf.rb:1821:in `pkg_config'
redmine_v4_work |       from extconf.rb:15:in `<main>'
redmine_v4_work |
redmine_v4_work | To see why this extension failed to compile, please check the mkmf.log which can
redmine_v4_work | be found here:
redmine_v4_work |
redmine_v4_work |   /usr/local/bundle/extensions/x86_64-linux/2.5.0/ffi-1.9.25/mkmf.log
redmine_v4_work |
redmine_v4_work | extconf failed, exit code 1
redmine_v4_work |
redmine_v4_work | Gem files will remain installed in /usr/local/bundle/gems/ffi-1.9.25 for
redmine_v4_work | inspection.
redmine_v4_work | Results logged to
redmine_v4_work | /usr/local/bundle/extensions/x86_64-linux/2.5.0/ffi-1.9.25/gem_make.out
redmine_v4_work |
redmine_v4_work | An error occurred while installing ffi (1.9.25), and Bundler cannot continue.
redmine_v4_work | Make sure that `gem install ffi -v '1.9.25' --source 'https://rubygems.org/'`
redmine_v4_work | succeeds before bundling.
redmine_v4_work |
redmine_v4_work | In Gemfile:
redmine_v4_work |   rich was resolved to 1.4.8, which depends on
redmine_v4_work |     sass-rails was resolved to 5.0.7, which depends on
redmine_v4_work |       sass was resolved to 3.7.3, which depends on
redmine_v4_work |         sass-listen was resolved to 4.0.0, which depends on
redmine_v4_work |           rb-inotify was resolved to 0.10.0, which depends on
redmine_v4_work |             ffi

**Comment by a-ono** [comment]
It has been fixed.
