### ISSUE TITLE
Ckeditor causes redmine to fail to start.

### ISSUE THREAD

**Issue by YoWenhow** [a-ono/redmine_ckeditor#298]
I recently upgraded from redmine-3.4.4 to redmine-4.0.3 and upgraded ckeditor to 1.2.1. After restarting apache, redmine cannot start normally.
The error log is as follows:
`[ E 2019-04-10 00:09:20.9705 11523/Te age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /opt/redmine: An error occurred while starting up the preloader.
  Error ID: 129d82a8
  Error details saved to: /tmp/passenger-error-kpD7SQ.html
  Message from application: uninitialized constant Generators::Base (NameError)
  /opt/redmine/plugins/redmine_ckeditor/lib/generators/redmine_ckeditor/rich_assets/rich_assets_generator.rb:4:in `<module:RedmineCkeditor>'
  /opt/redmine/plugins/redmine_ckeditor/lib/generators/redmine_ckeditor/rich_assets/rich_assets_generator.rb:3:in `<top (required)>'
  /usr/local/rvm/gems/ruby-2.6.2/gems/activesupport-5.2.2.1/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
  /usr/local/rvm/gems/ruby-2.6.2/gems/activesupport-5.2.2.1/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
  /usr/local/rvm/gems/ruby-2.6.2/gems/activesupport-5.2.2.1/lib/active_support/dependencies/interlock.rb:13:in `loading'
  /usr/local/rvm/gems/ruby-2.6.2/gems/railties-5.2.2.1/lib/rails/engine.rb:478:in `block (2 levels) in eager_load!'
  /usr/local/rvm/gems/ruby-2.6.2/gems/railties-5.2.2.1/lib/rails/engine.rb:477:in `each'
  /usr/local/rvm/gems/ruby-2.6.2/gems/railties-5.2.2.1/lib/rails/engine.rb:477:in `block in eager_load!'
  /usr/local/rvm/gems/ruby-2.6.2/gems/railties-5.2.2.1/lib/rails/engine.rb:475:in `each'
  /usr/local/rvm/gems/ruby-2.6.2/gems/railties-5.2.2.1/lib/rails/engine.rb:475:in `eager_load!'
  /usr/local/rvm/gems/ruby-2.6.2/gems/railties-5.2.2.1/lib/rails/engine.rb:356:in `eager_load!'
  /usr/local/rvm/gems/ruby-2.6.2/gems/railties-5.2.2.1/lib/rails/application/finisher.rb:69:in `each'
  /usr/local/rvm/gems/ruby-2.6.2/gems/railties-5.2.2.1/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
  /usr/local/rvm/gems/ruby-2.6.2/gems/railties-5.2.2.1/lib/rails/initializable.rb:32:in `instance_exec'
  /usr/local/rvm/gems/ruby-2.6.2/gems/railties-5.2.2.1/lib/rails/initializable.rb:32:in `run'
  /usr/local/rvm/gems/ruby-2.6.2/gems/railties-5.2.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
  /usr/local/rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
  /usr/local/rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /usr/local/rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /usr/local/rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /usr/local/rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/tsort.rb:347:in `each'
  /usr/local/rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/tsort.rb:347:in `call'
  /usr/local/rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
  /usr/local/rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
  /usr/local/rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
  /usr/local/rvm/gems/ruby-2.6.2/gems/railties-5.2.2.1/lib/rails/initializable.rb:60:in `run_initializers'
  /usr/local/rvm/gems/ruby-2.6.2/gems/railties-5.2.2.1/lib/rails/application.rb:361:in `initialize!'
  /opt/redmine/config/environment.rb:14:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /usr/local/rvm/gems/ruby-2.6.2/gems/rack-2.0.7/lib/rack/builder.rb:55:in `instance_eval'
  /usr/local/rvm/gems/ruby-2.6.2/gems/rack-2.0.7/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /usr/local/rvm/gems/ruby-2.6.2/gems/passenger-5.2.1/src/helper-scripts/rack-preloader.rb:110:in `eval'
  /usr/local/rvm/gems/ruby-2.6.2/gems/passenger-5.2.1/src/helper-scripts/rack-preloader.rb:110:in `preload_app'
  /usr/local/rvm/gems/ruby-2.6.2/gems/passenger-5.2.1/src/helper-scripts/rack-preloader.rb:156:in `<module:App>'
  /usr/local/rvm/gems/ruby-2.6.2/gems/passenger-5.2.1/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /usr/local/rvm/gems/ruby-2.6.2/gems/passenger-5.2.1/src/helper-scripts/rack-preloader.rb:29:in `<main>'

[ E 2019-04-10 00:09:20.9802 11523/T7 age/Cor/Con/CheckoutSession.cpp:285 ]: [Client 1-1] Cannot checkout session because a spawning error occurred. The identifier of the error is 129d82a8. Please see earlier logs for details about the error.
`
At first I thought the ruby environment was too old. When I upgraded from ruby 2.3.6 to ruby 2.6.2, the problem remained.

**Comment by elurex** [comment]
I can confirm ckeditor 1.2.1 works well with redmine 4.0.2.

However, once I updated to redmine 4.0.3, this plugin will fail to start.

**Comment by YoWenhow** [comment]
> I can confirm ckeditor 1.2.1 works well with redmine 4.0.2.
> 
> However, once I updated to redmine 4.0.3, this plugin will fail to start.

so sad

**Comment by clauded** [comment]
Here's the error generated when started with WEBrick:

`Exiting
/usr/share/redmine/plugins/redmine_ckeditor/lib/generators/redmine_ckeditor/rich_assets/rich_assets_generator.rb:4:in '<module:RedmineCkeditor>': uninitialized constant Generators::Base (NameError)
        from /usr/share/redmine/plugins/redmine_ckeditor/lib/generators/redmine_ckeditor/rich_assets/rich_assets_generator.rb:3:in '<top (required)>'
        from /var/lib/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/dependencies/interlock.rb:14:in 'block in loading'
        from /var/lib/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/concurrency/share_lock.rb:151:in 'exclusive'
        from /var/lib/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/dependencies/interlock.rb:13:in 'loading'
        from /var/lib/gems/2.3.0/gems/railties-5.2.3/lib/rails/engine.rb:478:in 'block (2 levels) in eager_load!'
        from /var/lib/gems/2.3.0/gems/railties-5.2.3/lib/rails/engine.rb:477:in 'each'
        from /var/lib/gems/2.3.0/gems/railties-5.2.3/lib/rails/engine.rb:477:in 'block in eager_load!'
        from /var/lib/gems/2.3.0/gems/railties-5.2.3/lib/rails/engine.rb:475:in 'each'
        from /var/lib/gems/2.3.0/gems/railties-5.2.3/lib/rails/engine.rb:475:in 'eager_load!'
        from /var/lib/gems/2.3.0/gems/railties-5.2.3/lib/rails/engine.rb:356:in 'eager_load!'
        from /var/lib/gems/2.3.0/gems/railties-5.2.3/lib/rails/application/finisher.rb:69:in 'each'
        from /var/lib/gems/2.3.0/gems/railties-5.2.3/lib/rails/application/finisher.rb:69:in 'block in <module:Finisher>'
        from /var/lib/gems/2.3.0/gems/railties-5.2.3/lib/rails/initializable.rb:32:in 'instance_exec'
        from /var/lib/gems/2.3.0/gems/railties-5.2.3/lib/rails/initializable.rb:32:in 'run'
        from /var/lib/gems/2.3.0/gems/railties-5.2.3/lib/rails/initializable.rb:61:in 'block in run_initializers'
        from /usr/lib/ruby/2.3.0/tsort.rb:228:in 'block in tsort_each'
        from /usr/lib/ruby/2.3.0/tsort.rb:350:in 'block (2 levels) in each_strongly_connected_component'
        from /usr/lib/ruby/2.3.0/tsort.rb:431:in 'each_strongly_connected_component_from'
        from /usr/lib/ruby/2.3.0/tsort.rb:349:in 'block in each_strongly_connected_component'
        from /usr/lib/ruby/2.3.0/tsort.rb:347:in 'each'
        from /usr/lib/ruby/2.3.0/tsort.rb:347:in 'call'
        from /usr/lib/ruby/2.3.0/tsort.rb:347:in 'each_strongly_connected_component'
        from /usr/lib/ruby/2.3.0/tsort.rb:226:in 'tsort_each'
        from /usr/lib/ruby/2.3.0/tsort.rb:205:in 'tsort_each'
        from /var/lib/gems/2.3.0/gems/railties-5.2.3/lib/rails/initializable.rb:60:in 'run_initializers'
        from /var/lib/gems/2.3.0/gems/railties-5.2.3/lib/rails/application.rb:361:in 'initialize!'
        from /usr/share/redmine/config/environment.rb:14:in '<top (required)>'
        from config.ru:3:in 'require'
        from config.ru:3:in 'block in <main>'
        from /var/lib/gems/2.3.0/gems/rack-2.0.7/lib/rack/builder.rb:55:in 'instance_eval'
        from /var/lib/gems/2.3.0/gems/rack-2.0.7/lib/rack/builder.rb:55:in 'initialize'
        from config.ru:in 'new'
        from config.ru:in '<main>'
        from /var/lib/gems/2.3.0/gems/rack-2.0.7/lib/rack/builder.rb:49:in 'eval'
        from /var/lib/gems/2.3.0/gems/rack-2.0.7/lib/rack/builder.rb:49:in 'new_from_string'
        from /var/lib/gems/2.3.0/gems/rack-2.0.7/lib/rack/builder.rb:40:in 'parse_file'
        from /var/lib/gems/2.3.0/gems/rack-2.0.7/lib/rack/server.rb:319:in 'build_app_and_options_from_config'
        from /var/lib/gems/2.3.0/gems/rack-2.0.7/lib/rack/server.rb:219:in 'app'
        from /var/lib/gems/2.3.0/gems/railties-5.2.3/lib/rails/commands/server/server_command.rb:27:in 'app'
        from /var/lib/gems/2.3.0/gems/rack-2.0.7/lib/rack/server.rb:354:in 'wrapped_app'
        from /var/lib/gems/2.3.0/gems/rack-2.0.7/lib/rack/server.rb:283:in 'start'
        from /var/lib/gems/2.3.0/gems/railties-5.2.3/lib/rails/commands/server/server_command.rb:53:in 'start'
        from /var/lib/gems/2.3.0/gems/railties-5.2.3/lib/rails/commands/server/server_command.rb:147:in 'block in perform'
        from /var/lib/gems/2.3.0/gems/railties-5.2.3/lib/rails/commands/server/server_command.rb:142:in 'tap'
        from /var/lib/gems/2.3.0/gems/railties-5.2.3/lib/rails/commands/server/server_command.rb:142:in 'perform'
        from /var/lib/gems/2.3.0/gems/thor-0.20.3/lib/thor/command.rb:27:in 'run'
        from /var/lib/gems/2.3.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in 'invoke_command'
        from /var/lib/gems/2.3.0/gems/thor-0.20.3/lib/thor.rb:387:in 'dispatch'
        from /var/lib/gems/2.3.0/gems/railties-5.2.3/lib/rails/command/base.rb:65:in 'perform'
        from /var/lib/gems/2.3.0/gems/railties-5.2.3/lib/rails/command.rb:46:in 'invoke'
        from /var/lib/gems/2.3.0/gems/railties-5.2.3/lib/rails/commands.rb:18:in '<top (required)>'
        from bin/rails:4:in 'require'
        from bin/rails:4:in '<main>'
`

**Comment by YoWenhow** [comment]
> I can confirm ckeditor 1.2.1 works well with redmine 4.0.2.
> 
> However, once I updated to redmine 4.0.3, this plugin will fail to start.

This problem is indeed caused by the incompatibility between redmine4.0.3 and ckeditor. When I downgraded to 4.0.2, the problem disappeared. Expect a follow-up version of ckeditor to fix this problem,lol.

**Comment by clauded** [comment]
Here's a workaround (but I'm not sure if it's the right way to fix this). Edit lib/generators/redmine_ckeditor/rich_assets/rich_assets_generator.rb and add this line after **require 'rake'**:

**require 'rails/generators'**

**Comment by ebartlomiej89** [comment]
After adding the **require 'rails/generators'** line, it works.

**Comment by a-ono** [comment]
Fixed in version 1.2.2.
