### ISSUE TITLE
We're sorry, but something went wrong.

### ISSUE THREAD

**Issue by xsunway** [a-ono/redmine_ckeditor#301]
Plugin installation and setup
Download the zip package and extract the directory that it contains into the plugins directory (make sure the name is redmine_ckeditor)

Install the required gems (in the Redmine root directory)

bundle install --without development test
Execute migration

rake redmine:plugins:migrate RAILS_ENV=production
Start Redmine

finsh those , reboot system 
visit redmin home url  , got :
We're sorry, but something went wrong. 
The issue has been logged for investigation. Please try again later.

**Comment by a-ono** [comment]
Maybe fixed in version 1.2.2.
