### ISSUE TITLE
Redmine 5.0 migrate

### ISSUE THREAD

**Issue by blackhase** [a-ono/redmine_ckeditor#347]
Hello, 

i tried to migrate to redmine 5.0. 
I get an Error: 
`LoadError: cannot load such file -- redmine_ckeditor/helper`

Does anyone have an idea?

I'm not Ruby developer. 
Can anyone help me.

Redmine 5.0,
MSSQL 2014
Ubuntu Server 22.04

Regards, 
Andi

**Comment by gabrielklein** [comment]
Similar problem, any idea how to fix it?

**Comment by blackhase** [comment]
Hello, 

Are you planning an upgrade to redmine 5.0?

Regards

**Comment by gabrielklein** [comment]
Some "tips" to fix it (I have not been able to fix it totally).

They have changed the way "require" works.
In init.rb, I've removed the "require_ckeditor"

In lib/ck_editor.rb I have added "base_url"
base_url = File.dirname(__FILE__)
require base_url + '/' + 'redmine_ckeditor/helper'
require base_url + '/' + 'redmine_ckeditor/helper'
require base_url + '/' + 'redmine_ckeditor/application_helper_patch'
require base_url + '/' + 'redmine_ckeditor/queries_helper_patch'
require base_url + '/' + 'redmine_ckeditor/rich_files_helper_patch'
require base_url + '/' + 'redmine_ckeditor/journals_controller_patch'
require base_url + '/' + 'redmine_ckeditor/messages_controller_patch'
require base_url + '/' + 'redmine_ckeditor/mail_handler_patch'
require base_url + '/' + 'redmine_ckeditor/pdf_patch'
require base_url + '/' + 'redmine_ckeditor/tempfile_patch'

But it's not enough.

**Comment by zndos** [comment]
To update the plugin, you also need to update gem 'rich' to zeitwerk .
i updated gem and its work local.
but prod server send error: 
│ │ [1] ! Unable to load application: Zeitwerk::NameError: expected file                                                         ↵
│ │ /usr/local/bundle/bundler/gems/a-ono_rich-2d22ee1ed4dd/app/inputs/rich_input.rb to define constant RichInput, but didn't
│ │ 
│ │       raise Zeitwerk::NameError.new("expected file #{file} to define constant #{cpath}, but didn't", cref.last)
│ │       ^^^^^
│ │ bundler: failed to load command: puma (/usr/local/bundle/bin/puma)
│ │ /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/callbacks.rb:25:in `on_file_autoloaded': expected file             ↵
│ │ /usr/local/bundle/bundler/gems/a-ono_rich-2d22ee1ed4dd/app/inputs/rich_input.rb to define constant RichInput, but didn't     ↵
│ │ (Zeitwerk::NameError)
│ │ 
│ │       raise Zeitwerk::NameError.new("expected file #{file} to define constant #{cpath}, but didn't", cref.last)
│ │       ^^^^^
│ │ 	from /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:28:in `require

**Comment by kamaladafrica** [comment]
There's a fork working on redmine 5 (https://github.com/nomadli/redmine_ckeditor)
Thanks to @nomadli

**Comment by blackhase** [comment]
> There's a fork working on redmine 5 (https://github.com/nomadli/redmine_ckeditor) Thanks to @nomadli

Thank you, work for me.
