### ISSUE TITLE
feature: migrate back to textile

### ISSUE THREAD

**Issue by cforce** [a-ono/redmine_ckeditor#50]
Would be very useful to still be able to turn again back to the old textile style, juts in case this plugin won't be suppiorted any more or users wanna use textile again.

There is already migrating old text to HTML, no the other direction would be available also.
Of course not all formata can be ported and  thats ok.
Said that it would be good to be able to set a compatibility mode, so that vthe ckeditor only offers formatting which can be ported back to textile. So it should be 1:1 mapping table for all available ckeditor formats

**Comment by a-ono** [comment]
It's supported in version 1.0.18.
```
rake redmine_ckeditor:migrate RAILS_ENV=production FROM=html TO=textile
```
