### ISSUE TITLE
Error then adding image

### ISSUE THREAD

**Issue by levich** [a-ono/redmine_ckeditor#54]
![321](https://f.cloud.github.com/assets/1146220/773579/55f3d6f2-e93d-11e2-937e-a096428dc621.png)
If attach Image - i am get error. In production.log
Command :: identify -format '%wx%h,%[exif:orientation]' "C:/Windows/Temp/32120130709-5800-97j8xm.png[0]"
[paperclip] An error was received while processing: #<Paperclip::Errors::NotIdentifiedByImageMagickError: Paperclip::Errors::NotIdentifiedByImageMagickError>

**Comment by a-ono** [comment]
Maybe fixed in version 1.0.18.
