### ISSUE TITLE
Using CKEditor Builder

### ISSUE THREAD

**Issue by muhammadhassan** [a-ono/redmine_ckeditor#87]
I want to have my custom build of CKEditor installed on redmine, can I use CKEditor Builder

http://ckeditor.com/builder

For exampel I want to disable CKEditor spell checking and in order to do this I have make my own build
http://stackoverflow.com/questions/16903392/how-to-enable-browser-spell-check-in-ckeditor-4
Any other customization I want to do.

So my questions, is using CKEditor Builder with this plugin is easy or not and what are steps required to install that custom build.

Thanks a lot.

**Comment by a-ono** [comment]
CKEditor settings can also be configured in master branch.
