### ISSUE TITLE
Using redmine_ckeditor the repository comment issues cannot link

### ISSUE THREAD

**Issue by czhixin** [a-ono/redmine_ckeditor#88]
Hi,Akihiro Ono.When I using redmine_ckeditor the repository comment issues cannot link,how to solve this problem？

Environment:
Redmine version 2.3.3.stable
Ruby version 1.9.3-p231 (2012-05-25)
Rails version 3.2.13
Environment production
Database adapter Mysql2
Redmine plugins:
redmine_ckeditor 1.0.13

http://www.redmine.org/issues/15422

**Comment by a-ono** [comment]
Fixed in 87032a2e554951c1ced7319db49eac53e43ed848
