### ISSUE TITLE
Error migrating

### ISSUE THREAD

**Issue by LuisSerrano** [a-ono/redmine_ckeditor#98]
When I try to migrate mi database the script return this error:

Migrating issues ... (2965/3315)rake aborted!
Attempted to update a stale object: Issue
/opt/redmine/app/models/issue.rb:165:in `create_or_update'
/opt/redmine/plugins/redmine_ckeditor/lib/tasks/ckeditor.rake:87:in `block in migrate'
/opt/redmine/plugins/redmine_ckeditor/lib/tasks/ckeditor.rake:84:in `migrate'
/opt/redmine/plugins/redmine_ckeditor/lib/tasks/ckeditor.rake:69:in `block in start'
/opt/redmine/plugins/redmine_ckeditor/lib/tasks/ckeditor.rake:65:in `each'
/opt/redmine/plugins/redmine_ckeditor/lib/tasks/ckeditor.rake:65:in `start'
/opt/redmine/plugins/redmine_ckeditor/lib/tasks/ckeditor.rake:101:in `block (2 levels) in <top (required)>'
Tasks: TOP => redmine_ckeditor:migrate
(See full trace by running task with --trace)

Could you help me please ?

**Comment by a-ono** [comment]
Please try version 1.0.18.
